<?php

$install_lang["admin_header_geomap_change"] = "Change map key";
$install_lang["admin_header_geomap_edit"] = "Map settings";
$install_lang["admin_header_geomap_settings_change"] = "Edit map settings";
$install_lang["admin_header_geomap_settings_edit"] = "Map settings";
$install_lang["admin_header_list"] = "Geo maps";
$install_lang["driver_info"] = "Details";
$install_lang["driver_key_notrequired"] = "Key is not required";
$install_lang["driver_name_bingmapsv7"] = "Bing maps (API v7)";
$install_lang["driver_name_googlemaps"] = "Google maps (API v2)";
$install_lang["driver_name_googlemapsv3"] = "Google maps (API v3)";
$install_lang["driver_name_yandexmaps"] = "Yandex maps (API v1)";
$install_lang["driver_name_yandexmapsv2"] = "Yandex maps (API v2)";
$install_lang["driver_registration"] = "Get key";
$install_lang["error_cant_save_settings"] = "Cannot save settings, please try again";
$install_lang["field_amenities"] = "Amenities";
$install_lang["field_default_lat"] = "Default latitude";
$install_lang["field_default_lon"] = "Default longitude";
$install_lang["field_default_zoom"] = "Default zoom";
$install_lang["field_driver"] = "Map type";
$install_lang["field_link"] = "Authorization";
$install_lang["field_map_gid"] = "Map object";
$install_lang["field_marker_icon"] = "Icon";
$install_lang["field_marker_icon_delete"] = "Remove";
$install_lang["field_regkey"] = "Key";
$install_lang["field_show_details"] = "Show object details";
$install_lang["field_status"] = "Used";
$install_lang["field_title"] = "Name";
$install_lang["field_use_amenities"] = "Use amenities";
$install_lang["field_use_click_zoom"] = "Use click zoom";
$install_lang["field_use_clusterer"] = "Use clusterer";
$install_lang["field_use_panorama"] = "Use panorama";
$install_lang["field_use_router"] = "Use router";
$install_lang["field_use_search_auto"] = "Use search autocomplete";
$install_lang["field_use_search_radius"] = "Use search radius";
$install_lang["field_use_searchbox"] = "Use searchbox";
$install_lang["field_use_show_details"] = "Show details";
$install_lang["field_use_smart_zoom"] = "Use smart zoom";
$install_lang["field_use_tools"] = "Use tools bar";
$install_lang["field_use_type_selector"] = "Use type selector";
$install_lang["field_view_type"] = "Default view";
$install_lang["header_amenity_select"] = "Amenities selection";
$install_lang["link_activate_geomap"] = "Activate";
$install_lang["link_active_geomap"] = "Active";
$install_lang["link_edit_driver"] = "Edit";
$install_lang["link_reset_all"] = "Reset all";
$install_lang["link_select_amenities"] = "Select amenities";
$install_lang["link_select_amenity"] = "Select amenity";
$install_lang["link_settings_driver"] = "Edit map settings";
$install_lang["link_tableicon_edit_driver"] = "Map key";
$install_lang["link_tableicon_settings_driver"] = "Setup";
$install_lang["link_view_map"] = "View on map";
$install_lang["loading"] = "Loading...";
$install_lang["map_default"] = "Initial map";
$install_lang["map_example"] = "Example";
$install_lang["map_example_1_text"] = "<img src=\"/uploads/default/maps_example_1.jpeg\" align=\"left\" hspace=\"4\">\n<b>London</b><br>\n<b>Tower Bridge</b> is a combined bascule and suspension bridge<br>\nin London, England, over the River Thames. It is close to the Tower of London,<br>\nwhich gives it its name. It has become an iconic symbol of London.";
$install_lang["map_example_2_text"] = "<img src=\"/uploads/default/maps_example_2.jpg\" align=\"left\" hspace=\"4\">\n<b>France</b><br>\nThe <b>Eiffel Tower</b> is an iron lattice tower located on the Champ de Mars in Paris.<br>\nBuilt in 1889, it has become a global icon of France";
$install_lang["map_example_3_text"] = "<img src=\"/uploads/default/maps_example_3.jpg\" align=\"left\" hspace=\"4\">\n<b>Italy</b><br>\n<b>Pisa</b> is a city in Tuscany, Central Italy, on the right bank of the mouth of the <br>\nRiver Arno on the Ligurian Sea. It is the capital city of the Province of Pisa. <br>\nPisa is known worldwide for its Leaning Tower (the bell tower of the city's cathedral)";
$install_lang["map_example_4_text"] = "<img src=\"/uploads/default/maps_example_4.jpeg\" align=\"left\" hspace=\"4\">\n<b>Neuschwanstein Castle</b><br>\nGerman: Schloss Neuschwanstein is a 19th-century<br>\nGothic Revival palace on a rugged hill above the village of<br>\nHohenschwangau near Füssen in southwest Bavaria, Germany.";
$install_lang["map_example_header"] = "European tour";
$install_lang["route_add"] = "Add route";
$install_lang["route_delete"] = "Remove route";
$install_lang["set_general_settings_point_text"] = "<b>Drag the marker to set up default map point</b>";
$install_lang["success_update_driver"] = "Key is successfully saved";
$install_lang["success_update_driver_settings"] = "Settings are successfully updated";
$install_lang["text_availbale_select_amenities"] = "Available for selection";

