<?php

$install_lang["admin_header_configuration"] = "Configuration";
$install_lang["admin_header_preview"] = "Preview";
$install_lang["admin_header_widget_code"] = "Cope and paste the code onto a website";
$install_lang["admin_header_widget_edit"] = "Edit widget";
$install_lang["admin_header_widgets_install"] = "Enabled widgets";
$install_lang["admin_header_widgets_list"] = "Installed widgets";
$install_lang["btn_get_code"] = "Get code";
$install_lang["colors_background"] = "background";
$install_lang["colors_block"] = "copyright";
$install_lang["colors_border"] = "border";
$install_lang["colors_header"] = "header";
$install_lang["colors_link"] = "links";
$install_lang["colors_text"] = "text";
$install_lang["error_module_install"] = "The module is not installed";
$install_lang["error_widget_invalid"] = "Path to widget is invalid";
$install_lang["field_module"] = "Module";
$install_lang["field_name"] = "Name";
$install_lang["field_widget_colors"] = "Colors";
$install_lang["field_widget_footer"] = "Footer";
$install_lang["field_widget_size"] = "Size";
$install_lang["field_widget_title"] = "Title";
$install_lang["link_delete_widget"] = "Remove widget";
$install_lang["link_edit_widget"] = "Edit widget";
$install_lang["link_install_widget"] = "Install";
$install_lang["no_widgets"] = "No widgets";
$install_lang["no_widgets_install"] = "No widgets. <a href=\"http://pilotgroup.zendesk.com/tickets/new/\">Contact us</a> for more details.";
$install_lang["note_delete_widget"] = "Would you like to delete the widget?";
$install_lang["success_widget_delete"] = "The widget is successfully removed";
$install_lang["success_widget_install"] = "The widget is successfully installed";
$install_lang["success_widget_update"] = "The widget is successfully updated";
