<?php

return array(
    'site_stat_block' => array(
        'gid'    => 'site_stat_block',
        'module' => 'start',
        'model'  => 'Start_model',
        'method' => '_dynamic_block_get_stat_block',
        'views'  => array(
            array(
                'gid' => 'default',
            ),
        ),
        'params' => '',
    ),
    'search_form_block' => array(
        'gid'    => 'search_form_block',
        'module' => 'start',
        'model'  => 'Start_model',
        'method' => '_dynamic_block_get_search_form',
        'views'  => array(
            array(
                'gid' => 'default',
            ),
        ),
        'params'  => '',
        'area'    => array(),
        'presets' => array(
            array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '11',
                'x'          => '0',
                'y'          => '7',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '600',
                'sorter'     => '11',
                'x'          => '0',
                'y'          => '7',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'jewish',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '5',
                'x'          => '0',
                'y'          => '3',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lovers',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '5',
                'x'          => '0',
                'y'          => '3',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'blackonwhite',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '6',
                'x'          => '0',
                'y'          => '4',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'deepblue',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '5',
                'x'          => '0',
                'y'          => '3',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'community',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '4',
                'x'          => '0',
                'y'          => '2',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'christian',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '7',
                'x'          => '0',
                'y'          => '5',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'persimmon_red',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'sorter'     => '10',
                'cache_time' => '0',
                'x'          => '0',
                'y'          => '6',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
    ),
);
