<?php
return [
    'news' => [
        [
            'gid' => 'ec165f2377a90be148988d21d4b40268',
            'name' => 'ЦБ РФ выпустил монету в честь Тюменской области',
            'annotation' => 'Банк России 7 августа 2014 г. выпускает в обращение памятную монету из недрагоценного металла номиналом 10 рублей серии "Российская Федерация": Тюменская область.',
            'content' => 'Банк России 7 августа 2014 г. выпускает в обращение памятную монету из недрагоценного металла номиналом 10 рублей серии "Российская Федерация": Тюменская область.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'ru',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.vestifinance.ru/articles/45637',
            'feed_id' => 2,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'e08d87e5c4a756c1167aea7ba497ba15',
            'name' => 'Чемпионат мира по гребле в Крылатском',
            'annotation' => 'В Москву приехало 950 спортсменов из 75 стран мира, чтобы сразиться за звание чемпиона мира по гребле на байдарках и каноэ. Специально к чемпионату гребной канал "Крылатское" был отреставрирован, тем самым вернув себе звание главного центра водного спорта России',
            'content' => 'В Москву приехало 950 спортсменов из 75 стран мира, чтобы сразиться за звание чемпиона мира по гребле на байдарках и каноэ. Специально к чемпионату гребной канал "Крылатское" был отреставрирован, тем самым вернув себе звание главного центра водного спорта России',
            'img' => '',
            'status' => 1,
            'lang_code' => 'ru',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.vesti.ru/doc.html?id=1874336',
            'feed_id' => 2,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => '-quot-quot-',
            'name' => 'Российский пункт пропуска &quot;Матвеев Курган&quot; приостановил работу из-за стрельбы на Украине',
            'annotation' => 'Российский пункт пропуска "Матвеев Курган" в Ростовской области приостановил приграничный контроль из-за интенсивной стрельбы на Украине. Люди, находившиеся между украинским и российским пунктами пропуска, эвакуированы в здание пункта пропуска "Матвеев Курган". Жертв и пострадавших нет.',
            'content' => 'Российский пункт пропуска "Матвеев Курган" в Ростовской области приостановил приграничный контроль из-за интенсивной стрельбы на Украине. Люди, находившиеся между украинским и российским пунктами пропуска, эвакуированы в здание пункта пропуска "Матвеев Курган". Жертв и пострадавших нет.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'ru',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.vesti.ru/doc.html?id=1874296',
            'feed_id' => 2,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => '-2014-',
            'name' => 'Аэропорт Франкфурта ухудшил прогноз продаж на 2014 год',
            'annotation' => 'Оператор франкфуртского международного аэропорта Fraport AG понизил прогноз розничных продаж на текущий год, сообщает агентство Bloomberg.',
            'content' => 'Оператор франкфуртского международного аэропорта Fraport AG понизил прогноз розничных продаж на текущий год, сообщает агентство Bloomberg.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'ru',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.vestifinance.ru/articles/45633',
            'feed_id' => 2,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'doctor-who-gets-red-carpet-premiere',
            'name' => 'Doctor Who gets red carpet premiere',
            'annotation' => 'Stars of the cult sci-fi TV show Doctor Who will greet fans at a red carpet event in Cardiff, as the first episode of the new series is given its world premiere.',
            'content' => 'Stars of the cult sci-fi TV show Doctor Who will greet fans at a red carpet event in Cardiff, as the first episode of the new series is given its world premiere.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.bbc.co.uk/news/uk-wales-28678387#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'feed_id' => 1,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'dame-helen-to-play-queen-on-broadway',
            'name' => 'Dame Helen to play Queen on Broadway',
            'annotation' => 'West End hit The Audience, starring Dame Helen Mirren as Queen Elizabeth II, is to transfer to Broadway next year.',
            'content' => 'West End hit The Audience, starring Dame Helen Mirren as Queen Elizabeth II, is to transfer to Broadway next year.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.bbc.co.uk/news/entertainment-arts-28688167#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'feed_id' => 1,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'belgian-dance-company-sacks-director',
            'name' => 'Belgian dance company sacks director',
            'annotation' => 'The former head of a leading English dance company who was made an MBE in the New Year Honours list is sacked by Royal Ballet of Flanders.',
            'content' => 'The former head of a leading English dance company who was made an MBE in the New Year Honours list is sacked by Royal Ballet of Flanders.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.bbc.co.uk/news/entertainment-arts-28686523#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'feed_id' => 1,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'celebrities-call-for-scots-no-vote',
            'name' => 'Celebrities call for Scots No vote',
            'annotation' => 'Public figures including Sir Mick Jagger and Dame Judi Dench urge Scotland to say "No" to independence, despite not being able to vote in the referendum.',
            'content' => 'Public figures including Sir Mick Jagger and Dame Judi Dench urge Scotland to say "No" to independence, despite not being able to vote in the referendum.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.bbc.co.uk/news/uk-scotland-scotland-politics-28687880#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'feed_id' => 1,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'bake-off-return-attracts-7-2-million',
            'name' => 'Bake Off return attracts 7.2 million',
            'annotation' => 'The Great British Bake Off returned to TV screens, with its first episode attracting an average 7.2 million viewers.',
            'content' => 'The Great British Bake Off returned to TV screens, with its first episode attracting an average 7.2 million viewers.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.bbc.co.uk/news/entertainment-arts-28686596#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'feed_id' => 1,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'tech-activity-overtakes-sleeping-',
            'name' => 'Tech activity "overtakes sleeping"',
            'annotation' => 'The communications regulator Ofcom indicates that on average, UK adults spend eight hours and 41 minutes of their day on media devices.',
            'content' => 'The communications regulator Ofcom indicates that on average, UK adults spend eight hours and 41 minutes of their day on media devices.',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2014-10-25 12:35:40',
            'feed_link' => 'http://www.bbc.co.uk/news/technology-28677674#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'feed_id' => 1,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
    ],
    'feeds' => [
        [
            'link' => 'http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml',
            'title' => 'BBC News - Entertainment &amp; Arts',
            'description' => 'The latest stories from the Entertainment & Arts section of the BBC News web site.',
            'site_link' => 'http://www.bbc.co.uk/news/entertainment_and_arts/#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'encoding' => 'UTF-8',
            'status' => '1',
            'lang' => 'en',
            'max_news' => '10',
            'date_add' => '2014-08-07 15:30:09'
        ],
        [
            'link' => 'http://www.vesti.ru/vesti.rss',
            'title' => 'ВЕСТИ',
            'description' => 'ВЕСТИ',
            'site_link' => 'http://www.vesti.ru',
            'encoding' => 'UTF-8',
            'status' => '1',
            'lang' => 'ru',
            'max_news' => '10',
            'date_add' => '2014-08-07 15:30:27'
        ],
    ],
];
