<?php

return array(
    'products' => array(
        array(
            'id'            => '1',
            'gid'           => 'cake',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '10.0000',
            'price_reduced' => '10.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '10',
            'is_bestseller' => '0',
            'priority'      => '2',
            'search_data'   => '10,Cake,Every birthday, every celebration ends with a delicious cake.	Made from a mix, this cake is particularly moist and fudgy, thanks to two secret ingredients. Combine packaged coconut and nuts with creamy chocolate frosting to create the irresistible filling.,Торт,Шоколадный торт с кокосовой начинкой. Бисквит очень нежный, очень шоколадный, почти без муки. Начинка состоит полностью из натуральных продуктов.,Paperboard,2kg',
            'photo'         => 'a:3:{i:0;s:14:"a39c35cb29.png";i:1;s:14:"498e3e10e6.png";i:2;s:14:"a1873f9b77.jpg";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-11 18:14:22',
            'name'          => array(
                'en' => 'Cake',
                'de' => 'Cake',
                'ru' => 'Торт',
            ),
            'description' => array(
                'en' => 'Every birthday, every celebration ends with a delicious cake. Made from a mix, this cake is particularly moist and fudgy, thanks to two secret ingredients. Combine packaged coconut and nuts with creamy chocolate frosting to create the irresistible filling.',
                'de' => 'Every birthday, every celebration ends with a delicious cake. Made from a mix, this cake is particularly moist and fudgy, thanks to two secret ingredients. Combine packaged coconut and nuts with creamy chocolate frosting to create the irresistible filling.',
                'ru' => 'Шоколадный торт с кокосовой начинкой. Бисквит очень нежный, очень шоколадный, почти без муки. Начинка состоит полностью из натуральных продуктов.',
            ),
            'option_5' => 'a:1:{i:2;s:1:"2";}',
            'option_8' => 'a:1:{i:6;s:1:"6";}',
        ),
        array(
            'id'            => '2',
            'gid'           => 'fruitcake',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '12.0000',
            'price_reduced' => '12.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '12',
            'is_bestseller' => '1',
            'priority'      => '1',
            'search_data'   => '12,Fruit cake,What makes this fruitcake so special? Well, it\'s made with dried fruit, not candied fruit; it features lots of dried cherries, raspberries, cranberries, and currants. A little dark rum, molasses, and butter make it truly delicious.,Торт с фруктами,Что может быть вкуснее, чем торт со свежими фруктами? Фрукты и ягоды можно использовать не только для украшения, но и для начинки. Под тонким слоем ягодного желе - нежный мусс из ягод на тончайшем слое теста... Превосходный подарок!,Paperboard,1kg',
            'photo'         => 'a:3:{i:0;s:14:"4331959740.jpg";i:1;s:14:"d241a5d511.jpg";i:2;s:14:"fb8eaf851e.jpg";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-12 14:02:58',
            'name'          => array(
                'en' => 'Fruit cake',
                'de' => 'Fruit cake',
                'ru' => 'Торт с фруктами',
            ),
            'description' => array(
                'en' => 'What makes this fruitcake so special? Well, it\'s made with dried fruit, not candied fruit; it features lots of dried cherries, raspberries, cranberries, and currants. A little dark rum, molasses, and butter make it truly delicious.',
                'de' => 'What makes this fruitcake so special? Well, it\'s made with dried fruit, not candied fruit; it features lots of dried cherries, raspberries, cranberries, and currants. A little dark rum, molasses, and butter make it truly delicious.',
                'ru' => 'Что может быть вкуснее, чем торт со свежими фруктами? Фрукты и ягоды можно использовать не только для украшения, но и для начинки. Под тонким слоем ягодного желе - нежный мусс из ягод на тончайшем слое теста... Превосходный подарок!',
            ),
            'option_5' => 'a:1:{i:1;s:1:"1";}',
            'option_8' => 'a:1:{i:6;s:1:"6";}',
        ),
        array(
            'id'            => '3',
            'gid'           => 'chocolates',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '28.0000',
            'price_reduced' => '28.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '29',
            'is_bestseller' => '0',
            'priority'      => '3',
            'search_data'   => '28.5,Chocolates,An assortment of dark chocolate, milk chocolate and white chocolate products. Expertly crafted fine cocoa makes the best-tasting chocolate.<br>-Milk Chocolate Gourmet Truffle: The creamy center is twice dipped into the smooth milk chocolate.<br>-Dark Chocolate Vanilla Gourmet Truffle: A vanilla-infused soft truffle center is enrobed with a drizzled, dark chocolate shell.<br>-White Chocolate Gourmet Truffle: A rich, creamy white chocolate center is surrounded with twice-dipped white chocolate.,Chocolates,Подарки из шоколада - лучшие подарки для гурманов и ценителей!<br>Конфеты из молочного шоколада с нежной начинкой из тертого ореха. Подходят в качестве десерта к чаю или кофе. Набор представлен в красочной картонной упаковке.,1kg',
            'photo'         => 'a:4:{i:0;s:14:"34e0924af0.png";i:1;s:14:"06b9dc9570.jpg";i:2;s:14:"9958b5dc36.jpg";i:3;s:14:"de1589150c.jpg";}','photo_count' => '4',
            'date_created'  => '2014-12-12 14:17:03',
            'name'          => array(
                'en' => 'Chocolates',
                'de' => 'Chocolates',
                'ru' => 'Chocolates',
            ),
            'description' => array(
                'en' => 'An assortment of dark chocolate, milk chocolate and white chocolate products. Expertly crafted fine cocoa makes the best-tasting chocolate.<br> -Milk Chocolate Gourmet Truffle: The creamy center is twice dipped into the smooth milk chocolate.<br> -Dark Chocolate Vanilla Gourmet Truffle: A vanilla-infused soft truffle center is enrobed with a drizzled, dark chocolate shell.<br> -White Chocolate Gourmet Truffle: A rich, creamy white chocolate center is surrounded with twice-dipped white chocolate.',
                'de' => 'An assortment of dark chocolate, milk chocolate and white chocolate products. Expertly crafted fine cocoa makes the best-tasting chocolate.<br> -Milk Chocolate Gourmet Truffle: The creamy center is twice dipped into the smooth milk chocolate.<br> -Dark Chocolate Vanilla Gourmet Truffle: A vanilla-infused soft truffle center is enrobed with a drizzled, dark chocolate shell.<br> -White Chocolate Gourmet Truffle: A rich, creamy white chocolate center is surrounded with twice-dipped white chocolate.',
                'ru' => 'Подарки из шоколада - лучшие подарки для гурманов и ценителей! Конфеты из молочного шоколада с нежной начинкой из тертого ореха. Подходят в качестве десерта к чаю или кофе. Набор представлен в красочной картонной упаковке.',
            ),
            'option_5' => 'a:1:{i:1;s:1:"1";}',
        ),
        array(
            'id'            => '4',
            'gid'           => 'surprise',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '15.0000',
            'price_reduced' => '15.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '15',
            'is_bestseller' => '0',
            'priority'      => '4',
            'search_data'   => '15,Surprise gift,Treat yourself to a surprise gift or make a compliment to someone you\'ve met on this site. Hint: the gift is made out of the finest cocoa beans.,Подарок-сюрприз,Порадуйте себя или сделайте комплимент понравившемуся пользователю сайта - закажите подарок-сюрприз! Намек: при изготовлении подарка использовались только самые лучшие сорта какао.,Paperboard,2kg',
            'photo'         => 'a:2:{i:0;s:14:"d32d653a65.png";i:1;s:14:"5dbe682c06.png";}',
            'photo_count'   => '2',
            'date_created'  => '2014-12-12 14:30:38',
            'name'          => array(
                'en' => 'Surprise gift',
                'de' => 'Surprise gift',
                'ru' => 'Подарок-сюрприз',
            ),
            'description' => array(
                'en' => 'Treat yourself to a surprise gift or make a compliment to someone you\'ve met on this site. Hint: the gift is made out of the finest cocoa beans.',
                'de' => 'Treat yourself to a surprise gift or make a compliment to someone you\'ve met on this site. Hint: the gift is made out of the finest cocoa beans.',
                'ru' => 'Порадуйте себя или сделайте комплимент понравившемуся пользователю сайта - закажите подарок-сюрприз! Намек: при изготовлении подарка использовались только самые лучшие сорта какао.',
            ),
            'option_5' => 'a:1:{i:2;s:1:"2";}',
            'option_8' => 'a:1:{i:6;s:1:"6";}',
        ),
        array(
            'id'            => '5',
            'gid'           => 'decorations_christmas',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '55.0000',
            'price_reduced' => '49.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '55',
            'is_bestseller' => '1',
            'priority'      => '5',
            'search_data'   => '49,Christmas decorations,This amazing array of ornaments is done in dazzling silver, red, and gold colours with a mixture of shiny, matte and glitter designed finishes. The assortment includes 7 pieces of ornament. Christmas decorations are a fun and festive part of the holiday season.<br>Shatter-resistant ornament decorations bring holiday cheer to any room.,Новогодние украшения,Украшения к зимним праздникам позволят вам без особых затрат изменить дом к Новому Году. Они помогут вам создать праздничное настроение тысячью способов.<br>Выдувное стекло; ручная работа; каждое изделие изготовлено искусным мастером.,Gold,7',
            'photo'         => 'a:4:{i:0;s:14:"8f2fcba88a.png";i:1;s:14:"d91deecb58.png";i:2;s:14:"c57b1a2b6e.jpg";i:3;s:14:"7abc1080fd.jpg";}',
            'photo_count'   => '4',
            'date_created'  => '2014-12-16 10:19:04',
            'name'          => array(
                'en' => 'Christmas decorations',
                'de' => 'Christmas decorations',
                'ru' => 'Новогодние украшения',
            ),
            'description' => array(
                'en' => 'This amazing array of ornaments is done in dazzling silver, red, and gold colours with a mixture of shiny, matte and glitter designed finishes. The assortment includes 7 pieces of ornament. Christmas decorations are a fun and festive part of the holiday season.<br> Shatter-resistant ornament decorations bring holiday cheer to any room.',
                'de' => 'This amazing array of ornaments is done in dazzling silver, red, and gold colours with a mixture of shiny, matte and glitter designed finishes. The assortment includes 7 pieces of ornament. Christmas decorations are a fun and festive part of the holiday season.<br> Shatter-resistant ornament decorations bring holiday cheer to any room.',
                'ru' => 'Украшения к зимним праздникам позволят вам без особых затрат изменить дом к Новому Году. Они помогут вам создать праздничное настроение тысячью способов.<br> Выдувное стекло; ручная работа; каждое изделие изготовлено искусным мастером.',
            ),
            'option_2' => 'a:1:{i:19;s:2:"19";}',
            'option_7' => 'a:1:{i:7;s:1:"7";}',
        ),
        array(
            'id'            => '6',
            'gid'           => 'decorations_christmas_red',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '55.0000',
            'price_reduced' => '49.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '55',
            'is_bestseller' => '1',
            'priority'      => '6',
            'search_data'   => '49,Christmas decorations,Shatter-Resistant Ornaments (7-Piece) set is an amazing array of ornaments designed in reds, blues, mint green and silver and in a mix of shiny, matte and glitter finishes. Perfect for your tree or placed around your home, this eye-catching assortment will bring a festive feel to your decor and stores easily for season after season enjoyment.,Новогодние украшения,Елочные игрушки от известных мировых производителей — это эксклюзивные изделия ручной работы. Элегантные, изготовленные с применением редких новаторских технологий, это не просто новогодние игрушки, а роскошные сувениры. Все наши изделия расписываются вручную, и поэтому любое украшение обладает исключительной индивидуальностью.,Red,7',
            'photo'         => 'a:3:{i:0;s:14:"ca986c367d.png";i:1;s:14:"4175bad454.jpg";i:2;s:14:"482efa2d9a.jpg";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 10:45:20',
            'name'          => array(
                'en' => 'Christmas decorations',
                'de' => 'Christmas decorations',
                'ru' => 'Новогодние украшения',
            ),
            'description' => array(
                'en' => 'Shatter-Resistant Ornaments (7-Piece) set is an amazing array of ornaments designed in reds, blues, mint green and silver and in a mix of shiny, matte and glitter finishes. Perfect for your tree or placed around your home, this eye-catching assortment will bring a festive feel to your decor and stores easily for season after season enjoyment.',
                'de' => 'Shatter-Resistant Ornaments (7-Piece) set is an amazing array of ornaments designed in reds, blues, mint green and silver and in a mix of shiny, matte and glitter finishes. Perfect for your tree or placed around your home, this eye-catching assortment will bring a festive feel to your decor and stores easily for season after season enjoyment.',
                'ru' => 'Елочные игрушки от известных мировых производителей — это эксклюзивные изделия ручной работы. Элегантные, изготовленные с применением редких новаторских технологий, это не просто новогодние игрушки, а роскошные сувениры. Все наши изделия расписываются вручную, и поэтому любое украшение обладает исключительной индивидуальностью.',
            ),
            'option_2' => 'a:1:{i:2;s:1:"2";}',
            'option_7' => 'a:1:{i:7;s:1:"7";}',
        ),
        array(
            'id'            => '7',
            'gid'           => 'decorations_christmas_silver',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '55.0000',
            'price_reduced' => '49.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '55',
            'is_bestseller' => '1',
            'priority'      => '7',
            'search_data'   => '49,Christmas decorations,Add a handsome finishing touch to your tree this year with the beautiful 7-piece assortment from Snowberry. With 10 incandescent lights to create a warm, comforting glow, the crystal-clear design will complement any style of decor. Specially molded to display a crystal-like effect, this elegant pack is sure to become a focal point in your holiday scene.,Новогодние украшения,Ваша елочка может выглядеть словно красотка с обложки глянцевого журнала - если бы существовали модные журналы для елок! Вы можете детально продумать ее стиль, подобрать аксессуары и сотворить изумительный праздничный наряд. Украшение елки – тоже искусство, так почему бы не применить свои творческие способности, чтобы создать новогодний шедевр?<br>Елочные шары и другие украшения в оконных проемах, на декоративных венках или в вазах. Придумайте свои собственные новогодние традиции!,Silver,7',
            'photo'         => 'a:3:{i:0;s:14:"2cf6e854a8.jpg";i:1;s:14:"ba264f7040.jpg";i:2;s:14:"4afa8f7b6b.jpg";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 10:49:08',
            'name'          => array(
                'en' => 'Christmas decorations',
                'de' => 'Christmas decorations',
                'ru' => 'Новогодние украшения',
            ),
            'description' => array(
                'en' => 'Add a handsome finishing touch to your tree this year with the beautiful 7-piece assortment from Snowberry. With 10 incandescent lights to create a warm, comforting glow, the crystal-clear design will complement any style of decor. Specially molded to display a crystal-like effect, this elegant pack is sure to become a focal point in your holiday scene.',
                'de' => 'Add a handsome finishing touch to your tree this year with the beautiful 7-piece assortment from Snowberry. With 10 incandescent lights to create a warm, comforting glow, the crystal-clear design will complement any style of decor. Specially molded to display a crystal-like effect, this elegant pack is sure to become a focal point in your holiday scene.',
                'ru' => 'Ваша елочка может выглядеть словно красотка с обложки глянцевого журнала - если бы существовали модные журналы для елок! Вы можете детально продумать ее стиль, подобрать аксессуары и сотворить изумительный праздничный наряд. Украшение елки – тоже искусство, так почему бы не применить свои творческие способности, чтобы создать новогодний шедевр?<br> Елочные шары и другие украшения в оконных проемах, на декоративных венках или в вазах. Придумайте свои собственные новогодние традиции!',
            ),
            'option_2' => 'a:1:{i:20;s:2:"20";}',
            'option_7' => 'a:1:{i:7;s:1:"7";}',
        ),
        array(
            'id'            => '8',
            'gid'           => 'decorations_halloween',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '64.0000',
            'price_reduced' => '57.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '64',
            'is_bestseller' => '1',
            'priority'      => '8',
            'search_data'   => '57,Halloween decorations,Whether your gathering is a sit-down dinner or a casual open house, these scary sights ensure your party is a scream. Dreadfully sophisticated and shockingly fun, a carved illuminated pumpkin gets Halloween off to a screaming start.,Украшения к Хэллоуину,Для всех любителей этого праздника и для всех, кто просто хочет освежить свой дом необычным декором, мы предлагаем интересные идеи украшений дома в стиле Хэллоуина. Традиционно принято украшать свой дом страшными картинами и композициями, напоминающими фильмы ужасов. Тем не менее, декор может быть очень даже стильным, современным и красивым. Достаточно понаблюдать за изменениями, которые происходят в эти дни в окружающей природе. Например, можно использовать определенные цвета, характерные для осени – оранжевый, желтый, коричневый, и предметы – листья, ветки и, конечно, тыквы.,Orange,3',
            'photo'         => 'a:2:{i:0;s:14:"248ce391e4.png";i:1;s:14:"cd5ef6f33a.png";}',
            'photo_count'   => '2',
            'date_created'  => '2014-12-16 10:54:47',
            'name'          => array(
                'en' => 'Halloween decorations',
                'de' => 'Halloween decorations',
                'ru' => 'Украшения к Хэллоуину',
            ),
            'description' => array(
                'en' => 'Whether your gathering is a sit-down dinner or a casual open house, these scary sights ensure your party is a scream.<br> Dreadfully sophisticated and shockingly fun, a carved illuminated pumpkin gets Halloween off to a screaming start.',
                'de' => 'Whether your gathering is a sit-down dinner or a casual open house, these scary sights ensure your party is a scream.<br> Dreadfully sophisticated and shockingly fun, a carved illuminated pumpkin gets Halloween off to a screaming start.',
                'ru' => 'Для всех любителей этого праздника и для всех, кто просто хочет освежить свой дом необычным декором, мы предлагаем интересные идеи украшений дома в стиле Хэллоуина. Традиционно принято украшать свой дом страшными картинами и композициями, напоминающими фильмы ужасов. Тем не менее, декор может быть очень даже стильным, современным и красивым. Достаточно понаблюдать за изменениями, которые происходят в эти дни в окружающей природе. Например, можно использовать определенные цвета, характерные для осени – оранжевый, желтый, коричневый, и предметы – листья, ветки и, конечно, тыквы.',
            ),
            'option_2' => 'a:1:{i:13;s:2:"13";}',
            'option_7' => 'a:1:{i:3;s:1:"3";}',
        ),
        array(
            'id'            => '9',
            'gid'           => 'roses',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '60.0000',
            'price_reduced' => '50.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '60',
            'is_bestseller' => '1',
            'priority'      => '9',
            'search_data'   => '50,Roses,Picked fresh from the farm to cast a warm ray of sunlight into their everyday, the Rose Bouquet blooms with an eye-catching array of colours in honour of any of life\'s special moments. Hand gathered in select floral farms and bringing together the hot colors of vibrant pink, orange, and yellow, this exquisite rose bouquet has been picked fresh for you to help you celebrate a birthday, to express your get well wishes, or to offer a fresh perspective on life\'s sweet surprises.,Розы,Этот очаровательный букет напоминает брызги ярких красок. Словно фруктовые цветные леденцы, в композиции собраны яркие солнечные цветы. Этот букет словно создан для юной, мечтательной и всегда улыбающейся девушки!,Paper,11',
            'photo'         => 'a:5:{i:0;s:14:"3b13b666b6.png";i:1;s:14:"5cb930f090.jpg";i:2;s:14:"0e825896ff.jpg";i:3;s:14:"96e7f1c37c.jpg";i:4;s:14:"62b8a96c95.jpg";}',
            'photo_count'   => '5',
            'date_created'  => '2014-12-16 13:25:17',
            'name'          => array(
                'en' => 'Roses',
                'de' => 'Roses',
                'ru' => 'Розы',
            ),
            'description' => array(
                'en' => 'Picked fresh from the farm to cast a warm ray of sunlight into their everyday, the Rose Bouquet blooms with an eye-catching array of colours in honour of any of life\'s special moments. Hand gathered in select floral farms and bringing together the hot colors of vibrant pink, orange, and yellow, this exquisite rose bouquet has been picked fresh for you to help you celebrate a birthday, to express your get well wishes, or to offer a fresh perspective on life\'s sweet surprises.',
                'de' => 'Picked fresh from the farm to cast a warm ray of sunlight into their everyday, the Rose Bouquet blooms with an eye-catching array of colours in honour of any of life\'s special moments. Hand gathered in select floral farms and bringing together the hot colors of vibrant pink, orange, and yellow, this exquisite rose bouquet has been picked fresh for you to help you celebrate a birthday, to express your get well wishes, or to offer a fresh perspective on life\'s sweet surprises.',
                'ru' => 'Этот очаровательный букет напоминает брызги ярких красок. Словно фруктовые цветные леденцы, в композиции собраны яркие солнечные цветы. Этот букет словно создан для юной, мечтательной и всегда улыбающейся девушки!',
            ),
            'option_7' => 'a:1:{i:11;s:2:"11";}',
            'option_8' => 'a:1:{i:4;s:1:"4";}',
        ),
        array(
            'id'            => '10',
            'gid'           => 'tulips',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '45.0000',
            'price_reduced' => '39.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '45',
            'is_bestseller' => '1',
            'priority'      => '10',
            'search_data'   => '39,Tulips,The brightly coloured bulb of the tulip and its elegant, long green stem with velveteen leaves make it one of the most recognizable flowers in the world. Our tulip bouquets are so fresh and crisp you\'ll think we\'ve captured spring itself and delivered it to your door. The bright, pastel colors bring a big dose of sunshine into any room.,Тюльпаны,Розовые тюльпаны — что может быть прелестней этих нежных, трогательных бутонов, укутанных изумрудной зеленью пышных листочков!,9',
            'photo'         => 'a:3:{i:0;s:14:"2a0e0126de.jpg";i:1;s:14:"c3f9c149a3.jpg";i:2;s:14:"fdc8d05e6a.png";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 13:33:06',
            'name'          => array(
                'en' => 'Tulips',
                'de' => 'Tulips',
                'ru' => 'Тюльпаны',
            ),
            'description' => array(
                'en' => 'The brightly coloured bulb of the tulip and its elegant, long green stem with velveteen leaves make it one of the most recognizable flowers in the world. Our tulip bouquets are so fresh and crisp you\'ll think we\'ve captured spring itself and delivered it to your door. The bright, pastel colors bring a big dose of sunshine into any room.',
                'de' => 'The brightly coloured bulb of the tulip and its elegant, long green stem with velveteen leaves make it one of the most recognizable flowers in the world. Our tulip bouquets are so fresh and crisp you\'ll think we\'ve captured spring itself and delivered it to your door. The bright, pastel colors bring a big dose of sunshine into any room.',
                'ru' => 'Розовые тюльпаны — что может быть прелестней этих нежных, трогательных бутонов, укутанных изумрудной зеленью пышных листочков!',
            ),
            'option_7' => 'a:1:{i:9;s:1:"9";}',
        ),
        array(
            'id'            => '11',
            'gid'           => 'rose_basket',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '110.0000',
            'price_reduced' => '99.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '110',
            'is_bestseller' => '1',
            'priority'      => '11',
            'search_data'   => '99,Rose basket,No other flower offers such a strong reaction as the romantic and sensual rose. Roses are the flowers that also offer the strongest symbolic message. Available in a variety of stunning colours and in a variety of artistic arrangements, our rose collection is designed to offer you a means of communicating the depth and power of your feelings.,Корзина роз,Нельзя не почувствовать тепло, исходящее от объёмного букета из прекрасных роз. Подарите его человеку, к которому вы испытываете наилучшие чувства. Сильная и яркая композиция символизирует торжество, благосостояние, а также крепость духа.',
            'photo'         => 'a:3:{i:0;s:14:"3d5a01137a.jpg";i:1;s:14:"24f74ecf79.jpg";i:2;s:14:"540784d5d1.jpg";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 13:37:29',
            'name'          => array(
                'en' => 'Rose basket',
                'de' => 'Rose basket',
                'ru' => 'Корзина роз',
            ),
            'description' => array(
                'en' => 'No other flower offers such a strong reaction as the romantic and sensual rose. Roses are the flowers that also offer the strongest symbolic message. Available in a variety of stunning colours and in a variety of artistic arrangements, our rose collection is designed to offer you a means of communicating the depth and power of your feelings.',
                'de' => 'No other flower offers such a strong reaction as the romantic and sensual rose. Roses are the flowers that also offer the strongest symbolic message. Available in a variety of stunning colours and in a variety of artistic arrangements, our rose collection is designed to offer you a means of communicating the depth and power of your feelings.',
                'ru' => 'Нельзя не почувствовать тепло, исходящее от объёмного букета из прекрасных роз. Подарите его человеку, к которому вы испытываете наилучшие чувства. Сильная и яркая композиция символизирует торжество, благосостояние, а также крепость духа.',
            ),
        ),
        array(
            'id'            => '12',
            'gid'           => 'flower_basket',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '110.0000',
            'price_reduced' => '99.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '110',
            'is_bestseller' => '1',
            'priority'      => '12',
            'search_data'   => '99,Flower basket,A basket full of beauty, joy and surprise. No matter what - or who - you\'re celebrating, our Flower Basket is filled with just the right gift. A great way to express your gratitude in a fun and thoughtful way!,Цветочная корзина,Элегантность и классика - вот два слова, которыми можно описать эту красочную корзину. Яркое и нежное цветочное полотно, созданное из ослепительных оранжевых, красных, жёлтых и белоснежных цветов. Подарите любимому человеку особое настроение, чудесные тона радости и позитива!',
            'photo'         => 'a:4:{i:0;s:14:"8837694dae.jpg";i:1;s:14:"7e25ac7af7.jpg";i:2;s:14:"1244690877.jpg";i:3;s:14:"da46a17ad4.png";}',
            'photo_count'   => '4',
            'date_created'  => '2014-12-16 13:50:11',
            'name'          => array(
                'en' => 'Flower basket',
                'de' => 'Flower basket',
                'ru' => 'Цветочная корзина',
            ),
            'description' => array(
                'en' => 'A basket full of beauty, joy and surprise. No matter what - or who - you\'re celebrating, our Flower Basket is filled with just the right gift. A great way to express your gratitude in a fun and thoughtful way!',
                'de' => 'A basket full of beauty, joy and surprise. No matter what - or who - you\'re celebrating, our Flower Basket is filled with just the right gift. A great way to express your gratitude in a fun and thoughtful way!',
                'ru' => 'Элегантность и классика - вот два слова, которыми можно описать эту красочную корзину. Яркое и нежное цветочное полотно, созданное из ослепительных оранжевых, красных, жёлтых и белоснежных цветов. Подарите любимому человеку особое настроение, чудесные тона радости и позитива!',
            ),
        ),
        array(
            'id'            => '13',
            'gid'           => 'laptop_black',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '600.0000',
            'price_reduced' => '540.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '600',
            'is_bestseller' => '0',
            'priority'      => '13',
            'search_data'   => '540,Laptop black,A Windows laptop that is built to compete with Chromebooks on features and price. It does pretty well on its own, but Microsoft sweetens the deal with free OneDrive storage and Office 365 Personal for a year. ,Ноутбук черный,Очень мощная начинка для данного ценового диапазона. Последнее поколение процессора (низкое тепловыделение). Практически все игры идут на высоких, максимальных настройках при данном разрешении экрана. Тихий, практически не слышно.,Windows 8.1,Intel Pentium G3258,Black',
            'photo'         => 'a:4:{i:0;s:14:"40b7584402.png";i:1;s:14:"afb63493c0.jpg";i:2;s:14:"8ce94361a7.jpg";i:3;s:14:"7549324249.png";}',
            'photo_count'   => '4',
            'date_created'  => '2014-12-16 14:09:13',
            'name'          => array(
                'en' => 'Laptop black',
                'de' => 'Laptop black',
                'ru' => 'Ноутбук черный',
            ),
            'description' => array(
                'en' => 'A Windows laptop that is built to compete with Chromebooks on features and price. It does pretty well on its own, but Microsoft sweetens the deal with free OneDrive storage and Office 365 Personal for a year. ',
                'de' => 'A Windows laptop that is built to compete with Chromebooks on features and price. It does pretty well on its own, but Microsoft sweetens the deal with free OneDrive storage and Office 365 Personal for a year. ',
                'ru' => 'Очень мощная начинка для данного ценового диапазона. Последнее поколение процессора (низкое тепловыделение). Практически все игры идут на высоких, максимальных настройках при данном разрешении экрана. Тихий, практически не слышно.',
            ),
            'option_2' => 'a:1:{i:8;s:1:"8";}',
            'option_4' => 'a:1:{i:3;s:1:"3";}',
            'option_6' => 'a:1:{i:5;s:1:"5";}',
        ),
        array(
            'id'            => '14',
            'gid'           => 'laptop_gray',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '1050.0000',
            'price_reduced' => '980.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '1050',
            'is_bestseller' => '0',
            'priority'      => '14',
            'search_data'   => '980,Laptop gray,This is an entry-level gaming laptop with some real muscle, showing impressive performance and solid battery life without the expense of a premium system. Plenty of features, and a nice price. ,Ноутбук серый,Lenovo IdeaPad Z510 (Core i7 4702MQ 2200 Mhz/15.6"/1920x1080/8.0Gb/1008Gb HDD+SSD Cache/DVD-RW/NVIDIA GeForce GT 740M/Wi-Fi/Bluetooth/Win 8 64),Debian,Intel Core i7,Gray',
            'photo'         => 'a:3:{i:0;s:14:"84a78ed917.png";i:1;s:14:"2ad0052ad7.jpg";i:2;s:14:"1aa85c252c.jpg";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 14:13:01',
            'name'          => array(
                'en' => 'Laptop gray',
                'de' => 'Laptop gray',
                'ru' => 'Ноутбук серый',
            ),
            'description' => array(
                'en' => 'This is an entry-level gaming laptop with some real muscle, showing impressive performance and solid battery life without the expense of a premium system. Plenty of features, and a nice price.',
                'de' => 'This is an entry-level gaming laptop with some real muscle, showing impressive performance and solid battery life without the expense of a premium system. Plenty of features, and a nice price.',
                'ru' => 'Lenovo IdeaPad Z510 (Core i7 4702MQ 2200 Mhz/15.6"/1920x1080/8.0Gb/1008Gb HDD+SSD Cache/DVD-RW/NVIDIA GeForce GT 740M/Wi-Fi/Bluetooth/Win 8 64)',
            ),
            'option_2' => 'a:1:{i:9;s:1:"9";}',
            'option_4' => 'a:1:{i:4;s:1:"4";}',
            'option_6' => 'a:1:{i:7;s:1:"7";}',
        ),
        array(
            'id'            => '15',
            'gid'           => 'tablet',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '215.0000',
            'price_reduced' => '215.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '215',
            'is_bestseller' => '1',
            'priority'      => '15',
            'search_data'   => '215,Tablet,Conceptualized in the mid-20th century and prototyped and developed in the last two decades of that century, tablet devices became popular in 2010. A tablet computer is a mobile computer with touch-screen display, circuitry and battery in a single unit. Tablets come equipped with sensors, including cameras, a microphone, an accelerometer and a touchscreen, with finger or stylus gestures substituting for the use of computer mouse and keyboard.,Планшет,Планшет, или планшетный персональный компьютер – это новый взгляд на переносные компьютеры, их возможности и удобство. Время ноутбуков постепенно уходит в прошлое. У планшета нет громоздкого корпуса, с открывающейся крышкой-монитором, как у ноутбуков. Минимальные размеры и вес делают его незаменимым для бизнеса и путешествий.,Android,Intel Core i7,Black',
            'photo'         => 'a:3:{i:0;s:14:"be63116a8b.png";i:1;s:14:"96c1756f8a.jpg";i:2;s:14:"2c1fbbf09d.jpg";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 14:40:10',
            'name'          => array(
                'en' => 'Tablet',
                'de' => 'Tablet',
                'ru' => 'Планшет',
            ),
            'description' => array(
                'en' => 'Conceptualized in the mid-20th century and prototyped and developed in the last two decades of that century, tablet devices became popular in 2010. A tablet computer is a mobile computer with touch-screen display, circuitry and battery in a single unit. Tablets come equipped with sensors, including cameras, a microphone, an accelerometer and a touchscreen, with finger or stylus gestures substituting for the use of computer mouse and keyboard.',
                'de' => 'Conceptualized in the mid-20th century and prototyped and developed in the last two decades of that century, tablet devices became popular in 2010. A tablet computer is a mobile computer with touch-screen display, circuitry and battery in a single unit. Tablets come equipped with sensors, including cameras, a microphone, an accelerometer and a touchscreen, with finger or stylus gestures substituting for the use of computer mouse and keyboard.',
                'ru' => 'Conceptualized in the mid-20th century and prototyped and developed in the last two decades of that century, tablet devices became popular in 2010. A tablet computer is a mobile computer with touch-screen display, circuitry and battery in a single unit. Tablets come equipped with sensors, including cameras, a microphone, an accelerometer and a touchscreen, with finger or stylus gestures substituting for the use of computer mouse and keyboard.',
            ),
            'option_2' => 'a:1:{i:8;s:1:"8";}',
            'option_4' => 'a:1:{i:4;s:1:"4";}',
            'option_6' => 'a:1:{i:1;s:1:"1";}',
        ),
        array(
            'id'            => '16',
            'gid'           => 'jacket',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '200.0000',
            'price_reduced' => '185.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '200',
            'is_bestseller' => '0',
            'priority'      => '16',
            'search_data'   => '185,Leather jacket,Leather scuba jacket with a vintage, suede-like feel. Its subtle allover print makes it a great choice for any person who wants to feel their best. The simple zipper lines streamline the look, while the rib-knit sleeves add a comfy touch. Truly a great, timeless addition to your wardrobe.,Кожаная куртка,Стильная куртка-косуха выполнена из гладкой кожи с трикотажными вставками на длинных рукавах. Детали: прямой крой, застежка и манжеты на молниях, перфорированная фактура, вытачки на груди, два кармана спереди, хлопковая черная подкладка в основной части и гладкая - в рукавах.,Leather,Beige,Black,Brown,XS,S,M,L,XL,XXL,XXXL',
            'photo'         => 'a:3:{i:0;s:14:"3615508240.png";i:1;s:14:"b9a5cb6c94.png";i:2;s:14:"62a7078a4a.png";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 16:18:02',
            'name'          => array(
                'en' => 'Leather jacket',
                'de' => 'Leather jacket',
                'ru' => 'Кожаная куртка',
            ),
            'description' => array(
                'en' => 'Leather scuba jacket with a vintage, suede-like feel. Its subtle allover print makes it a great choice for any person who wants to feel their best. The simple zipper lines streamline the look, while the rib-knit sleeves add a comfy touch. Truly a great, timeless addition to your wardrobe.',
                'de' => 'Leather scuba jacket with a vintage, suede-like feel. Its subtle allover print makes it a great choice for any person who wants to feel their best. The simple zipper lines streamline the look, while the rib-knit sleeves add a comfy touch. Truly a great, timeless addition to your wardrobe.',
                'ru' => 'Стильная куртка-косуха выполнена из гладкой кожи с трикотажными вставками на длинных рукавах. Детали: прямой крой, застежка и манжеты на молниях, перфорированная фактура, вытачки на груди, два кармана спереди, хлопковая черная подкладка в основной части и гладкая - в рукавах.',
            ),
            'option_1' => 'a:7:{i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";i:7;s:1:"7";}',
            'option_2' => 'a:3:{i:4;s:1:"4";i:8;s:1:"8";i:10;s:2:"10";}',
            'option_3' => 'a:1:{i:11;s:2:"11";}',
        ),
        array(
            'id'            => '17',
            'gid'           => 'shirt',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '100.0000',
            'price_reduced' => '95.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '100',
            'is_bestseller' => '1',
            'priority'      => '17',
            'search_data'   => '95,Shirt,Update your shirt collection with this subtle elegant printed design. Featuring a small collar and button down front. A wardrobe classic, it\'s been updated with black buttons for a subtly stylish twist. Machine wash. 100% Cotton.,Рубашка,Стильная клетка. Нагрудный карман, оригинальные детали. Отлично сочетается с джинсами. Рекомендации по уходу: стирать при 40°, гладить при 150°.,Cotton,Yellow,Chocolate,Beige,Green,Dark blue,Light blue,Black,Gray,White,Orange,Peach,Olive,XS,S,M,L,XL,XXL',
            'photo'         => 'a:4:{i:0;s:14:"474e145f3f.png";i:1;s:14:"1e0763c6a2.jpg";i:2;s:14:"f3b38005a9.jpg";i:3;s:14:"b7009e50a0.jpg";}',
            'photo_count'   => '4',
            'date_created'  => '2014-12-16 16:21:46',
            'name'          => array(
                'en' => 'Shirt',
                'de' => 'Shirt',
                'ru' => 'Рубашка',
            ),
            'description' => array(
                'en' => 'Update your shirt collection with this subtle elegant printed design. Featuring a small collar and button down front. A wardrobe classic, it\'s been updated with black buttons for a subtly stylish twist. Machine wash. 100% Cotton.',
                'de' => 'Update your shirt collection with this subtle elegant printed design. Featuring a small collar and button down front. A wardrobe classic, it\'s been updated with black buttons for a subtly stylish twist. Machine wash. 100% Cotton.',
                'ru' => 'Стильная клетка. Нагрудный карман, оригинальные детали. Отлично сочетается с джинсами. Рекомендации по уходу: стирать при 40°, гладить при 150°.',
            ),
            'option_1' => 'a:6:{i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";}',
            'option_2' => 'a:12:{i:1;s:1:"1";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";i:7;s:1:"7";i:8;s:1:"8";i:9;s:1:"9";i:11;s:2:"11";i:13;s:2:"13";i:15;s:2:"15";i:16;s:2:"16";}',
            'option_3' => 'a:1:{i:3;s:1:"3";}',
        ),
        array(
            'id'            => '18',
            'gid'           => 'top',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '25.0000',
            'price_reduced' => '18.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '25',
            'is_bestseller' => '0',
            'priority'      => '18',
            'search_data'   => '18,Tank top,We love the soft, light weight fabric of this tank top. Complete with a round neckline, this dazzling number is the perfect piece to pair with skinny jeans and heels for your next girls night out. We also love this simple tank paired with joggers and ankle boots.,Майка,Топ базовый выполнен из мягкого полотна. Тонкие бретели. Овальный вырез горловины. Однотонный и в тонкую полоску. Базовый полуприлегающий силуэт.,Cotton,Red,Green,Light blue,White,Orange,XS,S,M,L,XL',
            'photo'         => 'a:3:{i:0;s:14:"bb44bf4ef1.png";i:1;s:14:"0af10079a2.jpg";i:2;s:14:"dd7558b11e.png";}',
            'photo_count'   => '3',
            'date_created'  => '2014-12-16 17:16:26',
            'name'          => array(
                'en' => 'Tank top',
                'de' => 'Tank top',
                'ru' => 'Майка',
            ),
            'description' => array(
                'en' => 'We love the soft, light weight fabric of this tank top. Complete with a round neckline, this dazzling number is the perfect piece to pair with skinny jeans and heels for your next girls night out. We also love this simple tank paired with joggers and ankle boots.',
                'de' => 'We love the soft, light weight fabric of this tank top. Complete with a round neckline, this dazzling number is the perfect piece to pair with skinny jeans and heels for your next girls night out. We also love this simple tank paired with joggers and ankle boots.',
                'ru' => 'Топ базовый выполнен из мягкого полотна. Тонкие бретели. Овальный вырез горловины. Однотонный и в тонкую полоску. Базовый полуприлегающий силуэт.',
            ),
            'option_1' => 'a:5:{i:1;s:1:"1";i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";}',
            'option_2' => 'a:5:{i:2;s:1:"2";i:5;s:1:"5";i:7;s:1:"7";i:11;s:2:"11";i:13;s:2:"13";}',
            'option_3' => 'a:1:{i:3;s:1:"3";}',
        ),
        array(
            'id'            => '19',
            'gid'           => 'tshirt',
            'id_user'       => '0',
            'status'        => '1',
            'price'         => '35.0000',
            'price_reduced' => '24.0000',
            'gid_currency'  => 'USD',
            'price_sorting' => '35',
            'is_bestseller' => '1',
            'priority'      => '19',
            'search_data'   => '24,T-Shirt,Figure flattering and fab, our tee features a fitted silhouette and complimentary neckline. Its versatile and comfy look is perfect for styling up, styling down, or styling any super cool outfit.,Футболка,Футболка - это модный, стильный, удобный предмет одежды. Яркие жизнерадостные цвета поднимут настроение. Более сдержанные цвета подойдут к любому гардеробу.,Cotton,Red,Beige,Gray,White,S,M,L,XL,XXL,XXXL',
            'photo'         => 'a:4:{i:0;s:14:"293737a3f6.png";i:1;s:14:"462f5286b5.png";i:2;s:14:"8e34800f0f.png";i:3;s:14:"71f10a0f52.png";}',
            'photo_count'   => '4',
            'date_created'  => '2014-12-16 17:25:08',
            'name'          => array(
                'en' => 'T-Shirt',
                'de' => 'T-Shirt',
                'ru' => 'Футболка',
            ),
            'description' => array(
                'en' => 'Figure flattering and fab, our tee features a fitted silhouette and complimentary neckline. Its versatile and comfy look is perfect for styling up, styling down, or styling any super cool outfit.',
                'de' => 'Figure flattering and fab, our tee features a fitted silhouette and complimentary neckline. Its versatile and comfy look is perfect for styling up, styling down, or styling any super cool outfit.',
                'ru' => 'Футболка - это модный, стильный, удобный предмет одежды. Яркие жизнерадостные цвета поднимут настроение. Более сдержанные цвета подойдут к любому гардеробу.',
            ),
            'option_1' => 'a:6:{i:2;s:1:"2";i:3;s:1:"3";i:4;s:1:"4";i:5;s:1:"5";i:6;s:1:"6";i:7;s:1:"7";}',
            'option_2' => 'a:4:{i:2;s:1:"2";i:4;s:1:"4";i:9;s:1:"9";i:11;s:2:"11";}',
            'option_3' => 'a:1:{i:3;s:1:"3";}',
        ),
    ),
    'bestsellers' => array(
        array('id_category' => '4','id_product' => '2','priority' => '1'),
        array('id_category' => '2','id_product' => '5','priority' => '2'),
        array('id_category' => '2','id_product' => '6','priority' => '3'),
        array('id_category' => '2','id_product' => '7','priority' => '4'),
        array('id_category' => '2','id_product' => '8','priority' => '5'),
        array('id_category' => '3','id_product' => '9','priority' => '6'),
        array('id_category' => '3','id_product' => '10','priority' => '7'),
        array('id_category' => '3','id_product' => '11','priority' => '8'),
        array('id_category' => '3','id_product' => '12','priority' => '9'),
        array('id_category' => '1','id_product' => '15','priority' => '10'),
        array('id_category' => '5','id_product' => '17','priority' => '11'),
        array('id_category' => '5','id_product' => '19','priority' => '12'),
    ),
    'categories' => array(
        array(
            'id'                     => '1',
            'gid'                    => 'electronics',
            'id_parent'              => '0',
            'status'                 => '1',
            'product_active_count'   => '3',
            'product_inactive_count' => '0',
            'bestsellers_count'      => '1',
            'priority'               => '2',
            'options_data'           => 'a:3:{i:6;s:1:"6";i:4;s:1:"4";i:2;s:1:"2";}',
            'name'                   => array(
                'en' => 'Electronics',
                'de' => 'Electronics',
                'ru' => 'Электроника',
            ),
            'description' => array(
                'en' => 'Electronics Store is the perfect destination for anyone looking for digital cameras, headphones/earphones, MP3 players, hi-fi speaker systems, GPS devices, TVs, laptops, tablets and accessories. Browse through our large selection to find the product that best suits your needs.<br> All of our products are accompanied by the largest selection of reviews and low prices. So find that perfect gift for you or for someone closest to you.',
                'de' => 'Electronics Store is the perfect destination for anyone looking for digital cameras, headphones/earphones, MP3 players, hi-fi speaker systems, GPS devices, TVs, laptops, tablets and accessories. Browse through our large selection to find the product that best suits your needs.<br> All of our products are accompanied by the largest selection of reviews and low prices. So find that perfect gift for you or for someone closest to you.',
                'ru' => 'Добро пожаловать в раздел электроники нашего онлайн-магазина. Здесь вы найдете широкий выбор портативных компьютеров, планшетов, мобильных телефонов, телевизоров, холодильников, стиральных машин, пылесосов, фенов и другой техники.<br> Выберите идеальный подарок для себя и для любимого человека!',
            ),
        ),
        array(
            'id'                     => '2',
            'gid'                    => 'decorations',
            'id_parent'              => '0',
            'status'                 => '1',
            'product_active_count'   => '4',
            'product_inactive_count' => '0',
            'bestsellers_count'      => '4',
            'priority'               => '4',
            'options_data'           => 'a:2:{i:2;s:1:"2";i:7;s:1:"7";}',
            'name'                   => array(
                'en' => 'Home decorations',
                'de' => 'Home decorations',
                'ru' => 'Украшения для дома',
            ),
            'description' => array(
                'en' => 'By adding a few decor pieces here and there at your home, you can create a warm, welcoming look that captures your personality. It is also easy to refresh your style season to season or year to year simply by changing out a few pieces.<br> When choosing your home decorations, try to stick to a general style theme and color palette. This way, you can pick pieces of different shapes, textures, size and design while maintaining a cohesive feel.',
                'de' => 'By adding a few decor pieces here and there at your home, you can create a warm, welcoming look that captures your personality. It is also easy to refresh your style season to season or year to year simply by changing out a few pieces.<br> When choosing your home decorations, try to stick to a general style theme and color palette. This way, you can pick pieces of different shapes, textures, size and design while maintaining a cohesive feel.',
                'ru' => 'Декорирование интерьера в современном мире приобретает все большее значение. Декоративные изделия для дома бывают самыми разнообразными; проявив фантазию, украсить дом можно почти всем, чем угодно, даже простой, казалось бы, на вид бутылкой.<br> Товары, представленные в этом разделе, помогут добавить в привычный интерьер изюминку и сделать ваш дом стильным и неповторимым.',
            ),
        ),
        array(
            'id'                     => '3',
            'gid'                    => 'flowers',
            'id_parent'              => '0',
            'status'                 => '1',
            'product_active_count'   => '4',
            'product_inactive_count' => '0',
            'bestsellers_count'      => '4',
            'priority'               => '3',
            'options_data'           => 'a:2:{i:8;s:1:"8";i:7;s:1:"7";}',
            'name'                   => array(
                'en' => 'Flowers',
                'de' => 'Flowers',
                'ru' => 'Цветы',
            ),
            'description' => array(
                'en' => 'There is something about receiving the gift of flowers that can mean so much. For one, it certainly means that someone took the time to pick out an arrangement and have it delivered specifically to you.<br> Send flowers online. Order seasonal mixed bouquets, lush green plants, festive balloons, and much more, and rest assured that your gift will be hand-arranged and delivered with love.<br> All flowers arrive with a complimentary card so that you can easily personalize your message.',
                'de' => 'There is something about receiving the gift of flowers that can mean so much. For one, it certainly means that someone took the time to pick out an arrangement and have it delivered specifically to you.<br> Send flowers online. Order seasonal mixed bouquets, lush green plants, festive balloons, and much more, and rest assured that your gift will be hand-arranged and delivered with love.<br> All flowers arrive with a complimentary card so that you can easily personalize your message.',
                'ru' => 'Мы сотрудничаем с международной сетью доставки цветов.<br> К вашим услугам ведущие флористы мировых столиц, огромный выбор свежесрезанных цветов и готовых букетов, а также безграничные возможности для исполнения любых цветочных пожеланий.<br> Доставьте радость любимым людям!',
            ),
        ),
        array(
            'id'                     => '4',
            'gid'                    => 'sweets',
            'id_parent'              => '0',
            'status'                 => '1',
            'product_active_count'   => '4',
            'product_inactive_count' => '0',
            'bestsellers_count'      => '1',
            'priority'               => '5',
            'options_data'           => 'a:2:{i:8;s:1:"8";i:5;s:1:"5";}',
            'name'                   => array(
                'en' => 'Sweet gifts',
                'de' => 'Sweet gifts',
                'ru' => 'Сладости',
            ),
            'description' => array(
                'en' => 'Send sweet gift baskets to friends, family and loved ones. The wide variety of sweets will satisfy anyone\'s sweet tooth whenever a craving strikes.<br> We love nothing better than preparing and shipping out your favourite sweets, knowing that they are going to make someone\'s day. We hope that you find something that will let you impress the person you fancy.',
                'de' => 'Send sweet gift baskets to friends, family and loved ones. The wide variety of sweets will satisfy anyone\'s sweet tooth whenever a craving strikes.<br> We love nothing better than preparing and shipping out your favourite sweets, knowing that they are going to make someone\'s day. We hope that you find something that will let you impress the person you fancy.',
                'ru' => 'Здесь вы сможете подобрать оригинальные сладкие подарки для родных и близких.<br> Порадуйте себя или любимого человека, которого встретили на этом сайте. Закажите подарок-сюрприз, состоящий из шоколадных и карамельных конфет, суфле и мармелада, а также из некоторых секретных компонентов.<br> При желании вы можете заказать упаковку для самостоятельного формирования подарков своим кондитерским наполнением и игровыми наборами.',
            ),
        ),
        array(
            'id'                     => '5',
            'gid'                    => 'clothing',
            'id_parent'              => '0',
            'status'                 => '1',
            'product_active_count'   => '4',
            'product_inactive_count' => '0',
            'bestsellers_count'      => '2',
            'priority'               => '1',
            'options_data'           => 'a:3:{i:3;s:1:"3";i:2;s:1:"2";i:1;s:1:"1";}',
            'name'                   => array(
                'en' => 'Clothes',
                'de' => 'Clothes',
                'ru' => 'Одежда',
            ),
            'description' => array(
                'en' => 'Quality clothing at the right price. The hottest fashion and trends delivered to your doorstep.<br> From dresses and jeans to boots, casual shoes, accessories and more, find your head-to-toe style from the most-wanted international brands, online.',
                'de' => 'Quality clothing at the right price. The hottest fashion and trends delivered to your doorstep.<br> From dresses and jeans to boots, casual shoes, accessories and more, find your head-to-toe style from the most-wanted international brands, online.',
                'ru' => 'Модно и стильно одеваться любят все, но ходить по магазинам нравится далеко не каждому. Купите одежду в нашем интернет-магазине и не тратьте время на передвижение по городу и покупки впопыхах.<br> В нашем онлайн-магазине шопинг превращается в удовольствие: вы удобно устраиваетесь перед монитором и начинаете свое путешествие.<br> Разнообразный, постоянно обновляемый ассортимент, широкий выбор, доступные цены, регулярные распродажи, привлекательные скидки – лишь немногие преимущества, которые мы предоставляем своим клиентам.',
            ),
        ),
    ),
    'options' => array(
        array(
            'id'   => '1',
            'type' => 'multi',
            'name' => array(
                'en' => 'Size',
                'de' => 'Size',
                'ru' => 'Размер',
            ),
            'description' => array(
                'en' => '1. Get a flexible measuring tape. These are often sold in craft stores.<br> 2. Neck: Measure around the base of the neck in inches. Round up to the nearest half inch.<br> 3. Chest: Wrap tape measure under armpits around fullest part of the chest/bust.<br> 4. Waist: Wrap tape measure around where you normally wear your pants. Keep tape measure a little loose by keeping a finger between the tape measure and your waist.<br> 5. Hips: Stand with legs about 6 inches (15.2 cm) apart and measure around the fullest part of your hips.<br> 6. Inseam: Put on a pair of shoes. Have someone measure from your crotch to back of the heel, where you want your pants to end.',
                'de' => '1. Get a flexible measuring tape. These are often sold in craft stores.<br> 2. Neck: Measure around the base of the neck in inches. Round up to the nearest half inch.<br> 3. Chest: Wrap tape measure under armpits around fullest part of the chest/bust.<br> 4. Waist: Wrap tape measure around where you normally wear your pants. Keep tape measure a little loose by keeping a finger between the tape measure and your waist.<br> 5. Hips: Stand with legs about 6 inches (15.2 cm) apart and measure around the fullest part of your hips.<br> 6. Inseam: Put on a pair of shoes. Have someone measure from your crotch to back of the heel, where you want your pants to end.',
                'ru' => 'Как снять мерки<br> Рост: снимите обувь и прислонитесь к ровной вертикальной поверхности. Рост измеряется от макушки до ступней.<br> Обхват груди: измеряется по наиболее выступающим точкам груди.<br> Обхват под грудью: измеряется под грудью.<br>Обхват талии: измеряется вокруг талии, держитесь при этом естественно и свободно.<br> Обхват бедер: измеряется по наиболее выступающим точкам бедер и ягодиц.<br> Боковая длина брюк: лучше всего снять эту мерку с брюк, которые на вас очень хорошо сидят. Измеряйте без учета пояса до нижнего края брюк. Иначе можно замерить на теле, начиная от косточки бедра до ступней.<br> Длина стопы: встаньте обеими ногами на лист бумаги и очертите контуры стопы. Измерьте расстояние в сантиметрах. Если длина стопы на одной ноге отличается от другой, ориентируйтесь на больший показатель.<br> Измерения производите в нижнем белье и так, чтобы сантиметр плотно прилегал к телу. Если вы воспользуетесь при снятии мерок чьей-нибудь помощью, замеры будут точнее.',
            ),
        ),
        array(
            'id'   => '2',
            'type' => 'multi',
            'name' => array(
                'en' => 'Colour',
                'de' => 'Colour',
                'ru' => 'Цвет',
            ),
            'description' => array(
                'en' => 'The actual product colours may slightly vary from the colours shown in the image.',
                'de' => 'The actual product colours may slightly vary from the colours shown in the image.',
                'ru' => 'Цвет товара может незначительно отличаться от цвета на изображении.',
            ),
        ),
        array(
            'id'   => '3',
            'type' => 'multi',
            'name' => array(
                'en' => 'Fabric',
                'de' => 'Fabric',
                'ru' => 'Ткань',
            ),
            'description' => array(
                'en' => '',
                'de' => '',
                'ru' => '',
            ),
        ),
        array(
            'id'   => '4',
            'type' => 'one',
            'name' => array(
                'en' => 'Processor',
                'de' => 'Processor',
                'ru' => 'Процессор',
            ),
            'description' => array(
                'en' => 'The internal arrangement of a microprocessor varies depending on the age of the design and the intended purposes of the microprocessor. The complexity of an integrated circuit is bounded by physical limitations of the number of transistors that can be put onto one chip, the number of package terminations that can connect the processor to other parts of the system, the number of interconnections it is possible to make on the chip, and the heat that the chip can dissipate. Advancing technology makes more complex and powerful chips feasible to manufacture.',
                'de' => 'The internal arrangement of a microprocessor varies depending on the age of the design and the intended purposes of the microprocessor. The complexity of an integrated circuit is bounded by physical limitations of the number of transistors that can be put onto one chip, the number of package terminations that can connect the processor to other parts of the system, the number of interconnections it is possible to make on the chip, and the heat that the chip can dissipate. Advancing technology makes more complex and powerful chips feasible to manufacture.',
                'ru' => 'Долгое время центральные процессоры создавались из отдельных микросхем малой и средней интеграции, содержащих от нескольких единиц до нескольких сотен транзисторов. Разместив целый процессор на одном чипе сверxбольшой интеграции, удалось значительно снизить его стоимость. В настоящее время один или несколько микропроцессоров используются в качестве вычислительного элемента во всём, от мельчайших встраиваемых систем и мобильных устройств до огромных мейнфреймов и суперкомпьютеров.',
            ),
        ),
        array(
            'id'   => '5',
            'type' => 'multi',
            'name' => array(
                'en' => 'Weight',
                'de' => 'Weight',
                'ru' => 'Вес',
            ),
            'description' => array(
                'en' => '',
                'de' => '',
                'ru' => '',
            ),
        ),
        array(
            'id'   => '6',
            'type' => 'one',
            'name' => array(
                'en' => 'OS',
                'de' => 'OS',
                'ru' => 'ОС',
            ),
            'description' => array(
                'en' => 'The operating system (OS) is the most important program that runs on a computer or a device. Operating systems perform basic tasks, such as recognizing input from the keyboard, sending output to the display screen, keeping track of files and directories on the disk, and controlling peripheral devices such as disk drives and printers.',
                'de' => 'The operating system (OS) is the most important program that runs on a computer or a device. Operating systems perform basic tasks, such as recognizing input from the keyboard, sending output to the display screen, keeping track of files and directories on the disk, and controlling peripheral devices such as disk drives and printers.',
                'ru' => 'Операционная система (ОС) - базовый комплекс компьютерных программ, обеспечивающий интерфейс с пользователем, управление аппаратными средствами компьютера, работу с файлами, ввод и вывод данных, а также выполнение прикладных программ и утилит.',
            ),
        ),
        array(
            'id'   => '7',
            'type' => 'multi',
            'name' => array(
                'en' => 'Quantity',
                'de' => 'Quantity',
                'ru' => 'Количество',
            ),
            'description' => array(
                'en' => 'Number of pieces in one pack. The items are sold by packs.',
                'de' => 'Number of pieces in one pack. The items are sold by packs.',
                'ru' => 'Количество штук в одной упаковке. Товар продается упаковками.',
            ),
        ),
        array(
            'id'   => '8',
            'type' => 'multi',
            'name' => array(
                'en' => 'Packing material',
                'de' => 'Packing material',
                'ru' => 'Материал упаковки',
            ),
            'description' => array(
                'en' => '',
                'de' => '',
                'ru' => '',
            ),
        ),
    ),
    'products_categories' => array(
        array('id_category' => '4','id_product' => '1'),
        array('id_category' => '4','id_product' => '2'),
        array('id_category' => '4','id_product' => '3'),
        array('id_category' => '4','id_product' => '4'),
        array('id_category' => '2','id_product' => '5'),
        array('id_category' => '2','id_product' => '6'),
        array('id_category' => '2','id_product' => '7'),
        array('id_category' => '2','id_product' => '8'),
        array('id_category' => '3','id_product' => '9'),
        array('id_category' => '3','id_product' => '10'),
        array('id_category' => '3','id_product' => '11'),
        array('id_category' => '3','id_product' => '12'),
        array('id_category' => '1','id_product' => '13'),
        array('id_category' => '1','id_product' => '14'),
        array('id_category' => '1','id_product' => '15'),
        array('id_category' => '5','id_product' => '16'),
        array('id_category' => '5','id_product' => '17'),
        array('id_category' => '5','id_product' => '18'),
        array('id_category' => '5','id_product' => '19'),
    ),
    'shippings' => array(
        array(
            'id'           => '1',
            'price'        => '7.9900',
            'gid_currency' => 'USD',
            'status'       => '1',
            'name'         => array(
                'en' => 'Shipping to Europe',
                'de' => 'Shipping to Europe',
                'ru' => 'Доставка в страны Западной Европы',
            ),
            'description' => array(
                'en' => 'This rate applies to Austria, Bulgaria, Cyprus, Czech Republic, Denmark, Finland, France, Germany, Greece, Ireland, Italy, Spain, Poland, Portugal, and UK.',
                'de' => 'This rate applies to Austria, Bulgaria, Cyprus, Czech Republic, Denmark, Finland, France, Germany, Greece, Ireland, Italy, Spain, Poland, Portugal, and UK.',
                'ru' => 'Тариф действует для следующих стран: Австрия, Болгария, Великобритания, Германия, Греция, Дания, Ирландия, Испания, Италия, Кипр, Польша, Португалия, Финляндия, Франция и Чехия.',
            ),
        ),
        array(
            'id'           => '2',
            'price'        => '5.9900',
            'gid_currency' => 'USD',
            'status'       => '1',
            'name'         => array(
                'en' => 'Shipping to the US',
                'de' => 'Shipping to the US',
                'ru' => 'Доставка в США',
            ),
            'description' => array(
                'en' => 'We ship to the continental U.S., Alaska, and Hawaii.<br> We do not ship to U.S. Territories: Puerto Rico, U.S. Virgin Islands, Guam, Saipan, Midway Islands, American Samoa, and Federated States of Micronesia.',
                'de' => 'We ship to the continental U.S., Alaska, and Hawaii.<br> We do not ship to U.S. Territories: Puerto Rico, U.S. Virgin Islands, Guam, Saipan, Midway Islands, American Samoa, and Federated States of Micronesia.',
                'ru' => 'Доставка осуществляется по Континентальным штатам, в Аляску и на Гавайи.<br> Временно не доставляются товары по Островным территориям: Пуэрто-Рико, Американские Виргинские острова, Гуам, Северные Марианские острова, Мидуэй, Американское Самоа, Федеративные Штаты Микронезии.',
            ),
        ),
    ),
    'shippings_countries' => array(
        array(
            'id_shippings' => '1',
            'locations'    => array(
                array('id_country' => 'GB','id_region' => '0','id_city' => '0'),
                array('id_country' => 'FR','id_region' => '0','id_city' => '0'),
                array('id_country' => 'DE','id_region' => '0','id_city' => '0'),
                array('id_country' => 'ES','id_region' => '0','id_city' => '0'),
            ),
        ),
        array(
            'id_shippings' => '2',
            'locations'    => array(
                array('id_country' => 'US','id_region' => '0','id_city' => '0'),
            ),
        ),

    ),

);
