<?php

return array(
    'albums' => array(
        array(
            'id'                => 1,
            'id_album_type'     => 1,
            'id_user'           => 0,
            'date_add'          => '2016-07-01 16:46:01',
            'name'              => 'Portrait',
            'description'       => 'People portraits',
            'permissions'       => 4,
            'media_count'       => 34,
            'media_count_guest' => 34,
            'media_count_user'  => 34,
            'langs'             => array(
                'en' => 'Portrait',
                'ru' => 'Портрет',
            ),
        ),
        array(
            'id'                => 2,
            'id_album_type'     => 1,
            'id_user'           => 0,
            'date_add'          => '2016-07-01 16:46:46',
            'name'              => 'Animals',
            'description'       => 'Your pets and other animals',
            'permissions'       => 4,
            'media_count'       => 0,
            'media_count_guest' => 0,
            'media_count_user'  => 0,
            'langs'             => array(
                'en' => 'Animals',
                'ru' => 'Животные',
            ),
        ),
        array(
            'id'                => 3,
            'id_album_type'     => 1,
            'id_user'           => 0,
            'date_add'          => '2016-07-01 16:49:42',
            'name'              => 'Travel',
            'description'       => 'Places you\'ve been to and would like to visit',
            'permissions'       => 4,
            'media_count'       => 2,
            'media_count_guest' => 2,
            'media_count_user'  => 2,
            'langs'             => array(
                'en' => 'Travel',
                'ru' => 'Путешествие',
            ),
        ),
        array(
            'id'                => 4,
            'id_album_type'     => 1,
            'id_user'           => 9,
            'date_add'          => '2016-07-01 16:56:02',
            'name'              => 'Winter',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 1,
            'media_count_guest' => 1,
            'media_count_user'  => 1,
            'langs'             => array(
                'en' => 'Winter',
                'ru' => 'Winter',
            ),
        ),
        array(
            'id'                => 5,
            'id_album_type'     => 1,
            'id_user'           => 1,
            'date_add'          => '2016-07-01 17:01:16',
            'name'              => 'Flowers',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 0,
            'media_count_guest' => 0,
            'media_count_user'  => 0,
            'langs'             => array(
                'en' => 'Flowers',
                'ru' => 'Flowers',
            ),
        ),
        array(
            'id'                => 6,
            'id_album_type'     => 1,
            'id_user'           => 15,
            'date_add'          => '2016-07-01 17:27:25',
            'name'              => 'makeup',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 4,
            'media_count_guest' => 4,
            'media_count_user'  => 4,
            'langs'             => array(
                'en' => 'makeup',
                'ru' => 'makeup',
            ),
        ),
        array(
            'id'                => 7,
            'id_album_type'     => 1,
            'id_user'           => 10,
            'date_add'          => '2016-07-01 17:29:27',
            'name'              => 'favorite cars',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 1,
            'media_count_guest' => 1,
            'media_count_user'  => 1,
            'langs'             => array(
                'en' => 'favorite cars',
                'ru' => 'favorite cars',
            ),
        ),
        array(
            'id'                => 8,
            'id_album_type'     => 1,
            'id_user'           => 8,
            'date_add'          => '2016-07-01 17:33:52',
            'name'              => 'the suit :)',
            'description'       => '',
            'permissions'       => 2,
            'media_count'       => 1,
            'media_count_guest' => 1,
            'media_count_user'  => 1,
            'langs'             => array(
                'en' => 'the suit :)',
                'ru' => 'the suit :)',
            ),
        ),
        array(
            'id'                => 9,
            'id_album_type'     => 1,
            'id_user'           => 3,
            'date_add'          => '2016-07-01 17:48:33',
            'name'              => 'leather jackets',
            'description'       => '',
            'permissions'       => 1,
            'media_count'       => 1,
            'media_count_guest' => 1,
            'media_count_user'  => 1,
            'langs'             => array(
                'en' => 'leather jackets',
                'ru' => 'leather jackets',
            ),
        ),
        array(
            'id'                => 10,
            'id_album_type'     => 1,
            'id_user'           => 16,
            'date_add'          => '2016-07-01 17:50:56',
            'name'              => 'sunglasses',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 1,
            'media_count_guest' => 1,
            'media_count_user'  => 1,
            'langs'             => array(
                'en' => 'sunglasses',
                'ru' => 'sunglasses',
            ),
        ),
        array(
            'id'                => 11,
            'id_album_type'     => 1,
            'id_user'           => 11,
            'date_add'          => '2016-07-01 18:09:57',
            'name'              => 'in the morning',
            'description'       => '',
            'permissions'       => 3,
            'media_count'       => 4,
            'media_count_guest' => 4,
            'media_count_user'  => 4,
            'langs'             => array(
                'en' => 'in the morning',
                'ru' => 'in the morning',
            ),
        ),
        array(
            'id'                => 12,
            'id_album_type'     => 1,
            'id_user'           => 2,
            'date_add'          => '2016-07-01 18:11:16',
            'name'              => 'yellow',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 2,
            'media_count_guest' => 2,
            'media_count_user'  => 2,
            'langs'             => array(
                'en' => 'yellow',
                'ru' => 'yellow',
            ),
        ),
        array(
            'id'                => 13,
            'id_album_type'     => 1,
            'id_user'           => 7,
            'date_add'          => '2016-07-01 18:13:41',
            'name'              => 'party',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 1,
            'media_count_guest' => 1,
            'media_count_user'  => 1,
            'langs'             => array(
                'en' => 'party',
                'ru' => 'party',
            ),
        ),
        array(
            'id'                => 14,
            'id_album_type'     => 1,
            'id_user'           => 4,
            'date_add'          => '2016-07-01 18:15:35',
            'name'              => 'hair',
            'description'       => '',
            'permissions'       => 3,
            'media_count'       => 2,
            'media_count_guest' => 2,
            'media_count_user'  => 2,
            'langs'             => array(
                'en' => 'hair',
                'ru' => 'hair',
            ),
        ),
        array(
            'id'                => 15,
            'id_album_type'     => 1,
            'id_user'           => 14,
            'date_add'          => '2016-07-01 18:16:43',
            'name'              => 'flowers',
            'description'       => '',
            'permissions'       => 4,
            'media_count'       => 2,
            'media_count_guest' => 2,
            'media_count_user'  => 2,
            'langs'             => array(
                'en' => 'flowers',
                'ru' => 'flowers',
            ),
        ),
    ),
);
