<?php
return array(
    'users' => array(
        array(
            'date_created' => '2016-03-24 17:41:04',
            'date_modified' => '2016-05-04 15:53:23',
            'email' => 'ivan@mail.com',
            'nickname' => 'ivan22',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Ivan',
            'sname' => 'Fateev',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => 'b118217a1a.png',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 110,
            'id_country' => 'US',
            'id_region' => 5,
            'id_city' => 5,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1988-01-20',
            'age' => 30,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 4,
            'search_field' => 'Ivan; Fateev; ivan22; 1988-01-20; United States, New York City Weight 71kg - 80kg (157-177lbs); Height 181cm-190cm(6ft-6,3ft); Body type Athletic; Hair Blond; Style Business, Classic, Sport; Seaside walk; At 5 years old, ask me why); Interests Cinema, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:53:23',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:53:32',
            'lat' => 40.7142700,
            'lon' => -74.0059700,
            'fe_weight' => 5,
            'fe_height' => 5,
            'fe_body' => 1,
            'fe_hair' => 4,
            'fe_style' => 262,
            'fe_ideal_date' => 'Seaside walk',
            'fe_best_bd' => 'At 5 years old, ask me why)',
            'fe_interests' => 130,
        ),
        array(
            'date_created' => '2016-03-24 17:42:36',
            'date_modified' => '2016-05-04 15:54:34',
            'email' => 'kelly@mail.com',
            'nickname' => 'kelly',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Kelly',
            'sname' => 'Shelley',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '9c3dc42100.png',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 110,
            'id_country' => 'US',
            'id_region' => 5,
            'id_city' => 5,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1991-10-30',
            'age' => 27,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 7,
            'search_field' => 'Kelly; Shelley; kelly; 1991-10-30; United States, New York City Weight 51kg - 60kg (113-133lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Chestnut; Style Business, Classic, Fashion; That would probably be a walk along the seashore; My parents took me to Disneyland when I was a kid. It was amazing!; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:54:34',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:54:37',
            'lat' => 40.7142700,
            'lon' => -74.0059700,
            'fe_weight' => 3,
            'fe_height' => 3,
            'fe_body' => 2,
            'fe_hair' => 5,
            'fe_style' => 14,
            'fe_ideal_date' => 'That would probably be a walk along the seashore',
            'fe_best_bd' => 'My parents took me to Disneyland when I was a kid. It was amazing!',
            'fe_interests' => 254,
        ),
        array(
            'date_created' => '2016-03-24 17:44:08',
            'date_modified' => '2016-05-04 15:54:57',
            'email' => 'fred@mail.com',
            'nickname' => 'Freddie',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Fred',
            'sname' => 'Smith',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '968c111e5e.png',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 120,
            'id_country' => 'GB',
            'id_region' => 4,
            'id_city' => 4,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1990-04-18',
            'age' => 28,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 1,
            'search_field' => 'Fred; Smith; Freddie; 1990-04-18; United Kingdom, London Weight 81kg - 90kg (180-200lbs); Height 191cm-200cm(6,3ft-6,7ft); Body type Athletic; Hair Black; Style Free, Sport; Jogging in the park then BBQ; It\'s getting better every year; Interests Cinema, Music, Cooking, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:54:57',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:55:01',
            'lat' => 51.5085300,
            'lon' => -0.1257400,
            'fe_weight' => 6,
            'fe_height' => 6,
            'fe_body' => 1,
            'fe_hair' => 3,
            'fe_style' => 400,
            'fe_ideal_date' => 'Jogging in the park then BBQ',
            'fe_best_bd' => 'It\'s getting better every year',
            'fe_interests' => 142,
        ),
        array(
            'date_created' => '2016-03-25 17:24:23',
            'date_modified' => '2016-05-04 15:55:19',
            'email' => 'maria@mail.com',
            'nickname' => 'Maria',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Maria',
            'sname' => 'Santos',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '917fa00264.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 130,
            'id_country' => 'US',
            'id_region' => 5,
            'id_city' => 5,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1991-01-06',
            'age' => 27,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 2,
            'search_field' => 'Maria; Santos; Maria; 1991-01-06; United States, New York City Weight 40kg - 50kg (89-111lbs); Height 151cm-160cm(5ft-5,3ft); Body type Normal; Hair Black; Style Fashion, Grunge; Any date with the person I love; Hopefully it is yet to come )); Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:55:19',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:55:22',
            'lat' => 40.7142700,
            'lon' => -74.0059700,
            'fe_weight' => 2,
            'fe_height' => 2,
            'fe_body' => 2,
            'fe_hair' => 3,
            'fe_style' => 40,
            'fe_ideal_date' => 'Any date with the person I love',
            'fe_best_bd' => 'Hopefully it is yet to come ))',
            'fe_interests' => 254,
        ),
        array(
            'date_created' => '2016-03-25 17:30:22',
            'date_modified' => '2016-03-29 16:46:59',
            'email' => 'thomas@mail.com',
            'nickname' => 'ThomasM',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Thomas',
            'sname' => 'Monaghan',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '148e5f96e9.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 90,
            'id_country' => 'DE',
            'id_region' => 2,
            'id_city' => 2,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1993-02-16',
            'age' => 25,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 1,
            'search_field' => 'Thomas; Monaghan; ThomasM; 1993-02-16; Germany, Berlin Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Normal; Hair Chestnut; Style Business, Classic; rope jumping :); I don\'t like my birthdays much; Interests Cinema, Music, Cooking;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '0000-00-00 00:00:00',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-01 18:18:03',
            'fe_weight' => 5,
            'fe_height' => 4,
            'fe_body' => 2,
            'fe_hair' => 5,
            'fe_style' => 6,
            'fe_ideal_date' => 'rope jumping :)',
            'fe_best_bd' => 'I don\'t like my birthdays much',
            'fe_interests' => 14,
        ),
        array(
            'date_created' => '2016-03-25 17:36:31',
            'date_modified' => '2016-05-04 15:55:42',
            'email' => 'christine@mail.com',
            'nickname' => 'Christine',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Christine',
            'sname' => 'Fleur',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => 'b53a3c56aa.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 160,
            'id_country' => 'FR',
            'id_region' => 1,
            'id_city' => 1,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1994-03-09',
            'age' => 24,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 1,
            'search_field' => 'Christine; Fleur; Christine; 1994-03-09; France, Paris Weight 40kg - 50kg (89-111lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Thin; Hair Blond; Style Fashion; I like the old-fashioned way, flowers, dinner - romantic evening; When I got a pet!; Interests Music, Cooking, Painting, Shopping;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:55:42',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:55:49',
            'lat' => 48.8666670,
            'lon' => 2.3333330,
            'fe_weight' => 2,
            'fe_height' => 3,
            'fe_body' => 6,
            'fe_hair' => 4,
            'fe_style' => 8,
            'fe_ideal_date' => 'I like the old-fashioned way, flowers, dinner - romantic evening',
            'fe_best_bd' => 'When I got a pet!',
            'fe_interests' => 60,
        ),
        array(
            'date_created' => '2016-03-25 17:43:36',
            'date_modified' => '2016-05-04 15:56:05',
            'email' => 'marcia@mail.com',
            'nickname' => 'Marcia',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Marcia',
            'sname' => 'Courtney',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => 'd8a6f4a7e3.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 150,
            'id_country' => 'US',
            'id_region' => 5,
            'id_city' => 5,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1993-04-30',
            'age' => 25,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 2,
            'search_field' => 'Marcia; Courtney; Marcia; 1993-04-30; United States, New York City Weight 40kg - 50kg (89-111lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Black; Style Business, Classic, Fashion, Free, Grunge, Sport; do something together; away from home; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:56:05',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:56:12',
            'lat' => 40.7142700,
            'lon' => -74.0059700,
            'fe_weight' => 2,
            'fe_height' => 3,
            'fe_body' => 2,
            'fe_hair' => 3,
            'fe_style' => 318,
            'fe_ideal_date' => 'do something together',
            'fe_best_bd' => 'away from home',
            'fe_interests' => 254,
        ),
        array(
            'date_created' => '2016-03-25 17:47:17',
            'date_modified' => '2016-05-04 15:56:31',
            'email' => 'clark22@mail.com',
            'nickname' => 'Clark',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Clark',
            'sname' => 'Gibbs',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '42baa183d7.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 180,
            'id_country' => 'GB',
            'id_region' => 4,
            'id_city' => 4,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1990-05-15',
            'age' => 28,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 3,
            'search_field' => 'Clark; Gibbs; Clark; 1990-05-15; United Kingdom, London Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Athletic; Hair Black; Style Free, Sport; I like outdoor activities, so I\'d like to spend the time with my date outdoors; yet to come; Interests Cinema, Music, Cooking, Shopping, TV, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:56:31',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:56:37',
            'lat' => 51.5085300,
            'lon' => -0.1257400,
            'fe_weight' => 5,
            'fe_height' => 4,
            'fe_body' => 1,
            'fe_hair' => 3,
            'fe_style' => 272,
            'fe_ideal_date' => 'I like outdoor activities, so I\'d like to spend the time with my date outdoors',
            'fe_best_bd' => 'yet to come',
            'fe_interests' => 238,
        ),
        array(
            'date_created' => '2016-03-25 17:53:29',
            'date_modified' => '2016-05-04 15:56:52',
            'email' => 'lucy@mail.com',
            'nickname' => 'Lucille',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Lucy',
            'sname' => 'Atwood',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '3350bc8ad3.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 60,
            'id_country' => 'DE',
            'id_region' => 2,
            'id_city' => 2,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1994-06-24',
            'age' => 24,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 2,
            'search_field' => 'Lucy; Atwood; Lucille; 1994-06-24; Germany, Berlin Weight 51kg - 60kg (113-133lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Blond; Style Classic, Fashion; Definitely involving nice dinner; Two years ago when I was in India, such an amazing country!; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:56:52',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:57:04',
            'lat' => 52.5166667,
            'lon' => 13.4000000,
            'fe_weight' => 3,
            'fe_height' => 3,
            'fe_body' => 2,
            'fe_hair' => 4,
            'fe_style' => 12,
            'fe_ideal_date' => 'Definitely involving nice dinner',
            'fe_best_bd' => 'Two years ago when I was in India, such an amazing country!',
            'fe_interests' => 254,
        ),
        array(
            'date_created' => '2016-03-25 17:59:34',
            'date_modified' => '2016-05-04 15:57:23',
            'email' => 'chrisj@mail.com',
            'nickname' => 'Chris',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Chris',
            'sname' => 'Johnson',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => 'a36d631339.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 140,
            'id_country' => 'US',
            'id_region' => 5,
            'id_city' => 5,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1993-06-12',
            'age' => 25,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 2,
            'search_field' => 'Chris; Johnson; Chris; 1993-06-12; United States, New York City Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Normal; Hair Black; Style Business, Classic, Fashion, Free, Grunge, Sport; Take a ride somewhere; Every day is good enough, birthday is nothing really special; Interests Music;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '2016-06-04 15:57:23',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 1,
            'site_status' => 0,
            'date_last_activity' => '2016-05-04 15:57:24',
            'lat' => 40.7142700,
            'lon' => -74.0059700,
            'fe_weight' => 5,
            'fe_height' => 4,
            'fe_body' => 2,
            'fe_hair' => 3,
            'fe_style' => 318,
            'fe_ideal_date' => 'Take a ride somewhere',
            'fe_best_bd' => 'Every day is good enough, birthday is nothing really special',
            'fe_interests' => 4,
        ),
        array(
            'date_created' => '2016-03-25 18:04:40',
            'date_modified' => '2016-05-01 16:58:15',
            'email' => 'kathy@mail.com',
            'nickname' => 'Kathy',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Kathy',
            'sname' => 'Ryan',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '279732c33a.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 105,
            'id_country' => 'ES',
            'id_region' => 3,
            'id_city' => 3,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1994-07-07',
            'age' => 24,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 3,
            'search_field' => 'Kathy; Ryan; Kathy; 1994-07-07; Spain, Madrid Weight 61kg - 70kg (135-155lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Black; Style Classic, Fashion; Going to theatre, then dinner; Oh, all my birthdays have been great so far; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '0000-00-00 00:00:00',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-01 18:10:39',
            'lat' => 40.4165000,
            'lon' => -3.7025600,
            'fe_weight' => 4,
            'fe_height' => 3,
            'fe_body' => 2,
            'fe_hair' => 3,
            'fe_style' => 12,
            'fe_ideal_date' => 'Going to theatre, then dinner',
            'fe_best_bd' => 'Oh, all my birthdays have been great so far',
            'fe_interests' => 254,
        ),
        array(
            'date_created' => '2016-03-25 18:12:27',
            'date_modified' => '2016-05-01 16:58:14',
            'email' => 'jonathan@mail.com',
            'nickname' => 'Jonathan',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Jonathan',
            'sname' => 'Davies',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '368c8a7460.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 177,
            'id_country' => 'GB',
            'id_region' => 4,
            'id_city' => 4,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1987-08-24',
            'age' => 31,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 3,
            'search_field' => 'Jonathan; Davies; Jonathan; 1987-08-24; United Kingdom, London Weight 71kg - 80kg (157-177lbs); Height 181cm-190cm(6ft-6,3ft); Body type Normal; Hair Chestnut; Style Business, Classic; Bar crawl would be ideal.; Last year, I can tell you why, just ask; Interests Painting, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '0000-00-00 00:00:00',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-01 18:09:10',
            'fe_weight' => 5,
            'fe_height' => 5,
            'fe_body' => 2,
            'fe_hair' => 5,
            'fe_style' => 6,
            'fe_ideal_date' => 'Bar crawl would be ideal.',
            'fe_best_bd' => 'Last year, I can tell you why, just ask',
            'fe_interests' => 144,
        ),
        array(
            'date_created' => '2016-03-25 18:23:09',
            'date_modified' => '2016-05-01 16:58:14',
            'email' => 'mahmoud@mail.com',
            'nickname' => 'Mahmoud',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Mahmoud',
            'sname' => 'Ahmed',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => 'cdddc53341.png',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 123,
            'id_country' => 'US',
            'id_region' => 5,
            'id_city' => 5,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1991-09-19',
            'age' => 27,
            'show_adult' => 0,
            'profile_completion' => 90,
            'views_count' => 3,
            'search_field' => 'Mahmoud; Ahmed; Mahmoud; 1991-09-19; United States, New York City Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Athletic; Hair Black; Style Business, Classic, Fashion, Free, Grunge, Sport; Interests Cinema, Music, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '0000-00-00 00:00:00',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-01 18:13:13',
            'lat' => 40.7142700,
            'lon' => -74.0059700,
            'fe_weight' => 5,
            'fe_height' => 4,
            'fe_body' => 1,
            'fe_hair' => 3,
            'fe_style' => 318,
            'fe_ideal_date' => '',
            'fe_best_bd' => '',
            'fe_interests' => 134,
        ),
        array(
            'date_created' => '2016-03-25 18:27:47',
            'date_modified' => '2016-05-01 16:58:41',
            'email' => 'nat@mail.com',
            'nickname' => 'Natalie',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Natalie',
            'sname' => 'Coldman',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => '437de18441.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 308,
            'id_country' => 'FR',
            'id_region' => 1,
            'id_city' => 1,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1994-10-15',
            'age' => 24,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 3,
            'search_field' => 'Natalie; Coldman; Natalie; 1994-10-15; France, Paris Weight 40kg - 50kg (89-111lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Thin; Hair Chestnut; Style Classic, Fashion, Free; Skiing, sailing; The next one is going to be just fine); Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '0000-00-00 00:00:00',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-01 18:17:09',
            'lat' => 48.8666670,
            'lon' => 2.3333330,
            'fe_weight' => 2,
            'fe_height' => 3,
            'fe_body' => 6,
            'fe_hair' => 5,
            'fe_style' => 28,
            'fe_ideal_date' => 'Skiing, sailing',
            'fe_best_bd' => 'The next one is going to be just fine)',
            'fe_interests' => 254,
        ),
        array(
            'date_created' => '2016-03-29 15:53:17',
            'date_modified' => '2016-05-01 17:36:03',
            'email' => 'anna@mail.com',
            'nickname' => 'Annie',
            'user_type' => 'female',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'Anna',
            'sname' => 'Crawford',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => 'c11bd5a0e1.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 67,
            'id_country' => 'DE',
            'id_region' => 2,
            'id_city' => 2,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1993-09-30',
            'age' => 25,
            'show_adult' => 0,
            'profile_completion' => 100,
            'views_count' => 5,
            'search_field' => 'Anna; Crawford; Annie; 1993-09-30; Germany, Berlin Weight 51kg - 60kg (113-133lbs); Height 171cm-180cm(5,7ft-6ft); Body type Thin; Hair Blond; Style Business, Classic, Fashion, Free, Sport; It starts with flowers); When I turned 15, my parents bought me a horse!; Interests Cinema, Music, Cooking;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '0000-00-00 00:00:00',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-01 18:25:14',
            'lat' => 52.5166667,
            'lon' => 13.4000000,
            'fe_weight' => 3,
            'fe_height' => 4,
            'fe_body' => 6,
            'fe_hair' => 4,
            'fe_style' => 286,
            'fe_ideal_date' => 'It starts with flowers)',
            'fe_best_bd' => 'When I turned 15, my parents bought me a horse!',
            'fe_interests' => 14,
        ),
        array(
            'date_created' => '2016-03-29 16:11:46',
            'date_modified' => '2016-05-01 17:30:55',
            'email' => 'will@mail.com',
            'nickname' => 'William',
            'user_type' => 'male',
            'password' => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm' => 1,
            'approved' => 1,
            'activity' => 1,
            'confirm_code' => '',
            'fname' => 'William',
            'sname' => 'Elk',
            'lang_code' => 'en',
            'user_open_id' => '',
            'user_logo' => 'ee5136d1ce.jpg',
            'user_logo_moderation' => '',
            'logo_comments_count' => 0,
            'group_id' => 1,
            'account' => 190,
            'id_country' => 'GB',
            'id_region' => 4,
            'id_city' => 4,
            'phone' => '',
            'address' => '',
            'postal_code' => '',
            'birth_date' => '1990-10-20',
            'age' => 28,
            'show_adult' => 0,
            'profile_completion' => 95,
            'views_count' => 5,
            'search_field' => 'William; Elk; William; 1990-10-20; United Kingdom, London Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Normal; Hair Black; Style Business, Classic; Some formal dinner or gala event; Interests Music, Cooking, Painting, Shopping;',
            'activated_end_date' => '0000-00-00 00:00:00',
            'featured_end_date' => '0000-00-00 00:00:00',
            'hide_on_site_end_date' => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date' => '0000-00-00 00:00:00',
            'leader_bid' => 0,
            'leader_text' => '',
            'leader_write_date' => '0000-00-00 00:00:00',
            'online_status' => 0,
            'site_status' => 0,
            'date_last_activity' => '2016-05-01 18:18:23',
            'lat' => 51.5085300,
            'lon' => -0.1257400,
            'fe_weight' => 5,
            'fe_height' => 4,
            'fe_body' => 2,
            'fe_hair' => 3,
            'fe_style' => 6,
            'fe_ideal_date' => 'Some formal dinner or gala event',
            'fe_best_bd' => '',
            'fe_interests' => 60,
        ),
    ),
    'users_views' => array(
        array(
            'id_user' => 1,
            'id_viewer' => 2,
            'view_date' => '2016-03-25',),
        array(
            'id_user' => 1,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 1,
            'id_viewer' => 2,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 1,
            'id_viewer' => 9,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 2,
            'id_viewer' => 3,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 2,
            'id_viewer' => 1,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 2,
            'id_viewer' => 1,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 2,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 2,
            'id_viewer' => 5,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 2,
            'id_viewer' => 8,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 2,
            'id_viewer' => 8,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 3,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 4,
            'id_viewer' => 1,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 4,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 5,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 6,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 7,
            'id_viewer' => 5,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 7,
            'id_viewer' => 11,
            'view_date' => '2016-03-25',),
        array(
            'id_user' => 8,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 8,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 8,
            'id_viewer' => 15,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 9,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 9,
            'id_viewer' => 16,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 10,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 10,
            'id_viewer' => 7,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 11,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 11,
            'id_viewer' => 8,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 11,
            'id_viewer' => 16,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 12,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 12,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 12,
            'id_viewer' => 7,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 13,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 13,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 13,
            'id_viewer' => 7,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 14,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 14,
            'id_viewer' => 5,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 14,
            'id_viewer' => 8,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 15,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 15,
            'id_viewer' => 3,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 15,
            'id_viewer' => 7,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 15,
            'id_viewer' => 8,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 15,
            'id_viewer' => 16,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 16,
            'id_viewer' => 1,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 16,
            'id_viewer' => 2,
            'view_date' => '2016-03-29',),
        array(
            'id_user' => 16,
            'id_viewer' => 6,
            'view_date' => '2016-05-01',),
        array(
            'id_user' => 16,
            'id_viewer' => 8,
            'view_date' => '2016-03-30',),
        array(
            'id_user' => 16,
            'id_viewer' => 15,
            'view_date' => '2016-03-29',),
    ),
    'users_viewers' => array(
        array(
            'id_user' => 1,
            'id_viewer' => 2,
            'view_date' => '2016-03-30 12:47:24',),
        array(
            'id_user' => 1,
            'id_viewer' => 9,
            'view_date' => '2016-05-01 17:08:49',),
        array(
            'id_user' => 2,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:25',),
        array(
            'id_user' => 2,
            'id_viewer' => 3,
            'view_date' => '2016-05-01 17:52:32',),
        array(
            'id_user' => 2,
            'id_viewer' => 8,
            'view_date' => '2016-05-01 18:15:31',),
        array(
            'id_user' => 2,
            'id_viewer' => 5,
            'view_date' => '2016-05-01 16:29:45',),
        array(
            'id_user' => 3,
            'id_viewer' => 2,
            'view_date' => '2016-03-29 16:47:04',),
        array(
            'id_user' => 4,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:22',),
        array(
            'id_user' => 5,
            'id_viewer' => 2,
            'view_date' => '2016-03-29 16:46:59',),
        array(
            'id_user' => 6,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:19',),
        array(
            'id_user' => 7,
            'id_viewer' => 11,
            'view_date' => '2016-03-25 18:09:02',),
        array(
            'id_user' => 7,
            'id_viewer' => 5,
            'view_date' => '2016-05-01 16:32:35',),
        array(
            'id_user' => 8,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:16',),
        array(
            'id_user' => 8,
            'id_viewer' => 2,
            'view_date' => '2016-03-29 16:46:58',),
        array(
            'id_user' => 8,
            'id_viewer' => 15,
            'view_date' => '2016-03-29 16:04:56',),
        array(
            'id_user' => 9,
            'id_viewer' => 16,
            'view_date' => '2016-03-29 16:29:05',),
        array(
            'id_user' => 9,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:17',),
        array(
            'id_user' => 10,
            'id_viewer' => 7,
            'view_date' => '2016-05-01 16:38:06',),
        array(
            'id_user' => 10,
            'id_viewer' => 2,
            'view_date' => '2016-03-29 16:46:58',),
        array(
            'id_user' => 11,
            'id_viewer' => 8,
            'view_date' => '2016-03-30 18:39:51',),
        array(
            'id_user' => 11,
            'id_viewer' => 16,
            'view_date' => '2016-03-29 16:32:18',),
        array(
            'id_user' => 11,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:15',),
        array(
            'id_user' => 12,
            'id_viewer' => 2,
            'view_date' => '2016-03-29 16:46:57',),
        array(
            'id_user' => 12,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:14',),
        array(
            'id_user' => 12,
            'id_viewer' => 7,
            'view_date' => '2016-05-01 16:38:04',),
        array(
            'id_user' => 13,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:14',),
        array(
            'id_user' => 13,
            'id_viewer' => 7,
            'view_date' => '2016-05-01 16:50:32',),
        array(
            'id_user' => 13,
            'id_viewer' => 2,
            'view_date' => '2016-03-29 16:46:56',),
        array(
            'id_user' => 14,
            'id_viewer' => 8,
            'view_date' => '2016-03-30 18:39:50',),
        array(
            'id_user' => 14,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:41',),
        array(
            'id_user' => 14,
            'id_viewer' => 5,
            'view_date' => '2016-05-01 16:32:13',),
        array(
            'id_user' => 15,
            'id_viewer' => 3,
            'view_date' => '2016-05-01 17:36:03',),
        array(
            'id_user' => 15,
            'id_viewer' => 8,
            'view_date' => '2016-03-30 18:39:49',),
        array(
            'id_user' => 15,
            'id_viewer' => 7,
            'view_date' => '2016-05-01 16:38:03',),
        array(
            'id_user' => 15,
            'id_viewer' => 16,
            'view_date' => '2016-03-29 16:31:14',),
        array(
            'id_user' => 15,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 17:10:03',),
        array(
            'id_user' => 16,
            'id_viewer' => 2,
            'view_date' => '2016-03-29 16:46:56',),
        array(
            'id_user' => 16,
            'id_viewer' => 8,
            'view_date' => '2016-03-30 18:40:42',),
        array(
            'id_user' => 16,
            'id_viewer' => 15,
            'view_date' => '2016-03-29 16:33:40',),
        array(
            'id_user' => 16,
            'id_viewer' => 1,
            'view_date' => '2016-05-01 16:58:03',),
        array(
            'id_user' => 16,
            'id_viewer' => 6,
            'view_date' => '2016-05-01 17:30:55',),
    ),
    'groups' => [
        [
            'gid' => 'default',
            'name' => [
                'en' => 'Default Group',
                'ru' => 'Группа по умолчанию',
            ],
            'description' => [
                'en' => 'The default group, starting group after registration',
                'ru' => 'Группа по умолчанию, стартовая группа после регистрации',
            ],
            'is_active' => true,
            'is_default' => true,
            'priority' => 1,
        ],
    ],
);
