<?php

return array(
    'users' => array(
        array(
        'date_created'                     => '2016-04-24 17:41:04',
            'date_modified'                => '2016-06-04 15:53:23',
            'email'                        => 'ivan@mail.com',
            'nickname'                     => 'ivan22',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Ivan',
            'sname'                        => 'Fateev',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => 'b118217a1a.png',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 110,
            'id_country'                   => 'US',
            'id_region'                    => 5,
            'id_city'                      => 5,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1988-01-20',
            'age'                          => 30,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 4,
            'search_field'                 => 'Ivan; Fateev; ivan22; 1988-01-20; United States, New York City Weight 71kg - 80kg (157-177lbs); Height 181cm-190cm(6ft-6,3ft); Body type Athletic; Hair Blond; Style Business, Classic, Sport; Seaside walk; At 5 years old, ask me why); Interests Cinema, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:53:23',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:53:32',
            'lat'                          => 40.7142700,
            'lon'                          => -74.0059700,
        'fe_iphone_android'                => 1,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 1,
        'fe_style'                         => 262,
        'fe_favourite_films'               => 'One Flew Over the Cuckoo\'s Nest',
        'fe_favourite_tv_shows'            => 'Breaking Bad, True Detective',
        'fe_favourite_music'               => 'Jamiroquai',
        'fe_favourite_books'               => 'The Catcher in the Rye',
            ),
        array(
        'date_created'                     => '2016-04-24 17:42:36',
            'date_modified'                => '2016-06-04 15:54:34',
            'email'                        => 'kelly@mail.com',
            'nickname'                     => 'kelly',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Kelly',
            'sname'                        => 'Shelley',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '9c3dc42100.png',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 110,
            'id_country'                   => 'US',
            'id_region'                    => 5,
            'id_city'                      => 5,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1991-10-30',
            'age'                          => 27,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 7,
            'search_field'                 => 'Kelly; Shelley; kelly; 1991-10-30; United States, New York City Weight 51kg - 60kg (113-133lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Chestnut; Style Business, Classic, Fashion; That would probably be a walk along the seashore; My parents took me to Disneyland when I was a kid. It was amazing!; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:54:34',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:54:37',
            'lat'                          => 40.7142700,
            'lon'                          => -74.0059700,
        'fe_iphone_android'                => 3,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 2,
        'fe_style'                         => 14,
        'fe_favourite_films'               => 'All parts of The Godfather',
        'fe_favourite_tv_shows'            => 'The Good Wife',
        'fe_favourite_music'               => 'Country music',
        'fe_favourite_books'               => 'The Divine Comedy',
            ),
        array(
        'date_created'                     => '2016-04-24 17:44:08',
            'date_modified'                => '2016-06-04 15:54:57',
            'email'                        => 'fred@mail.com',
            'nickname'                     => 'Freddie',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Fred',
            'sname'                        => 'Smith',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '968c111e5e.png',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 120,
            'id_country'                   => 'GB',
            'id_region'                    => 4,
            'id_city'                      => 4,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1990-04-18',
            'age'                          => 28,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 1,
            'search_field'                 => 'Fred; Smith; Freddie; 1990-04-18; United Kingdom, London Weight 81kg - 90kg (180-200lbs); Height 191cm-200cm(6,3ft-6,7ft); Body type Athletic; Hair Black; Style Free, Sport; Jogging in the park then BBQ; It\'s getting better every year; Interests Cinema, Music, Cooking, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:54:57',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:55:01',
            'lat'                          => 51.5085300,
            'lon'                          => -0.1257400,
        'fe_iphone_android'                => 2,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 3,
        'fe_style'                         => 400,
        'fe_favourite_films'               => 'Sunset Boulevard',
        'fe_favourite_tv_shows'            => 'Arrested Development',
        'fe_favourite_music'               => 'Bruno Mars',
        'fe_favourite_books'               => 'Crime and Punishment',
        ),
        array(
        'date_created'                     => '2016-04-25 17:24:23',
            'date_modified'                => '2016-06-04 15:55:19',
            'email'                        => 'maria@mail.com',
            'nickname'                     => 'Maria',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Maria',
            'sname'                        => 'Santos',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '917fa00264.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 130,
            'id_country'                   => 'US',
            'id_region'                    => 5,
            'id_city'                      => 5,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1991-01-06',
            'age'                          => 27,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 2,
            'search_field'                 => 'Maria; Santos; Maria; 1991-01-06; United States, New York City Weight 40kg - 50kg (89-111lbs); Height 151cm-160cm(5ft-5,3ft); Body type Normal; Hair Black; Style Fashion, Grunge; Any date with the person I love; Hopefully it is yet to come )); Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:55:19',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:55:22',
            'lat'                          => 40.7142700,
            'lon'                          => -74.0059700,
        'fe_iphone_android'                => 2,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 4,
        'fe_style'                         => 40,
        'fe_favourite_films'               => '12 Angry Men',
        'fe_favourite_tv_shows'            => 'Elementary',
        'fe_favourite_music'               => 'Christina Aguilera',
        'fe_favourite_books'               => 'Pippi Longstocking',
        ),
        array(
        'date_created'                     => '2016-04-25 17:30:22',
            'date_modified'                => '2016-04-29 16:46:59',
            'email'                        => 'thomas@mail.com',
            'nickname'                     => 'ThomasM',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Thomas',
            'sname'                        => 'Monaghan',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '148e5f96e9.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 90,
            'id_country'                   => 'DE',
            'id_region'                    => 2,
            'id_city'                      => 2,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1993-02-16',
            'age'                          => 25,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 1,
            'search_field'                 => 'Thomas; Monaghan; ThomasM; 1993-02-16; Germany, Berlin Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Normal; Hair Chestnut; Style Business, Classic; rope jumping :); I don\'t like my birthdays much; Interests Cinema, Music, Cooking;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '0000-00-00 00:00:00',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-01 18:18:03',
            'lat'                          => 52.5166667,
            'lon'                          => 13.4000000,
        'fe_iphone_android'                => 2,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 4,
        'fe_style'                         => 6,
        'fe_favourite_films'               => 'Taxi Driver',
        'fe_favourite_tv_shows'            => 'Bones',
        'fe_favourite_music'               => 'John Legend',
        'fe_favourite_books'               => 'Hamlet, King Lear',
        ),
        array(
        'date_created'                     => '2016-04-25 17:36:31',
            'date_modified'                => '2016-06-04 15:55:42',
            'email'                        => 'christine@mail.com',
            'nickname'                     => 'Christine',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Christine',
            'sname'                        => 'Fleur',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => 'b53a3c56aa.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 160,
            'id_country'                   => 'FR',
            'id_region'                    => 1,
            'id_city'                      => 1,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1994-03-09',
            'age'                          => 24,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 1,
            'search_field'                 => 'Christine; Fleur; Christine; 1994-03-09; France, Paris Weight 40kg - 50kg (89-111lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Thin; Hair Blond; Style Fashion; I like the old-fashioned way, flowers, dinner - romantic evening; When I got a pet!; Interests Music, Cooking, Painting, Shopping;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:55:42',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:55:49',
            'lat'                          => 48.8666670,
            'lon'                          => 2.3333330,
        'fe_iphone_android'                => 1,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 4,
        'fe_style'                         => 8,
        'fe_favourite_films'               => 'Gravity',
        'fe_favourite_tv_shows'            => 'Homeland',
        'fe_favourite_music'               => 'Shakira, Juanes',
        'fe_favourite_books'               => 'Don Quixote',
        ),
        array(
        'date_created'                     => '2016-04-25 17:43:36',
            'date_modified'                => '2016-06-04 15:56:05',
            'email'                        => 'marcia@mail.com',
            'nickname'                     => 'Marcia',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Marcia',
            'sname'                        => 'Courtney',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => 'd8a6f4a7e3.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 150,
            'id_country'                   => 'US',
            'id_region'                    => 5,
            'id_city'                      => 5,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1993-04-30',
            'age'                          => 25,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 2,
            'search_field'                 => 'Marcia; Courtney; Marcia; 1993-04-30; United States, New York City Weight 40kg - 50kg (89-111lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Black; Style Business, Classic, Fashion, Free, Grunge, Sport; do something together; away from home; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:56:05',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:56:12',
            'lat'                          => 40.7142700,
            'lon'                          => -74.0059700,
        'fe_iphone_android'                => 3,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 3,
        'fe_style'                         => 318,
        'fe_favourite_films'               => 'LA Confidential',
        'fe_favourite_tv_shows'            => 'Two and a Half Men',
        'fe_favourite_music'               => 'Rolling Stones',
        'fe_favourite_books'               => 'The Trial, The Castle',
        ),
        array(
        'date_created'                     => '2016-04-25 17:47:17',
            'date_modified'                => '2016-06-04 15:56:31',
            'email'                        => 'clark22@mail.com',
            'nickname'                     => 'Clark',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Clark',
            'sname'                        => 'Gibbs',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '42baa183d7.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 180,
            'id_country'                   => 'GB',
            'id_region'                    => 4,
            'id_city'                      => 4,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1990-05-15',
            'age'                          => 28,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 3,
            'search_field'                 => 'Clark; Gibbs; Clark; 1990-05-15; United Kingdom, London Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Athletic; Hair Black; Style Free, Sport; I like outdoor activities, so I\'d like to spend the time with my date outdoors; yet to come; Interests Cinema, Music, Cooking, Shopping, TV, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:56:31',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:56:37',
            'lat'                          => 51.5085300,
            'lon'                          => -0.1257400,
        'fe_iphone_android'                => 2,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 3,
        'fe_style'                         => 272,
        'fe_favourite_films'               => 'King Kong, ET, Aliens',
        'fe_favourite_tv_shows'            => 'True Blood',
        'fe_favourite_music'               => 'Justin Timberlake',
        'fe_favourite_books'               => 'Great Expectations',
        ),
        array(
        'date_created'                     => '2016-04-25 17:53:29',
            'date_modified'                => '2016-06-04 15:56:52',
            'email'                        => 'lucy@mail.com',
            'nickname'                     => 'Lucille',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Lucy',
            'sname'                        => 'Atwood',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '3350bc8ad3.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 60,
            'id_country'                   => 'DE',
            'id_region'                    => 2,
            'id_city'                      => 2,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1994-06-24',
            'age'                          => 24,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 2,
            'search_field'                 => 'Lucy; Atwood; Lucille; 1994-06-24; Germany, Berlin Weight 51kg - 60kg (113-133lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Blond; Style Classic, Fashion; Definitely involving nice dinner; Two years ago when I was in India, such an amazing country!; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:56:52',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:57:04',
            'lat'                          => 52.5166667,
            'lon'                          => 13.4000000,
        'fe_iphone_android'                => 3,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 4,
        'fe_style'                         => 12,
        'fe_favourite_films'               => 'Lawrence of Arabia',
        'fe_favourite_tv_shows'            => 'Grey\'s Anatomy',
        'fe_favourite_music'               => 'One Direction',
        'fe_favourite_books'               => 'The Old Man and the Sea',
        ),
        array(
        'date_created'                     => '2016-04-25 17:59:34',
            'date_modified'                => '2016-06-04 15:57:23',
            'email'                        => 'chrisj@mail.com',
            'nickname'                     => 'Chris',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Chris',
            'sname'                        => 'Johnson',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => 'a36d631339.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 140,
            'id_country'                   => 'US',
            'id_region'                    => 5,
            'id_city'                      => 5,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1993-06-12',
            'age'                          => 25,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 2,
            'search_field'                 => 'Chris; Johnson; Chris; 1993-06-12; United States, New York City Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Normal; Hair Black; Style Business, Classic, Fashion, Free, Grunge, Sport; Take a ride somewhere; Every day is good enough, birthday is nothing really special; Interests Music;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '2016-07-04 15:57:23',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 1,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-04 15:57:24',
            'lat'                          => 40.7142700,
            'lon'                          => -74.0059700,
        'fe_iphone_android'                => 4,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 3,
        'fe_style'                         => 318,
        'fe_favourite_films'               => 'North by Northwest',
        'fe_favourite_tv_shows'            => 'The Blacklist',
        'fe_favourite_music'               => 'Katy Perry, Rihanna',
        'fe_favourite_books'               => 'Wuthering Heights',
        ),
        array(
        'date_created'                     => '2016-04-25 18:04:40',
            'date_modified'                => '2016-06-01 16:58:15',
            'email'                        => 'kathy@mail.com',
            'nickname'                     => 'Kathy',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Kathy',
            'sname'                        => 'Ryan',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '279732c33a.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 105,
            'id_country'                   => 'ES',
            'id_region'                    => 3,
            'id_city'                      => 3,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1994-07-07',
            'age'                          => 24,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 3,
            'search_field'                 => 'Kathy; Ryan; Kathy; 1994-07-07; Spain, Madrid Weight 61kg - 70kg (135-155lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Normal; Hair Black; Style Classic, Fashion; Going to theatre, then dinner; Oh, all my birthdays have been great so far; Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '0000-00-00 00:00:00',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-01 18:10:39',
            'lat'                          => 40.4165000,
            'lon'                          => -3.7025600,
        'fe_iphone_android'                => 3,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 3,
        'fe_style'                         => 12,
        'fe_favourite_films'               => '12 Years a Slave',
        'fe_favourite_tv_shows'            => 'The Voice, Glee',
        'fe_favourite_music'               => 'Snoop Dogg',
        'fe_favourite_books'               => 'One Hundred Years of Solitude',
        ),
        array(
        'date_created'                     => '2016-04-25 18:12:27',
            'date_modified'                => '2016-06-01 16:58:14',
            'email'                        => 'jonathan@mail.com',
            'nickname'                     => 'Jonathan',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Jonathan',
            'sname'                        => 'Davies',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '368c8a7460.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 177,
            'id_country'                   => 'GB',
            'id_region'                    => 4,
            'id_city'                      => 4,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1987-08-24',
            'age'                          => 31,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 3,
            'search_field'                 => 'Jonathan; Davies; Jonathan; 1987-08-24; United Kingdom, London Weight 71kg - 80kg (157-177lbs); Height 181cm-190cm(6ft-6,3ft); Body type Normal; Hair Chestnut; Style Business, Classic; Bar crawl would be ideal.; Last year, I can tell you why, just ask; Interests Painting, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '0000-00-00 00:00:00',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-01 18:09:10',
            'lat'                          => 51.5085300,
            'lon'                          => -0.1257400,
        'fe_iphone_android'                => 2,
        'fe_windows_mac'                   => 2,
        'fe_facebook_twitter'              => 1,
        'fe_style'                         => 6,
        'fe_favourite_films'               => 'Toy Story - all parts',
        'fe_favourite_tv_shows'            => 'Mad Men',
        'fe_favourite_music'               => 'Chris Brown',
        'fe_favourite_books'               => 'Madame Bovary',
        ),
        array(
        'date_created'                     => '2016-04-25 18:23:09',
            'date_modified'                => '2016-06-01 16:58:14',
            'email'                        => 'mahmoud@mail.com',
            'nickname'                     => 'Mahmoud',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Mahmoud',
            'sname'                        => 'Ahmed',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => 'cdddc53341.png',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 123,
            'id_country'                   => 'US',
            'id_region'                    => 5,
            'id_city'                      => 5,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1991-09-19',
            'age'                          => 27,
            'show_adult'                   => 0,
            'profile_completion'           => 90,
            'views_count'                  => 3,
            'search_field'                 => 'Mahmoud; Ahmed; Mahmoud; 1991-09-19; United States, New York City Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Athletic; Hair Black; Style Business, Classic, Fashion, Free, Grunge, Sport; Interests Cinema, Music, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '0000-00-00 00:00:00',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-01 18:13:13',
            'lat'                          => 40.7142700,
            'lon'                          => -74.0059700,
        'fe_iphone_android'                => 1,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 3,
        'fe_style'                         => 318,
        'fe_favourite_films'               => 'Apocalypse Now',
        'fe_favourite_tv_shows'            => 'The Big Bang Theory',
        'fe_favourite_music'               => 'The Big Bang Theory',
        'fe_favourite_books'               => 'Ulysses',
        ),
        array(
        'date_created'                     => '2016-04-25 18:27:47',
            'date_modified'                => '2016-06-01 16:58:41',
            'email'                        => 'nat@mail.com',
            'nickname'                     => 'Natalie',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Natalie',
            'sname'                        => 'Coldman',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => '437de18441.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 308,
            'id_country'                   => 'FR',
            'id_region'                    => 1,
            'id_city'                      => 1,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1994-10-15',
            'age'                          => 24,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 3,
            'search_field'                 => 'Natalie; Coldman; Natalie; 1994-10-15; France, Paris Weight 40kg - 50kg (89-111lbs); Height 160cm-170cm(5,3ft-5,7ft); Body type Thin; Hair Chestnut; Style Classic, Fashion, Free; Skiing, sailing; The next one is going to be just fine); Interests Cinema, Music, Cooking, Painting, Shopping, TV, Internet;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '0000-00-00 00:00:00',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-01 18:17:09',
            'lat'                          => 48.8666670,
            'lon'                          => 2.3333330,
        'fe_iphone_android'                => 2,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 2,
        'fe_style'                         => 28,
        'fe_favourite_films'               => 'Finding Nemo',
        'fe_favourite_tv_shows'            => 'Modern Family',
        'fe_favourite_music'               => 'Lenny Kravitz',
        'fe_favourite_books'               => 'Moby-Dick',
        ),
        array(
        'date_created'                     => '2016-04-29 15:53:17',
            'date_modified'                => '2016-06-01 17:36:03',
            'email'                        => 'anna@mail.com',
            'nickname'                     => 'Annie',
            'user_type'                    => 'female',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'Anna',
            'sname'                        => 'Crawford',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => 'c11bd5a0e1.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 67,
            'id_country'                   => 'DE',
            'id_region'                    => 2,
            'id_city'                      => 2,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1993-09-30',
            'age'                          => 25,
            'show_adult'                   => 0,
            'profile_completion'           => 100,
            'views_count'                  => 5,
            'search_field'                 => 'Anna; Crawford; Annie; 1993-09-30; Germany, Berlin Weight 51kg - 60kg (113-133lbs); Height 171cm-180cm(5,7ft-6ft); Body type Thin; Hair Blond; Style Business, Classic, Fashion, Free, Sport; It starts with flowers); When I turned 15, my parents bought me a horse!; Interests Cinema, Music, Cooking;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '0000-00-00 00:00:00',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-01 18:25:14',
            'lat'                          => 52.5166667,
            'lon'                          => 13.4000000,
        'fe_iphone_android'                => 3,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 1,
        'fe_style'                         => 286,
        'fe_favourite_films'               => 'Singin\' in the Rain',
        'fe_favourite_tv_shows'            => 'Game of Thrones',
        'fe_favourite_music'               => 'Justin Bieber, Lady Gaga and Katy Perry',
        'fe_favourite_books'               => 'Pride and Prejudice and other books by Jane Austen',
        ),
        array(
        'date_created'                     => '2016-04-29 16:11:46',
            'date_modified'                => '2016-06-01 17:30:55',
            'email'                        => 'will@mail.com',
            'nickname'                     => 'William',
            'user_type'                    => 'male',
            'password'                     => 'e10adc3949ba59abbe56e057f20f883e',
            'confirm'                      => 1,
            'approved'                     => 1,
            'activity'                     => 1,
            'confirm_code'                 => '',
            'fname'                        => 'William',
            'sname'                        => 'Elk',
            'lang_code'                    => 'en',
            'user_open_id'                 => '',
            'user_logo'                    => 'ee5136d1ce.jpg',
            'user_logo_moderation'         => '',
            'logo_comments_count'          => 0,
            'group_id'                     => 1,
            'account'                      => 190,
            'id_country'                   => 'GB',
            'id_region'                    => 4,
            'id_city'                      => 4,
            'phone'                        => '',
            'address'                      => '',
            'postal_code'                  => '',
            'birth_date'                   => '1990-10-20',
            'age'                          => 28,
            'show_adult'                   => 0,
            'profile_completion'           => 95,
            'views_count'                  => 5,
            'search_field'                 => 'William; Elk; William; 1990-10-20; United Kingdom, London Weight 71kg - 80kg (157-177lbs); Height 171cm-180cm(5,7ft-6ft); Body type Normal; Hair Black; Style Business, Classic; Some formal dinner or gala event; Interests Music, Cooking, Painting, Shopping;',
            'activated_end_date'           => '0000-00-00 00:00:00',
            'featured_end_date'            => '0000-00-00 00:00:00',
            'hide_on_site_end_date'        => '0000-00-00 00:00:00',
            'highlight_in_search_end_date' => '0000-00-00 00:00:00',
            'up_in_search_end_date'        => '0000-00-00 00:00:00',
            'leader_bid'                   => 0,
            'leader_text'                  => '',
            'leader_write_date'            => '0000-00-00 00:00:00',
            'online_status'                => 0,
            'site_status'                  => 0,
            'date_last_activity'           => '2016-06-01 18:18:23',
            'lat'                          => 51.5085300,
            'lon'                          => -0.1257400,
        'fe_iphone_android'                => 1,
        'fe_windows_mac'                   => 1,
        'fe_facebook_twitter'              => 1,
        'fe_style'                         => 6,
        'fe_favourite_films'               => 'The Artist',
        'fe_favourite_tv_shows'            => 'Once Upon a Time',
        'fe_favourite_music'               => 'Kelly Clarkson',
        'fe_favourite_books'               => 'Mrs Dalloway',
        ),
    ),
    'users_views' => array(
        array(
            'id_user'   => 1,
            'id_viewer' => 2,
            'view_date' => '2016-04-25',),
        array(
            'id_user'   => 1,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 1,
            'id_viewer' => 2,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 1,
            'id_viewer' => 9,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 2,
            'id_viewer' => 3,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 2,
            'id_viewer' => 1,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 2,
            'id_viewer' => 1,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 2,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 2,
            'id_viewer' => 5,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 2,
            'id_viewer' => 8,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 2,
            'id_viewer' => 8,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 3,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 4,
            'id_viewer' => 1,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 4,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 5,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 6,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 7,
            'id_viewer' => 5,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 7,
            'id_viewer' => 11,
            'view_date' => '2016-04-25',),
        array(
            'id_user'   => 8,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 8,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 8,
            'id_viewer' => 15,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 9,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 9,
            'id_viewer' => 16,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 10,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 10,
            'id_viewer' => 7,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 11,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 11,
            'id_viewer' => 8,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 11,
            'id_viewer' => 16,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 12,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 12,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 12,
            'id_viewer' => 7,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 13,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 13,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 13,
            'id_viewer' => 7,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 14,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 14,
            'id_viewer' => 5,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 14,
            'id_viewer' => 8,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 15,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 15,
            'id_viewer' => 3,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 15,
            'id_viewer' => 7,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 15,
            'id_viewer' => 8,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 15,
            'id_viewer' => 16,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 16,
            'id_viewer' => 1,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 16,
            'id_viewer' => 2,
            'view_date' => '2016-04-29',),
        array(
            'id_user'   => 16,
            'id_viewer' => 6,
            'view_date' => '2016-06-01',),
        array(
            'id_user'   => 16,
            'id_viewer' => 8,
            'view_date' => '2016-04-30',),
        array(
            'id_user'   => 16,
            'id_viewer' => 15,
            'view_date' => '2016-04-29', ),
    ),
    'users_viewers' => array(
        array(
            'id_user'   => 1,
            'id_viewer' => 2,
            'view_date' => '2016-04-30 12:47:24',),
        array(
            'id_user'   => 1,
            'id_viewer' => 9,
            'view_date' => '2016-06-01 17:08:49',),
        array(
            'id_user'   => 2,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:25',),
        array(
            'id_user'   => 2,
            'id_viewer' => 3,
            'view_date' => '2016-06-01 17:52:32',),
        array(
            'id_user'   => 2,
            'id_viewer' => 8,
            'view_date' => '2016-06-01 18:15:31',),
        array(
            'id_user'   => 2,
            'id_viewer' => 5,
            'view_date' => '2016-06-01 16:29:45',),
        array(
            'id_user'   => 3,
            'id_viewer' => 2,
            'view_date' => '2016-04-29 16:47:04',),
        array(
            'id_user'   => 4,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:22',),
        array(
            'id_user'   => 5,
            'id_viewer' => 2,
            'view_date' => '2016-04-29 16:46:59',),
        array(
            'id_user'   => 6,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:19',),
        array(
            'id_user'   => 7,
            'id_viewer' => 11,
            'view_date' => '2016-04-25 18:09:02',),
        array(
            'id_user'   => 7,
            'id_viewer' => 5,
            'view_date' => '2016-06-01 16:32:35',),
        array(
            'id_user'   => 8,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:16',),
        array(
            'id_user'   => 8,
            'id_viewer' => 2,
            'view_date' => '2016-04-29 16:46:58',),
        array(
            'id_user'   => 8,
            'id_viewer' => 15,
            'view_date' => '2016-04-29 16:04:56',),
        array(
            'id_user'   => 9,
            'id_viewer' => 16,
            'view_date' => '2016-04-29 16:29:05',),
        array(
            'id_user'   => 9,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:17',),
        array(
            'id_user'   => 10,
            'id_viewer' => 7,
            'view_date' => '2016-06-01 16:38:06',),
        array(
            'id_user'   => 10,
            'id_viewer' => 2,
            'view_date' => '2016-04-29 16:46:58',),
        array(
            'id_user'   => 11,
            'id_viewer' => 8,
            'view_date' => '2016-04-30 18:39:51',),
        array(
            'id_user'   => 11,
            'id_viewer' => 16,
            'view_date' => '2016-04-29 16:32:18',),
        array(
            'id_user'   => 11,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:15',),
        array(
            'id_user'   => 12,
            'id_viewer' => 2,
            'view_date' => '2016-04-29 16:46:57',),
        array(
            'id_user'   => 12,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:14',),
        array(
            'id_user'   => 12,
            'id_viewer' => 7,
            'view_date' => '2016-06-01 16:38:04',),
        array(
            'id_user'   => 13,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:14',),
        array(
            'id_user'   => 13,
            'id_viewer' => 7,
            'view_date' => '2016-06-01 16:50:32',),
        array(
            'id_user'   => 13,
            'id_viewer' => 2,
            'view_date' => '2016-04-29 16:46:56',),
        array(
            'id_user'   => 14,
            'id_viewer' => 8,
            'view_date' => '2016-04-30 18:39:50',),
        array(
            'id_user'   => 14,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:41',),
        array(
            'id_user'   => 14,
            'id_viewer' => 5,
            'view_date' => '2016-06-01 16:32:13',),
        array(
            'id_user'   => 15,
            'id_viewer' => 3,
            'view_date' => '2016-06-01 17:36:03',),
        array(
            'id_user'   => 15,
            'id_viewer' => 8,
            'view_date' => '2016-04-30 18:39:49',),
        array(
            'id_user'   => 15,
            'id_viewer' => 7,
            'view_date' => '2016-06-01 16:38:03',),
        array(
            'id_user'   => 15,
            'id_viewer' => 16,
            'view_date' => '2016-04-29 16:31:14',),
        array(
            'id_user'   => 15,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 17:10:03',),
        array(
            'id_user'   => 16,
            'id_viewer' => 2,
            'view_date' => '2016-04-29 16:46:56',),
        array(
            'id_user'   => 16,
            'id_viewer' => 8,
            'view_date' => '2016-04-30 18:40:42',),
        array(
            'id_user'   => 16,
            'id_viewer' => 15,
            'view_date' => '2016-04-29 16:33:40',),
        array(
            'id_user'   => 16,
            'id_viewer' => 1,
            'view_date' => '2016-06-01 16:58:03',),
        array(
            'id_user'   => 16,
            'id_viewer' => 6,
            'view_date' => '2016-06-01 17:30:55',),
    ),
);
