<?php

return array(
    'registration_login_form' => array(
        'gid'    => 'registration_login_form',
        'module' => 'users',
        'model'  => 'Users_model',
        'method' => '_dynamic_block_get_registration_login_form',
        'views'  => array(
            array(
                'gid' => 'registration_form',
            ),
            array(
                'gid' => 'login_form',
            ),
        ),
        'area'    => array(),
        'presets' => array(
            array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'login_form',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '6',
                'x'          => '8',
                'y'          => '3',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'login_form',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '6',
                'x'          => '8',
                'y'          => '3',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'girls',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'registration_form',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '6',
                'x'          => '4',
                'y'          => '3',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'neighbourhood',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'registration_form',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '5',
                'x'          => '0',
                'y'          => '3',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'companions',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'registration_form',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '6',
                'x'          => '4',
                'y'          => '3',
                'w'          => '4',
                'h'          => '1',
            ),
        ),
    ),
    'new_users' => array(
        'gid'    => 'new_users',
        'module' => 'users',
        'model'  => 'Users_model',
        'method' => '_dynamic_block_get_new_users',
        'params' => array(
            'title' => array(
                'type'    => 'text',
                'default' => '',
                'gid'     => 'title',
            ),
            'count' => array(
                'type'    => 'int',
                'default' => '8',
                'gid'     => 'count',
            ),
            'user_type' => array(
                'type'    => 'int',
                'default' => '0',
                'gid'     => 'user_type',
            ),
        ),
        'views' => array(
            array(
                'gid' => 'big_thumbs',
            ),
            array(
                'gid' => 'medium_thumbs',
            ),
            array(
                'gid' => 'small_thumbs',
            ),
            array(
                'gid' => 'small_thumbs_w_descr',
            ),
            array(
                'gid' => 'carousel',
            ),
            array(
                'gid' => 'carousel_w_descr',
            ),
        ),
        'area' => array(
            array(
                'gid'        => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:0:"";s:8:"title_ru";s:0:"";s:5:"count";s:1:"4";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'medium_thumbs',
                'width'      => '100',
                'sorter'     => '10',
                'cache_time' => '0',
                'x'          => '0',
                'y'          => '6',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
        'presets' => array(
            array(
                'gid_preset' => 'default',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:0:"";s:8:"title_ru";s:0:"";s:5:"count";s:1:"4";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'medium_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '10',
                'x'          => '0',
                'y'          => '6',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'girlfriends',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:0:"";s:8:"title_ru";s:0:"";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'carousel',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '5',
                'x'          => '0',
                'y'          => '3',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'jewish',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:0:"";s:8:"title_ru";s:0:"";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '6',
                'x'          => '0',
                'y'          => '4',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lovers',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:9:"New Users";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"6";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'big_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '7',
                'x'          => '0',
                'y'          => '5',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'blackonwhite',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:9:"New Users";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'medium_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '9',
                'x'          => '0',
                'y'          => '6',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'deepblue',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:9:"New Users";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"3";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'big_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '11',
                'x'          => '0',
                'y'          => '9',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'companions',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:9:"New Users";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"6";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs_w_descr',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '8',
                'x'          => '0',
                'y'          => '5',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'community',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:0:"";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'carousel',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '5',
                'x'          => '0',
                'y'          => '3',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'christian',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:9:"New Users";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '9',
                'x'          => '0',
                'y'          => '7',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'autumn_walk',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:0:"";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"4";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'medium_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '12',
                'x'          => '0',
                'y'          => '9',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'persimmon_red',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:9:"New users";s:8:"title_ru";s:35:"Новые пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";} ',
                'view_str'   => 'small_thumbs',
                'width'      => '50',
                'sorter'     => '11',
                'cache_time' => '0',
                'x'          => '0',
                'y'          => '7',
                'w'          => '6',
                'h'          => '1',
            ),
        ),
    ),
    'active_users' => array(
        'gid'    => 'active_users',
        'module' => 'users',
        'model'  => 'Users_model',
        'method' => '_dynamic_block_get_active_users',
        'params' => array(
            'title' => array(
                'type'    => 'text',
                'default' => 'Last active users',
                'gid'     => 'title',
            ),
            'count' => array(
                'type'    => 'int',
                'default' => '8',
                'gid'     => 'count',
            ),
            'user_type' => array(
                'type'    => 'int',
                'default' => '0',
                'gid'     => 'user_type',
            ),
        ),
        'views' => array(
            array(
                'gid' => 'big_thumbs',
            ),
            array(
                'gid' => 'medium_thumbs',
            ),
            array(
                'gid' => 'small_thumbs',
            ),
            array(
                'gid' => 'small_thumbs_w_descr',
            ),
            array(
                'gid' => 'carousel',
            ),
            array(
                'gid' => 'carousel_w_descr',
            ),
        ),
        'area'    => array(),
        'presets' => array(
            array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:19:"Latest active users";s:8:"title_ru";s:35:"Заходившие недавно";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '16',
                'x'          => '0',
                'y'          => '11',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:19:"Latest active users";s:8:"title_ru";s:35:"Заходившие недавно";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '16',
                'x'          => '0',
                'y'          => '11',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'deepblue',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:13:"Latest Active";s:8:"title_ru";s:35:"Заходившие недавно";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'carousel_w_descr',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '7',
                'x'          => '0',
                'y'          => '5',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
    ),
    'featured_users' => array(
        'gid'    => 'featured_users',
        'module' => 'users',
        'model'  => 'Users_model',
        'method' => '_dynamic_block_get_featured_users',
        'params' => array(
            'title' => array(
                'type'    => 'text',
                'default' => 'Featured users',
                'gid'     => 'title',
            ),
            'count' => array(
                'type'    => 'int',
                'default' => '8',
                'gid'     => 'count',
            ),
            'user_type' => array(
                'type'    => 'int',
                'default' => '0',
                'gid'     => 'user_type',
            ),
        ),
        'views' => array(
            array(
                'gid' => 'big_thumbs',
            ),
            array(
                'gid' => 'medium_thumbs',
            ),
            array(
                'gid' => 'small_thumbs',
            ),
            array(
                'gid' => 'small_thumbs_w_descr',
            ),
            array(
                'gid' => 'carousel',
            ),
            array(
                'gid' => 'carousel_w_descr',
            ),
        ),
        'area' => array(
            array(
                'gid'        => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:45:"Популярные пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'sorter'     => '13',
                'cache_time' => '0',
                'x'          => '0',
                'y'          => '9',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
        'presets' => array(
            array(
                'gid_preset' => 'default',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:45:"Популярные пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '13',
                'x'          => '0',
                'y'          => '9',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:45:"Популярные пользователи";s:5:"count";s:1:"4";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'medium_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '13',
                'x'          => '0',
                'y'          => '9',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:45:"Популярные пользователи";s:5:"count";s:1:"4";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'medium_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '13',
                'x'          => '0',
                'y'          => '9',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'girls',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:45:"Популярные пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '11',
                'x'          => '0',
                'y'          => '7',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'neighbourhood',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:45:"Популярные пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'medium_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '8',
                'x'          => '0',
                'y'          => '5',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'autumn_walk',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:45:"Популярные пользователи";s:5:"count";s:1:"8";s:9:"user_type";s:1:"0";}',
                'view_str'   => 'small_thumbs',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '11',
                'x'          => '0',
                'y'          => '8',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'persimmon_red',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:8:"title_en";s:14:"Featured users";s:8:"title_ru";s:28:"VIP-пользователи";s:5:"count";i:8;s:9:"user_type";i:0;}',
                'view_str'   => 'small_thumbs',
                'width'      => '50',
                'sorter'     => '12',
                'cache_time' => '0',
                'x'          => '6',
                'y'          => '7',
                'w'          => '6',
                'h'          => '1',
            ),
        ),
    ),
    'auth_links' => array(
        'gid'    => 'auth_links',
        'module' => 'users',
        'model'  => 'Users_model',
        'method' => '_dynamic_block_get_auth_links',
        'params' => array(
            'right_align' => array(
                'type'    => 'checkbox',
                'default' => '1',
                'gid'     => 'right_align',
            ),
        ),
        'views' => array(
            array(
                'gid' => 'default',
            ),
        ),
        'area' => array(
            array(
                'gid'        => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'sorter'     => '4',
                'cache_time' => '0',
                'x'          => '6',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
        ),
        'presets' => array(
            array(
                'gid_preset' => 'default',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '4',
                'x'          => '6',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '4',
                'x'          => '6',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '4',
                'x'          => '6',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'girlfriends',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '6',
                'y'          => '1',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'jewish',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '8',
                'y'          => '1',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lovers',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '8',
                'y'          => '1',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'blackonwhite',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '4',
                'x'          => '6',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'deepblue',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '8',
                'y'          => '1',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'community',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '8',
                'y'          => '1',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'christian',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '6',
                'y'          => '1',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'autumn_walk',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '4',
                'x'          => '6',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'persimmon_red',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'sorter'     => '4',
                'cache_time' => '0',
                'x'          => '6',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
        ),
    ),
    'lang_select' => array(
        'gid'    => 'lang_select',
        'module' => 'users',
        'model'  => 'Users_model',
        'method' => '_dynamic_block_get_lang_select',
        'params' => array(
            'right_align' => array(
                'type'    => 'checkbox',
                'default' => '1',
                'gid'     => 'right_align',
            ),
        ),
        'views' => array(
            array(
                'gid' => 'default',
            ),
        ),
        'area' => array(
            array(
                'gid'        => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'sorter'     => '2',
                'cache_time' => '600',
                'x'          => '0',
                'y'          => '1',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
        'presets' => array(
            array(
                'gid_preset' => 'default',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '600',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'girls',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '70',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '4',
                'y'          => '1',
                'w'          => '8',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'jewish',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '1',
                'x'          => '0',
                'y'          => '0',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lovers',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '1',
                'x'          => '0',
                'y'          => '0',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'neighbourhood',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '6',
                'y'          => '1',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'blackonwhite',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'deepblue',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '1',
                'x'          => '0',
                'y'          => '0',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'companions',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '8',
                'y'          => '1',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'community',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '1',
                'x'          => '0',
                'y'          => '0',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'christian',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '5',
                'x'          => '0',
                'y'          => '3',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'autumn_walk',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '600',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '12',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'persimmon_red',
                'gid_area'   => 'index-page',
                'params'     => 'a:1:{s:11:"right_align";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '100',
                'sorter'     => '2',
                'cache_time' => '600',
                'x'          => '0',
                'y'          => '1',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
    ),
);
