<?php

$install_lang["block_active_users"] = "Самые активные пользователи";
$install_lang["block_auth_links"] = "Ссылки авторизации";
$install_lang["block_featured_users"] = "Популярные пользователи";
$install_lang["block_lang_select"] = "Выбор языка";
$install_lang["block_new_users"] = "Новые пользователи";
$install_lang["block_registration_login_form"] = "Регистрация / Вход";
$install_lang["param_active_users_count"] = "Число";
$install_lang["param_active_users_title"] = "Заголовок";
$install_lang["param_active_users_user_type"] = "ID типа пользователя (0 = все; берется из /admin/properties/property/user_type)";
$install_lang["param_auth_links_right_align"] = "Выравнивать справа";
$install_lang["param_featured_users_count"] = "Число";
$install_lang["param_featured_users_title"] = "Заголовок";
$install_lang["param_featured_users_user_type"] = "ID типа пользователя (0 = все; берется из /admin/properties/property/user_type)";
$install_lang["param_lang_select_right_align"] = "Выравнивать справа";
$install_lang["param_new_users_count"] = "Число";
$install_lang["param_new_users_title"] = "Заголовок";
$install_lang["param_new_users_user_type"] = "ID типа пользователя (0 = все; берется из /admin/properties/property/user_type)";
$install_lang["view_active_users_big_thumbs"] = "Большие картинки";
$install_lang["view_active_users_carousel"] = "Карусель";
$install_lang["view_active_users_carousel_w_descr"] = "Карусель с описанием";
$install_lang["view_active_users_medium_thumbs"] = "Средние картинки";
$install_lang["view_active_users_small_thumbs"] = "Маленькие картинки";
$install_lang["view_active_users_small_thumbs_w_descr"] = "Маленькие картинки с описанием";
$install_lang["view_auth_links_default"] = "По умолчанию";
$install_lang["view_featured_users_big_thumbs"] = "Большие картинки";
$install_lang["view_featured_users_carousel"] = "Карусель";
$install_lang["view_featured_users_carousel_w_descr"] = "Карусель с описанием";
$install_lang["view_featured_users_medium_thumbs"] = "Средние картинки";
$install_lang["view_featured_users_small_thumbs"] = "Маленькие картинки";
$install_lang["view_featured_users_small_thumbs_w_descr"] = "Маленькие картинки с описанием";
$install_lang["view_lang_select_default"] = "По умолчанию";
$install_lang["view_new_users_big_thumbs"] = "Большие картинки";
$install_lang["view_new_users_carousel"] = "Карусель";
$install_lang["view_new_users_carousel_w_descr"] = "Карусель с описанием";
$install_lang["view_new_users_medium_thumbs"] = "Средние картинки";
$install_lang["view_new_users_small_thumbs"] = "Маленькие картинки";
$install_lang["view_new_users_small_thumbs_w_descr"] = "Маленькие картинки с описанием";
$install_lang["view_registration_login_form_login_form"] = "Форма входа";
$install_lang["view_registration_login_form_registration_form"] = "Форма регистрации";
