<?php

return ['news' => [
        [
            'gid' => '5-common-lies-on-his-online-dating-profile',
            'name' => '5 Common Lies on His Online Dating Profile',
            'annotation' => 'How to keep an eye out for the characteristics men are most likely to lie about online...',
            'content' => '<blockquote><p>How to keep an eye out for the characteristics men are most likely to lie about online&#8230;</p></blockquote><p><img class="size-full wp-image-2680 aligncenter" alt="Girl with computer" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/Girl-with-computer.jpg" width="604" height="347" /></p><p>Unfortunately it&#8217;s becoming increasingly difficult to take a man&#8217;s <a href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=gen" target="_blank">online dating</a> profile at face value. A recent study conducted by AYI.com found that 1 in 3 <a title="AYI.com: What Women Want Infographic" href="http://www.ayi.com/dating-blog/what-women-want-infographic-ayi/" target="_blank">men admit to lying on a online dating profile</a> compared to fewer than 1 in 5 women, and that 55 percent of women who have used online dating have had a bad experience.</p><p>Do some men tell the whole truth, and nothing but the truth, in their online profiles? Certainly. But as a general rule, if you want to get the most out of your time in the world of <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=gen" target="_blank">online dating</a>, it’s a good idea to start reading between the lines and take everything you see and hear with a grain of salt.</p><p><strong><em><a href="http://www.ayi.com/dating-blog/online-dating-profile-tips-avoid-these-dating-mistakes/" target="_blank">Related: Online Dating Tips: 5 Profile Mistakes to Avoid</a></em></strong></p><h2><strong>The Most Common Online Dating Lies</strong></h2><p>If you’re looking for the cribs-notes cheat sheet for deciphering the truth from a dating profile, then keep an eye out for those characteristics men are most likely to lie about online.</p><p>Applying a skeptical eye to the top 5 facts and figures below will help you uncover 80 percent of online lies with minimum effort.</p><h3><strong>Height </strong></h3><p>The average man online says he’s at least one to two inches taller than he really is. Most men not only know women tend to prefer taller men, they also know women aren’t going to break out the measuring tape on a first date.</p><h3><strong>Weight/Physique </strong></h3><p>Through a combination of choosing what archetype best fits their body type (athletic, a little extra, obese, thin, jacked) and the pictures they decide to include in their profile, men can be pretty good at disguising what their bodies <em>really</em> look like.</p><h3><strong>Age </strong></h3><p>Sex advice columnist extraordinaire Dan Savage has stated he assumes every man with an online profile is probably two to five years older than he actually is.</p><p>This is a fair assumption to make even if I think the percentage of men lying about their age online isn’t quite as numerous as Savage suggests and is likely more common among daters in their 30s, 40s and 50s than among seniors and 20-somethings.</p><h3><strong>Income/Job </strong></h3><p>AYI.com&#8217;s study found that almost 1 in 2 <a title="AYI.com: What Women Want Infographic" href="http://www.ayi.com/dating-blog/what-women-want-infographic-ayi/" target="_blank">women are going to want to know a man&#8217;s employment status</a> on the first date. And as you’d imagine, many men lie about how much they make in their online dating profiles (rounding up of course).</p><p>Men may also exaggerate other details about their job, such as where they work and what position they actually hold.</p><h3><strong>Social Life/Social Connections </strong></h3><p>Plenty of men lie about the depth of their social lives.</p><p>Men who lie online about their social lives are likely to make it seem like they live more socially active lives than they have, and those men are also likely to lie about the quality of their social connections (exaggerate the importance of who they know and who they spend their time with).</p><p><em><strong><a href="http://www.ayi.com/dating-blog/10-ways-to-get-a-date-on-ayi-com/" target="_blank">Related: 10 Ways to Get a Date on AYI.com</a></strong></em></p><p><strong><img class="alignright size-full wp-image-2682" alt="internal woman and computer" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/internal-woman-and-computer.jpg" width="264" height="394" />Do all men significantly lie about these traits in their profiles? Of course not. Most men are <em>relatively</em> honest within their <a href="http://www.datingadvice.com/online-dating/dont-freak-out-when-writing-a-profile" target="_blank">dating site profiles</a>.</strong></p><p>A guy who is 5’7’’ probably isn’t going to say he’s 6’1’’ on his profile because you’ll know he was lying the second you meet him.</p><p>A guy who makes $20k a year flipping burgers isn’t going to say he makes $200k annually as an investment banker because he knows his dates will catch on to his deception pretty quickly.</p><p><strong>So what does this mean for you and your attempts at online dating success?</strong> Simple. Assume the men you meet might not be quite as tall, as successful or as connected as they say they are, and then decide whether you’d still consider dating them regardless.</p><p>If you’re happy with a man who’s a little shorter, broker and less socially winning than he presents himself online, then you won’t be disappointed if that’s exactly what he turns out to be when you meet in person.</p><p>You’ll have simply won the jackpot if the man who you end up grabbing a drink with really is the total package he seemed to be from his profile.</p><p><em>Read the original article on <a href="http://datingwithdignity.com/2013/02/how-to-decipher-his-online-profile/">Datingwithdignity.com</a></em></p><p><strong><em><span>♥</span> Keep up with AYI’s latest trending reports, dating data and tips on <a href="http://bit.ly/19HI3uk">Twitter</a>, <a href="http://bit.ly/17lu9KZ">YouTube</a>, <a title="AYI on Pinterest" href="http://pinterest.com/ayi/" target="_blank">Pinterest</a> and <a title="AYI.com Dating Blog" href="http://www.ayi.com/dating-blog" target="_blank">our blog</a>. </em></strong></p><p><strong><em><span>♥</span> To <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">browse singles</a> with similar interests in your area, visit <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">AYI.com</a>.</em></strong></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 12:35:40',
            'feed_link' => 'http://www.ayi.com/dating-blog/ayi-top-online-dating-profile-lies/',
            'feed_id' => 4,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'top-3-reasons-to-use-reverse-search',
            'name' => 'Top 3 Reasons to Use Reverse Search',
            'annotation' => 'How—and why—you should use AYI\'s newest feature to control who sees you in browse',
            'content' => '<blockquote><p>How—and why—you should use AYI&#8217;s newest feature to control who sees you in browse</p></blockquote><p><img class="aligncenter size-full wp-image-2742" title="AYI.com: Reverse Search" alt="Reverse Search Internal" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/Reverse-Search-Internal.jpg" width="831" height="328" /></p><p>What if the search for your perfect match could get smarter? AYI.com has recently launched its Reverse Search feature for web (mobile coming soon!, which means <strong>you</strong> can decide who can see you in browse so you&#8217;re only contacted by <a href="https://www.ayi.com/?source=10204&amp;subid=gen">singles</a> you&#8217;re interested in.</p><p>Why use Reverse Search? Here are the top 3 reasons to set up your preferences now!</p><p><strong>1. Save Time</strong></p><p><strong></strong>We know your everyday schedule is busy, and when it comes to dating—online and offline—no one has the time to talk to every person they come in contact with. Now you don&#8217;t have to worry about logging in to an overwhelmingly flooded inbox. Your messages and IM&#8217;s will only come from potential dates you <strong>want</strong> to hear from.</p><p><strong>2. Get Focused </strong></p><p>Location, location. Interested in meeting someone from another country? Set your location preference to <strong>all</strong>. Only interested in men in your immediate area so you can link up in person for a first date? Set your location preference to <strong>25 miles</strong>. Get focused and hone in on the exact matches you want to hear from based on their age and location. Now no one has to be geographically undesirable.</p><p><strong>3. Take Control</strong></p><p>Now you&#8217;re in the driver&#8217;s seat with complete control over your <a href="https://www.ayi.com/?source=10204&amp;subid=gen">online dating</a> experience. With millions of users on AYI.com, the dating space can feel enormous and unmanageable. Pairing your new Reverse Search option with your existing Advanced Search feature helps you narrow down the dating field and make more relevant, meaningful connections.</p><p><em><strong><a href="http://www.ayi.com/dating-blog/online-dating-profile-tips-avoid-these-dating-mistakes/">Related: 5 Profile Mistakes to Avoid</a></strong></em></p><p><strong>Now that you know all the great benefits to setting your Reverse Search preferences, get started! Here&#8217;s how in 3 easy steps:</strong></p><h3>STEP 1</h3><p>Click &#8220;Control who sees you&#8221; located on the right hand side of the blue browse tab</p><p><img class="aligncenter size-full wp-image-2800" alt="Reverse Search Screenshot" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/Reverse-Search-Screenshot1.jpg" width="710" height="472" /></p><h3>STEP 2</h3><p>Set your location and age preferences. Here you can dictate whether you would like users only within your country or as close as 25 miles to be able to view your profile and you can set the minimum and maximum age of a user that is allowed to contact you.</p><p><img class="aligncenter size-full wp-image-2765" alt="search preferences" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/search-preferences.jpg" width="795" height="345" /></p><h2>Step 3</h2><p>Save your preferences!</p><p><img class="aligncenter size-full wp-image-2752" alt="save preferences" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/save-preferences.jpg" width="420" height="311" /></p><p>&nbsp;</p><p>Now just sit back and enjoy your new online dating experience.</p><p><em><strong>Related: <a href="http://www.ayi.com/dating-blog/10-ways-to-get-a-date-on-ayi-com/">10 Ways to Get a Date on AYI.com</a></strong></em></p><p><strong><em><span>♥</span> Keep up with AYI’s latest trending reports, dating data and tips on <a href="http://bit.ly/19HI3uk">Twitter</a>, <a href="http://bit.ly/17lu9KZ">YouTube</a>, <a title="AYI on Pinterest" href="http://pinterest.com/ayi/" target="_blank">Pinterest</a> and <a title="AYI.com Dating Blog" href="http://www.ayi.com/dating-blog" target="_blank">our blog</a>. </em></strong></p><p><strong><em><span>♥</span> To <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">browse singles</a> with similar interests in your area, visit <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">AYI.com</a>.</em></strong></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 12:35:40',
            'feed_link' => 'http://www.ayi.com/dating-blog/online-dating-ayi-how-to-use-reverse-search-feature/',
            'feed_id' => 4,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'diy-halloween-costumes-couples-doing-it-right',
            'name' => 'DIY Halloween Costumes: Couples Doing It Right',
            'annotation' => 'These couples have used their imagination and craft skills to create unforgettable pairings.',
            'content' => '<p>Choosing a Halloween costume can be stressful. You want to be memorable, smart, sexy &#8230; but you also don&#8217;t want to break the bank.</p><p>These couples have used their imagination, sense of humor, and craft skills to create unforgettable pairings. We applaud their ingenuity! And we can&#8217;t wait to grab a friend and replicate some of these looks this Halloween.<br />&nbsp;</p><p><strong>Click through for inspiration: </strong></p><p>&nbsp;<br /><div><a href="http://www.ayi.com/dating-blog/online-dating-couples-costumes-halloween-diy-costume-ideas/#SlideDeck-2760">DIY Couples Costumes <small>[see the SlideDeck]</small></a></div></p><p>&nbsp;</p><p><strong><em><span>♥</span> Keep up with AYI’s latest trending reports, dating data and tips on <a href="http://bit.ly/19HI3uk">Twitter</a>, <a href="http://bit.ly/17lu9KZ">YouTube</a>, <a title="AYI on Pinterest" href="http://pinterest.com/ayi/" target="_blank">Pinterest</a> and <a title="AYI.com Dating Blog" href="http://www.ayi.com/dating-blog" target="_blank">our blog</a>. </em></strong></p><p><strong><em><span>♥</span> To <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">browse singles</a> with similar interests in your area, visit <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">AYI.com</a>.</em></strong></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 12:35:40',
            'feed_link' => 'http://www.ayi.com/dating-blog/online-dating-couples-costumes-halloween-diy-costume-ideas/',
            'feed_id' => 4,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'ayi-com-success-story-dia-amp-ralph',
            'name' => 'AYI.com Success Story: Dia &amp; Ralph',
            'annotation' => 'Dia found her soulmate, best friend and husband on AYI.com',
            'content' => '<p><img class="alignright  wp-image-2689" title="AYI.com Success Story: Ralph &amp; Dia" alt="AYI.com Success Story: Ralph &amp; Dia" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/09/Dia-and-Ralph-4.jpg" width="346" height="259" />&#8220;Hi, I am writing to share our own success story which happened here on AYI.com. I had been using the <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=gen">online dating</a> application for quite some time and I did get lots of yesses on my profile and messages along with it. One day, just as I was browsing the people who showed interest in me and my attention lingered on this guy who looked like the Hollywood actor Benjamin Bratt. His message was nothing out of the ordinary, but there was just something about him that caught my attention.</p><p>I replied to his message and then we added each other as friends on Facebook. We used Facebook as our primary means of communication. Because I live in the Philippines and he was from New York, the time difference kind of made it hard for us to stay &#8220;together&#8221; online most of the times. We then decided to set up a schedule so we knew when to log on. I gave him my cell phone number so we could text each other about the schedule. However, he didn&#8217;t use it for texting; instead, he called me a matter of seconds after he got the number.</p><p>The good thing about our set-up was that we opened our web cams 24/7. I was a writer and a massage therapist then, so I was mostly at home for my job. Ralph decided one day that the long distance had to stop. He made a big decision in his life when he moved from the United States to the Philippines, leaving his cozy apartment and his two cats to be with me here. We got married shortly after and celebrated our first anniversary as Mr. and Mrs. Ritoch.</p><p>Thank you so much AYI.com for bringing connecting me to my soulmate, my best friend and husband. I can&#8217;t thank you enough!&#8221;</p><p>- Dia</p><p><strong><em>Have your own AYI.com Success Story to share? <a title="Submit Your Online Dating Success Story" href="http://help.ayi.com/customer/portal/emails/new" target="_blank">Submit your story here</a> and at least one photo and we may feature it on our blog!</em></strong></p><p><strong><em><span>♥</span> Keep up with AYI’s latest trending reports, dating data and tips on <a href="http://bit.ly/19HI3uk">Twitter</a>, <a href="http://bit.ly/17lu9KZ">YouTube</a>, <a title="AYI on Pinterest" href="http://pinterest.com/ayi/" target="_blank">Pinterest</a> and <a title="AYI.com Dating Blog" href="http://www.ayi.com/dating-blog" target="_blank">our blog</a>. </em></strong></p><p><strong><em><span>♥</span> To <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">browse singles</a> with similar interests in your area, visit <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">AYI.com</a>.</em></strong></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 12:35:40',
            'feed_link' => 'http://www.ayi.com/dating-blog/online-dating-success-story-ayi-long-distance-relationship-dia-ralph/',
            'feed_id' => 4,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'funny-dating-101-on-time',
            'name' => 'Funny Dating 101: On Time',
            'annotation' => 'The time has come: after trying online dating, you finally get a first date with someone.',
            'content' => '<p>The time has come: after trying <a title="AYI.com" href="http://www.ayi.com" target="_blank">online dating</a>, you finally get a first date with someone. There are many factors to consider: what to wear, what to say, and most importantly, when to arrive.</p><p>Our guy below knew that arriving on time for the first date is key. He just didn&#8217;t realize the location was important, too. Luckily, he and his date had more in common than they realized. <strong>Watch:</strong></p><div></div><p>&nbsp;</p><p><strong><em><span>♥</span> Keep up with AYI.com’s latest trending reports, dating data and tips on <a href="http://bit.ly/19HI3uk" target="_blank">Twitter</a>, <a href="http://bit.ly/17lu9KZ">YouTube</a>, <a title="AYI.com on Pinterest" href="http://pinterest.com/ayi/" target="_blank">Pinterest</a> and <a title="AYI.com Dating Blog" href="http://www.ayi.com/dating-blog" target="_blank">our blog</a>. </em></strong></p><p><strong><em><span>♥</span> To <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=gen" target="_blank">browse singles</a> with similar interests in your area, visit <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=success-stories" target="_blank">AYI.com</a>.</em></strong></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 12:35:40',
            'feed_link' => 'http://www.ayi.com/dating-blog/online-dating-punctual-first-date-video/',
            'feed_id' => 4,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'date-your-way-to-a-better-relationship',
            'name' => 'Date Your Way to a Better Relationship',
            'annotation' => 'Put the spark back in your date nights',
            'content' => '<blockquote><p>Creative couples dates to add some spark to your weekends</p></blockquote><p><a href="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/shutterstock_106006154-e1382454591720.jpg"><img class="aligncenter  wp-image-2706" alt="Date Your Way to a Better Relationship" src="http://www.ayi.com/dating-blog/wp-content/uploads/2013/10/shutterstock_106006154-e1382454591720.jpg" width="636" height="330" /></a></p><p>Friday night, rent a video. Saturday night, rent a video. Sunday night, rent…well you know where this is going. Often, when in a long-term relationship, date nights become mundane and predictable. Put the spark back into your relationship. <strong>It’s easier than you think, but you will need to talk with your partner first.</strong> This really won’t take all that long and once it’s done all that’s left is to go out and have some fun.</p><p><em><strong>Related: <a title="Turn Your Apartment Into a Love Den" href="http://www.ayi.com/dating-blog/5-ways-to-turn-your-apartment-into-a-love-den/" target="_blank">5 Ways to Turn Your Apartment Into a Love Den</a></strong></em></p><h2>Creative Dates Add Spark to Your Relationship</h2><p><span>♥</span>Do you have similar hobbies or activities you enjoy? Plan a date around that. <a href="http://lifebytesbook.com/the-art-of-date-planning/">Talk with your partner </a>about things you may like to do. If you’re both athletic, go on a hiking date or have a date working out together at the gym, followed by a nice healthy snack at the gym&#8217;s café.</p><p><span>♥</span>Do you have <a title="Dating Outside Your Religion" href="http://www.ayi.com/dating-blog/online-dating-first-date-religious-beliefs-date-outside-faith/" target="_blank">vastly different interests</a>? Take turns planning dates that will introduce your partner to your hobby or fun activity.  His or her “thing” may never actually become <em>your</em> thing but you’ll at least have a better insight into what they find enjoyable.</p><h2>Do New Things Together</h2><p><span>♥</span>Do you <em>really</em> like doing the same old thing every week? You can still turn that up a notch or two. When I was growing up my parents had a date night every Saturday and they always went out to dinner. However, they made it a point to always go to a different restaurant, so they were continually trying different types of eateries.</p><p><span>♥</span><strong>No matter which route you choose, the key here is to be creative and have a sense of adventure.</strong> If you make the planning of your weekly date night a regular activity too you may find yourselves having as much fun in planning as in doing!</p><p><em><strong><em><strong>Related: <a title="Fall Date Ideas" href="http://www.ayi.com/dating-blog/dating-fall-date-ideas-slideshow/" target="_blank">6 Phenomenal Fall Date Ideas</a></strong></em></strong></em></p><p><strong><em><span>♥</span> Keep up with AYI’s latest trending reports, dating data and tips on <a href="http://bit.ly/19HI3uk">Twitter</a>, <a href="http://bit.ly/17lu9KZ">YouTube</a>, <a title="AYI on Pinterest" href="http://pinterest.com/ayi/" target="_blank">Pinterest</a> and <a title="AYI.com Dating Blog" href="http://www.ayi.com/dating-blog" target="_blank">our blog</a>. </em></strong></p><p><strong><em><span>♥</span> To <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">browse singles</a> with similar interests in your area, visit <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=zoopa" target="_blank">AYI.com</a>.</em></strong></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 17:13:33',
            'feed_link' => 'http://www.ayi.com/dating-blog/strengthen-your-relationship-advice-couples-date-ideas/',
            'feed_id' => 4,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'funny-dating-101-i-bet',
            'name' => 'Funny Dating 101: I Bet',
            'annotation' => 'A whole new meaning to the term "friends with benefits"',
            'content' => '<p>Sometimes your friends <em>really</em> do know what is best for you.</p><p>If  only our girl below knew that AYI.com lets you search for <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=gen" target="_blank">singles</a> through friends of friends, she might have avoided dating disasters with &#8220;Conspiracy Chris&#8221; and &#8220;Swaggy Steve&#8221;. <strong>Watch: </strong></p><div></div><p>&nbsp;</p><p><strong><em><span>♥</span> Keep up with AYI.com’s latest trending reports, dating data and tips on <a href="http://bit.ly/19HI3uk" target="_blank">Twitter</a>, <a href="http://bit.ly/17lu9KZ">YouTube</a>, <a title="AYI.com on Pinterest" href="http://pinterest.com/ayi/" target="_blank">Pinterest</a> and <a title="AYI.com Dating Blog" href="http://www.ayi.com/dating-blog" target="_blank">our blog</a>. </em></strong></p><p><strong><em><span>♥</span> To <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=gen" target="_blank">browse singles</a> with similar interests in your area, visit <a title="AYI.com" href="http://ayitrk.com/?a=10026&amp;c=23&amp;s1=success-stories" target="_blank">AYI.com</a>.</em></strong></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 17:13:33',
            'feed_link' => 'http://www.ayi.com/dating-blog/online-dating-friends-with-benefits-funny-dating-video-ayi/',
            'feed_id' => 4,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => '3-warning-signs-you-should-be-a-runaway-bride',
            'name' => '3 Warning Signs You Should Be A Runaway Bride',
            'annotation' => '                                                    Marriage can bring up all sorts of questions about your future spouse, and some of the answers may make you second-guess your commitment. Financial issues are some of the most important considerations before you say "I do". Listen up to this marriage advice to be truly sure about tying the knot.read more',
            'content' => '<div>    <div>            <div>                    <img src="http://images.tangomag.com/sites/default/files/imagecache/tee-images/image_blog/sneaks.jpg" alt="Marriage Advice: Financial Considerations Before The Wedding" title="" class="imagecache imagecache-tee-images imagecache-default imagecache-tee-images_default" width="240" height="180" />        </div>        </div></div>Marriage can bring up all sorts of questions about your future spouse, and some of the answers may make you second-guess your commitment. Financial issues are some of the most important considerations before you say "I do". Listen up to this marriage advice to be truly sure about tying the knot.<p><a href="http://www.yourtango.com/experts/scott-and-bethany-palmer-the-money-couple/3-signs-you-should-be-runaway-bride" target="_blank">read more</a></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 17:13:39',
            'feed_link' => 'http://www.yourtango.com/experts/scott-and-bethany-palmer-the-money-couple/3-signs-you-should-be-runaway-bride',
            'feed_id' => 3,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'finding-love-giveaway-great-advice-for-soulmate-searching',
            'name' => 'Finding Love Giveaway: Great Advice For Soulmate Searching',
            'annotation' => '                                                    On your search for true love, wouldn\'t it be nice to have a little encouragement now and then? Check out this relationship expert advice for finding your soulmate.read more',
            'content' => '<div>    <div>            <div>                    <img src="http://images.tangomag.com/sites/default/files/imagecache/tee-images/image_blog/156920343.jpg" alt="Finding Love Giveaway: Great Advice For Soulmate Searching" title="" class="imagecache imagecache-tee-images imagecache-default imagecache-tee-images_default" width="240" height="180" />        </div>        </div></div>On your search for true love, wouldn\'t it be nice to have a little encouragement now and then? Check out this relationship expert advice for finding your soulmate.<p><a href="http://www.yourtango.com/experts/coach-amy-schoen/finding-love-giveaway-great-advice-soulmate-searching" target="_blank">read more</a></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 17:13:39',
            'feed_link' => 'http://www.yourtango.com/experts/coach-amy-schoen/finding-love-giveaway-great-advice-soulmate-searching',
            'feed_id' => 3,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'midlife-marriage-6-ways-to-balance-you-me-amp-we',
            'name' => 'Midlife Marriage: 6 Ways To Balance You, Me &amp; We',
            'annotation' => '                                                    Dating and relationship coach for women over 40 Ronnie Ann Ryan talks about her own mid-life marriage — and the six ways she had to change to accommodate her new husband. If you\'re entering into a new relationship, learn how to balance your independence with your partner\'s needs.read more',
            'content' => '<div>    <div>            <div>                    <img src="http://images.tangomag.com/sites/default/files/imagecache/tee-images/image_blog/hiking_couple.jpg" alt="Relationship Coach: Dating Advice For Women Over 40" title="" class="imagecache imagecache-tee-images imagecache-default imagecache-tee-images_default" width="240" height="180" />        </div>        </div></div>Dating and relationship coach for women over 40 Ronnie Ann Ryan talks about her own mid-life marriage — and the six ways she had to change to accommodate her new husband. If you\'re entering into a new relationship, learn how to balance your independence with your partner\'s needs.<p><a href="http://www.yourtango.com/experts/coach-ronnie-ann-ryan/midlife-marriage-how-balance-you-and-me-and-we" target="_blank">read more</a></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 17:13:39',
            'feed_link' => 'http://www.yourtango.com/experts/coach-ronnie-ann-ryan/midlife-marriage-how-balance-you-and-me-and-we',
            'feed_id' => 3,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => 'online-dating',
            'name' => 'Знакомства онлайн',
            'annotation' => 'Современный темп жизни часто не оставляет времени на поиск партнера. Работа дома или в небольшом коллективе еще больше сужает возможный круг знакомств.  Иногда это становится серьезной проблемой, ведущей к депрессии и чувству одиночества. Знакомства онлайн – современный путь решения проблемы, каковы его преимущества и недостатки?',
            'content' => '<h2>Преимущества знакомств онлайн</h2><p>Современные технологии предлагают нам искать партнера в Интернете, учитывая самые разные особенности. Знакомства онлайн стали популярны не только среди молодежи, но и среди людей более старшего возраста. Некоторые сайты ориентированы на пользователей, ищущих краткосрочные отношения, другие, наоборот, предлагают свои услуги для желающих найти спутника жизни.</p><p><br />Знакомства онлайн &ndash; это простой и удобный способ встретить людей со схожими интересами, убеждениями и взглядами. Он так же не требует от вас выходить из дома после тяжелого рабочего дня. Искать свою любовь, уютно устроившись в любимом кресле &ndash; что может быть увлекательнее.</p><h2>Недостатки знакомств онлайн</h2><p>Знакомство в Интернете, предполагает не больше опасностей, чем знакомство за столиком в кафе. Кто-то хочет приукрасить свои достижения, кто-то скрыть свое положение, некоторым просто сложно открыться новому человеку. Отвечая на вопросы анкет, мы стремимся выставить себя в самом выгодном свете. Да и в реальной жизни желание казаться лучше никуда не пропадает.&nbsp;</p><h2>Знакомства онлайн и настоящее счастье</h2><p>Любые знакомства, онлайн в том числе, могут перерасти в серьезные отношения, если между партнерами пробежит та самая искра. Все зависит от вас, от того, что вы ищете, и о чем мечтаете. Попробовать в любом случае стоит, вы встретите новых знакомых и друзей по интересам, и кто знает, может быть онлайн знакомство перерастет в искреннюю, чистую и, самое главное, реальную любовь.</p><p><a href="http://www.edarling.ru/sovetchik/znakomstvo/znakomstva-onlain" rel="nofollow" target="_blank">Источник статьи</a></p>',
            'img' => 'dd4c6fc497.png',
            'status' => 1,
            'lang_code' => 'ru',
            'news_type' => 'news',
            'date_add' => '2016-04-25 12:45:54',
            'feed_link' => '',
            'feed_id' => 0,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
        [
            'gid' => '6-dating-gremlins-amp-goblins-to-conquer-this-halloween',
            'name' => '6 Dating Gremlins &amp; Goblins To Conquer This Halloween',
            'annotation' => '                                                    In the spirit of Halloween, this dating coach explains how your intimacy fears can act like spooky gremlins and goblins, keeping you from finding love. The bright side? You can control your inner thoughts and kill those pesky negative monsters! Take THAT, boogeyman!read more',
            'content' => '<div>    <div>            <div>                    <img src="http://images.tangomag.com/sites/default/files/imagecache/tee-images/image_blog/spooked.jpg" alt="Dating Coach: Overcome Dating Insecurities" title="" class="imagecache imagecache-tee-images imagecache-default imagecache-tee-images_default" width="240" height="180" />        </div>        </div></div>In the spirit of Halloween, this dating coach explains how your intimacy fears can act like spooky gremlins and goblins, keeping you from finding love. The bright side? You can control your inner thoughts and kill those pesky negative monsters! Take THAT, boogeyman!<p><a href="http://www.yourtango.com/experts/coach-amy-schoen/how-navigate-around-your-dating-fears-gremlins-and-goblin" target="_blank">read more</a></p>',
            'img' => '',
            'status' => 1,
            'lang_code' => 'en',
            'news_type' => 'feed',
            'date_add' => '2016-04-25 17:13:39',
            'feed_link' => 'http://www.yourtango.com/experts/coach-amy-schoen/how-navigate-around-your-dating-fears-gremlins-and-goblin',
            'feed_id' => 3,
            'feed_unique_id' => '',
            'video' => '',
            'video_image' => '',
            'video_data' => '',
            'set_to_subscribe' => 0,
            'comments_count' => 0,
        ],
    ],
    'feeds' => [
        [
            'link' => 'http://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml',
            'title' => 'BBC News - Entertainment &amp; Arts',
            'description' => 'The latest stories from the Entertainment & Arts section of the BBC News web site.',
            'site_link' => 'http://www.bbc.co.uk/news/entertainment_and_arts/#sa-ns_mchannel=rss&amp;ns_source=PublicRSS20-sa',
            'encoding' => 'UTF-8',
            'status' => '1',
            'lang_code' => 'en',
            'max_news' => '10',
        ],
        [
            'link' => 'http://www.vesti.ru/vesti.rss',
            'title' => 'ВЕСТИ',
            'description' => 'ВЕСТИ',
            'site_link' => 'http://www.vesti.ru',
            'encoding' => 'UTF-8',
            'status' => '1',
            'lang_code' => 'ru',
            'max_news' => '10',
        ],
    ],
];
