<?php

$install_lang["admin_menu_main_items"] = "主要";
$install_lang["admin_menu_main_items_admin-home-item"] = "主页";
$install_lang["admin_menu_main_items_admin-home-item_tooltip"] = "";
$install_lang["admin_menu_main_items_tooltip"] = "";
$install_lang["admin_menu_other_items"] = "模块";
$install_lang["admin_menu_other_items_add_ons_items"] = "模块";
$install_lang["admin_menu_other_items_add_ons_items_tooltip"] = "";
$install_lang["admin_menu_other_items_add_ons_items_admin-modules-item"] = "模块安装";
$install_lang["admin_menu_other_items_add_ons_items_admin-modules-item_tooltip"] = "";
$install_lang["admin_menu_other_items_tooltip"] = "";
$install_lang["admin_menu_settings_items"] = "设置";
$install_lang["admin_menu_settings_items_content_items"] = "内容";
$install_lang["admin_menu_settings_items_content_items_tooltip"] = "";
$install_lang["admin_menu_settings_items_interface-items"] = "界面";
$install_lang["admin_menu_settings_items_interface-items_tooltip"] = "";
$install_lang["admin_menu_settings_items_system-items"] = "系统";
$install_lang["admin_menu_settings_items_system-items_system-geolocation-item"] = "Geolocation"; // from en
$install_lang["admin_menu_settings_items_system-items_system-geolocation-item_tooltip"] = "Geolocation"; // from en
$install_lang["admin_menu_settings_items_system-items_system-numerics-item"] = "杂项设置";
$install_lang["admin_menu_settings_items_system-items_system-numerics-item_tooltip"] = "数值，模块设置";
$install_lang["admin_menu_settings_items_system-items_tooltip"] = "";
$install_lang["admin_menu_settings_items_tooltip"] = "";
$install_lang["admin_menu_system_items"] = "管理";
$install_lang["admin_menu_system_items_admin-home-item"] = "系统";
$install_lang["admin_menu_system_items_admin-home-item_tooltip"] = "";
$install_lang["admin_menu_system_items_admin-system-item"] = "管理";
$install_lang["admin_menu_system_items_admin-system-item_tooltip"] = "";
$install_lang["admin_menu_system_items_tooltip"] = "";
$install_lang["guest_main_menu_main-menu-home-item"] = "主页";
$install_lang["guest_main_menu_main-menu-home-item_tooltip"] = "";
$install_lang["settings_menu_settings-menu-home"] = "主页";
$install_lang["settings_menu_settings-menu-home_tooltip"] = "";
$install_lang["user_footer_menu_footer-menu-about-item"] = "关于";
$install_lang["user_footer_menu_footer-menu-about-item_tooltip"] = "";
$install_lang["user_footer_menu_footer-menu-help-item"] = "帮助";
$install_lang["user_footer_menu_footer-menu-help-item_tooltip"] = "";
$install_lang["user_footer_menu_footer-menu-links-item"] = "链接";
$install_lang["user_footer_menu_footer-menu-links-item_tooltip"] = "";
$install_lang["user_footer_menu_footer-menu-policy-item"] = "隐私政策";
$install_lang["user_footer_menu_footer-menu-policy-item_tooltip"] = "";
$install_lang["user_main_menu_user-main-home-item"] = "主页";
$install_lang["user_main_menu_user-main-home-item_tooltip"] = "";
$install_lang["user_top_menu_user-menu-activities"] = "活动";
$install_lang["user_top_menu_user-menu-activities_tooltip"] = "";
$install_lang["user_top_menu_user-menu-communication"] = "沟通";
$install_lang["user_top_menu_user-menu-communication_tooltip"] = "";
$install_lang["user_top_menu_user-menu-homepage"] = "Homepage"; // from en
$install_lang["user_top_menu_user-menu-homepage_tooltip"] = "";
$install_lang["user_top_menu_user-menu-people"] = "人们";
$install_lang["user_top_menu_user-menu-people_tooltip"] = "";

