<?php

$install_lang["add_funds_to_my_account"] = "充值到我的账户";
$install_lang["admin_header_numerics_change"] = "更改网站数值";
$install_lang["admin_header_settings_countries"] = "Countries format"; // from en
$install_lang["admin_header_settings_date_formats"] = "Date format"; // from en
$install_lang["admin_header_settings_numerics"] = "Pagination rules"; // from en
$install_lang["admin_header_settings_overview"] = "Numerics overview"; // from en
$install_lang["applications"] = "应用程序";
$install_lang["apply_job_items_per_page_field"] = "每页项";
$install_lang["apply_job_settings_module"] = "应用程序列表设置";
$install_lang["arrow_down"] = "&darr;";
$install_lang["arrow_up"] = "&uarr;";
$install_lang["available_browsers_text1"] = "您正在使用旧式浏览器版本";
$install_lang["available_browsers_text2"] = "为了获得更好的体验，请升级您的网页浏览器";
$install_lang["banners_button_custom"] = "GET FEATURE"; // from en
$install_lang["banners_button_design"] = "ORDER NOW"; // from en
$install_lang["banners_button_modules"] = "GET PACKAGE"; // from en
$install_lang["banners_button_packages"] = "GET PACKAGE"; // from en
$install_lang["banners_description_custom"] = "Order custom changes from the engineers who built your site!"; // from en
$install_lang["banners_description_design"] = "-Design integrations<br>-Logo design"; // from en
$install_lang["banners_description_modules"] = "Enhance your site with new special plugins and add-ons"; // from en
$install_lang["banners_description_packages"] = "Get everything you need to start a dating website"; // from en
$install_lang["banners_header_custom"] = "HAVE A FEATURE REQUEST?"; // from en
$install_lang["banners_header_design"] = "<div class='fleft'>MAKE YOUR SITE</div> <div class='inverted fleft'>UNIQUE</div>"; // from en
$install_lang["banners_header_modules"] = "PLUGINS & ADDONS"; // from en
$install_lang["banners_header_packages"] = "PACKAGES"; // from en
$install_lang["banners_items_per_page_field"] = "每页项";
$install_lang["banners_settings_module"] = "横幅设置";
$install_lang["btn_activate"] = "激活";
$install_lang["btn_add"] = "添加";
$install_lang["btn_add_to"] = "添加至";
$install_lang["btn_apply"] = "适用";
$install_lang["btn_approve"] = "批准";
$install_lang["btn_back"] = "返回";
$install_lang["btn_cancel"] = "取消";
$install_lang["btn_change"] = "更改";
$install_lang["btn_choose_file"] = "从电脑上传文件";
$install_lang["btn_clear"] = "重置";
$install_lang["btn_close"] = "关闭";
$install_lang["btn_create"] = "创建";
$install_lang["btn_decline"] = "拒绝";
$install_lang["btn_delete"] = "移除";
$install_lang["btn_done"] = "Done"; // from en
$install_lang["btn_edit"] = "编辑";
$install_lang["btn_login"] = "登陆";
$install_lang["btn_logoff"] = "退出";
$install_lang["btn_logout"] = "退出";
$install_lang["btn_ok"] = "好的";
$install_lang["btn_preview"] = "预览";
$install_lang["btn_refresh"] = "刷新";
$install_lang["btn_register"] = "注册";
$install_lang["btn_reply"] = "回复";
$install_lang["btn_restore"] = "修复";
$install_lang["btn_save"] = "保存";
$install_lang["btn_saving"] = "保存中...";
$install_lang["btn_search"] = "搜索";
$install_lang["btn_send"] = "发送";
$install_lang["btn_show"] = "显示";
$install_lang["btn_support"] = "支持";
$install_lang["btn_tableicon_is_active"] = "Active"; // from en
$install_lang["btn_tableicon_is_not_active"] = "Inactive"; // from en
$install_lang["btn_tableicon_no"] = "No"; // from en
$install_lang["btn_tableicon_yes"] = "Yes"; // from en
$install_lang["btn_upload"] = "上传";
$install_lang["btn_view_more"] = "查看更多";
$install_lang["change_my_pass"] = "更改密码";
$install_lang["contact_admin"] = "联系管理员";
$install_lang["content_removed"] = "Content has been removed"; // from en
$install_lang["copyright"] = "&copy;&nbsp;2016&nbsp;<a href=\"http://www.pilotgroup.net/\">Pilot Group Ltd</a>, 保留所有权利";
$install_lang["countries_output_city_format_field"] = "城市输出格式";
$install_lang["countries_output_country_format_field"] = "国家输出格式";
$install_lang["countries_output_region_format_field"] = "区域输出格式";
$install_lang["countries_settings_module"] = "国家设置";
$install_lang["date_format_day"] = "日";
$install_lang["date_format_day_with_zero"] = "含0的数字";
$install_lang["date_format_day_without_zero"] = "不含0的数字";
$install_lang["date_format_hours"] = "小时";
$install_lang["date_format_hours_12_with_zero"] = "含0的12小时";
$install_lang["date_format_hours_12_without_zero"] = "不含0的12小时";
$install_lang["date_format_hours_24_with_zero"] = "含0的24小时";
$install_lang["date_format_hours_24_without_zero"] = "不含0的24小时";
$install_lang["date_format_minutes"] = "分钟";
$install_lang["date_format_minutes_with_zero"] = "含0的数字";
$install_lang["date_format_minutes_without_zero"] = "不含0的数字";
$install_lang["date_format_month"] = "月";
$install_lang["date_format_month_full"] = "全称";
$install_lang["date_format_month_short"] = "简称";
$install_lang["date_format_month_with_zero"] = "含0的数字";
$install_lang["date_format_month_without_zero"] = "不含0的数字";
$install_lang["date_format_seconds"] = "秒钟";
$install_lang["date_format_seconds_with_zero"] = "含0的数字";
$install_lang["date_format_seconds_without_zero"] = "不含0的数字";
$install_lang["date_format_week_day"] = "一周的每一天";
$install_lang["date_format_week_day_full"] = "长";
$install_lang["date_format_week_day_short"] = "短";
$install_lang["date_format_year"] = "年";
$install_lang["date_format_year_2"] = "两位数";
$install_lang["date_format_year_4"] = "四位数";
$install_lang["date_formats_date_literal_description"] = "主要在用户模式下";
$install_lang["date_formats_date_literal_field"] = "日期文本";
$install_lang["date_formats_date_numeric_description"] = "无处";
$install_lang["date_formats_date_numeric_field"] = "日期值";
$install_lang["date_formats_date_time_literal_description"] = "主要在管理员模式下";
$install_lang["date_formats_date_time_literal_field"] = "日期时间文本";
$install_lang["date_formats_date_time_numeric_description"] = "管理员模式";
$install_lang["date_formats_date_time_numeric_field"] = "日期时间值";
$install_lang["date_formats_settings_module"] = "日期格式";
$install_lang["date_formats_time_literal_description"] = "无处";
$install_lang["date_formats_time_literal_field"] = "时间文本";
$install_lang["date_formats_time_numeric_description"] = "无处";
$install_lang["date_formats_time_numeric_field"] = "时间值";
$install_lang["date_formats_used_in"] = "被用于";
$install_lang["donate"] = "Donations"; // from en
$install_lang["donate_amount"] = "Amount"; // from en
$install_lang["donate_approve"] = "Approve"; // from en
$install_lang["donate_approved"] = "Approved"; // from en
$install_lang["donate_comment"] = "Comment"; // from en
$install_lang["donate_decline"] = "Decline"; // from en
$install_lang["donate_declined"] = "Declined"; // from en
$install_lang["donate_declined_by_me"] = "Declined by me"; // from en
$install_lang["donate_declined_by_sender"] = "Declined by sender"; // from en
$install_lang["donate_declined_by_user"] = "Declined by user"; // from en
$install_lang["donate_no_data"] = "No transactions"; // from en
$install_lang["donate_status"] = "Status"; // from en
$install_lang["donate_waiting"] = "Waiting"; // from en
$install_lang["edit_my_profile"] = "编辑资料";
$install_lang["error_date_format_empty"] = "Empty date format"; // from en
$install_lang["error_demo_mode"] = "出于安全原因，某些功能在线上演示时被禁用。<br>服务器试用版可用于测试。 <a href='http://www.datingpro.com/contact/'>联系我们</a> 获取更多详细信息。";
$install_lang["error_numerics_empty"] = "空值: [field]";
$install_lang["error_output_city_format_empty"] = "Empty output city format"; // from en
$install_lang["error_output_country_format_empty"] = "Empty output country format"; // from en
$install_lang["error_output_region_format_empty"] = "Empty output region format"; // from en
$install_lang["error_product_key_incorrect"] = "错误或空白的缩略图键";
$install_lang["example"] = "实例";
$install_lang["features_chats"] = "Text and video chats"; // from en
$install_lang["features_chats_txt"] = "See someone you like? Send a wink or a virtual gift, add them to your List of Favourites. Use Instant Messenger or a video chat to learn more about each other!"; // from en
$install_lang["features_likeme"] = "LikeMe"; // from en
$install_lang["features_likeme_txt"] = "LikeMe feature lets you like or skip site members. In case there's been a mutual 'like', you both can continue communication directly on the site."; // from en
$install_lang["features_nearest"] = "Nearest users"; // from en
$install_lang["features_nearest_txt"] = "Nearest users is a special search page with an interactive map. You can search by radius, and your own location will be the starting point. Exact location is not disclosed so it is perfectly safe."; // from en
$install_lang["fhf_back_link"] = "Return to homepage"; // from en
$install_lang["fhf_text"] = "The page you were looking for does not exist. You may have mistyped the address or the page may have moved."; // from en
$install_lang["fhf_title"] = "Not found"; // from en
$install_lang["field_login"] = "登陆";
$install_lang["field_order_key"] = "缩略图键";
$install_lang["field_password"] = "密码";
$install_lang["field_placeholder"] = "Start typing..."; // from en
$install_lang["filter_header"] = "过滤器";
$install_lang["from_last_week"] = "since last week"; // from en
$install_lang["geolocation_onoff"] = "Establish the coordinates of users"; // from en
$install_lang["header_actions"] = "动作";
$install_lang["header_admin_homepage"] = "欢迎 | 管理之家";
$install_lang["header_donate_view_block"] = "My transactions"; // from en
$install_lang["header_error"] = "404页面未找到";
$install_lang["header_filters"] = "Filters"; // from en
$install_lang["header_homepage"] = "我的主页";
$install_lang["header_inline_lang_edit"] = "翻译";
$install_lang["header_modinstaller_login"] = "登陆至模块管理";
$install_lang["header_my_statistics"] = "我的统计";
$install_lang["header_settings_geolocation"] = "Geolocation settings"; // from en
$install_lang["header_settings_numerics_list"] = "数值";
$install_lang["header_start_page"] = "主页";
$install_lang["lang_editor"] = "语言文本编辑器";
$install_lang["latest_added_ads_header"] = "最新添加";
$install_lang["link_details"] = "Details"; // from en
$install_lang["link_less_options"] = "更少选项";
$install_lang["link_more_options"] = "更多选项";
$install_lang["mailbox_attach_limit_field"] = "附件限制";
$install_lang["mailbox_items_per_page_field"] = "每页项";
$install_lang["mailbox_settings_module"] = "邮箱设置";
$install_lang["make_active"] = "激活";
$install_lang["make_inactive"] = "停用";
$install_lang["max"] = "最大";
$install_lang["max_photo_hint"] = "最大值";
$install_lang["media_items_per_page_field"] = "每页项";
$install_lang["media_settings_module"] = "媒体设置";
$install_lang["min"] = "最小";
$install_lang["mobile_app_title"] = "Mobile applications"; // from en
$install_lang["mobile_app_txt"] = "Access our site from your mobile device and always keep in touch, even on the go."; // from en
$install_lang["mod_installer_admin_login_text"] = "想要进入模块管理模板，请登陆。<br>您将在文件中找到登陆和密码信息 <b>应用程序/配置/安装脚本</b>";
$install_lang["multiselect_all_text"] = "选定的全部选项";
$install_lang["multiselect_change"] = "编辑";
$install_lang["multiselect_of"] = "的";
$install_lang["multiselect_please_select"] = "请选择至少一个选项";
$install_lang["multiselect_select_all"] = "全选";
$install_lang["multiselect_selected"] = "已选";
$install_lang["my_contacts"] = "我的联系人";
$install_lang["nav_first"] = "第一个";
$install_lang["nav_last"] = "最后一个";
$install_lang["nav_next"] = "下一个";
$install_lang["nav_prev"] = "上一个";
$install_lang["nav_user_first"] = "‹ 第一个";
$install_lang["nav_user_last"] = "最后一个 ›";
$install_lang["nav_user_next"] = "›";
$install_lang["nav_user_prev"] = "‹";
$install_lang["new_messages"] = "新的消息";
$install_lang["news_settings_module"] = "新闻设置";
$install_lang["news_userside_items_per_page_field"] = "每页新闻";
$install_lang["no_information"] = "无信息";
$install_lang["no_objects_select"] = "Please select at least one item"; // from en
$install_lang["no_str"] = "无";
$install_lang["not_found"] = "Not Found"; // from en
$install_lang["note_types_translate"] = "翻译文本";
$install_lang["notify_stick"] = "Stick"; // from en
$install_lang["option_checkbox_no"] = "不是";
$install_lang["option_checkbox_yes"] = "是的";
$install_lang["or"] = "或";
$install_lang["others_languages"] = "Other languages"; // from en
$install_lang["overflow_settings_module"] = "溢出";
$install_lang["page_not_found"] = "The page you were looking for does not exist. You may have mistyped the address or the page may have moved."; // from en
$install_lang["payments_items_per_page_field"] = "每页的付款统计条目";
$install_lang["payments_settings_module"] = "付款设置";
$install_lang["return_home"] = "Go to homepage"; // from en
$install_lang["saved_searches"] = "已保存的搜索";
$install_lang["search_all_column"] = "Search all columns"; // from en
$install_lang["search_people"] = "搜索用户";
$install_lang["select_all"] = "检查全部";
$install_lang["select_default"] = "请选择";
$install_lang["seo_tags_homepage_header"] = "主页";
$install_lang["seo_tags_homepage_title"] = "Dating Pro : 网站首页";
$install_lang["seo_tags_index_title"] = "Dating Pro : 索引页面";
$install_lang["sett_apply_job_item"] = "应用程序";
$install_lang["sett_banners_item"] = "横幅";
$install_lang["sett_countries_item"] = "国家";
$install_lang["sett_date_formats_item"] = "数据格式";
$install_lang["sett_im_item"] = "IM";
$install_lang["sett_mailbox_item"] = "邮箱";
$install_lang["sett_media_item"] = "媒体";
$install_lang["sett_news_item"] = "新闻";
$install_lang["sett_numerics_item"] = "标页码";
$install_lang["sett_overview_item"] = "概览";
$install_lang["sett_payments_item"] = "付款";
$install_lang["sett_start_item"] = "默认值";
$install_lang["sett_wall_events_item"] = "墙";
$install_lang["showing"] = "显示";
$install_lang["sort_by"] = "排序方式";
$install_lang["start_admin_items_per_page_field"] = "管理员模式下的每页项目数量";
$install_lang["start_index_items_per_page_field"] = "用户模式下的每页项目数量";
$install_lang["start_settings_module"] = "默认值";
$install_lang["stat_payments"] = "Earnings per week"; // from en
$install_lang["stat_payments_all"] = "Total earnings"; // from en
$install_lang["stat_payments_avg"] = "Average spend"; // from en
$install_lang["stat_profile_viewed"] = "Profile views"; // from en
$install_lang["stat_registered"] = "New registrations per week"; // from en
$install_lang["success_date_format_update"] = "Date format is successfully updated"; // from en
$install_lang["success_update_numerics_data"] = "数值设置更新成功";
$install_lang["system_version"] = "系统版本";
$install_lang["system_version_available"] = "<a href=\"http://www.datingpro.com/blog/meet-the-new-version-of-pg-dating-pro-software-2016-8-honey/\">Update your site now to version [version]</a>";
$install_lang["template"] = "Template"; // from en
$install_lang["text_error"] = "您请求的页面无法找到";
$install_lang["text_of"] = "的";
$install_lang["text_pages"] = "页面";
$install_lang["text_promo"] = "Find your match"; // from en
$install_lang["text_promo_description"] = "Create a simple profile, post your photos, and soon you'll be networking with our incredible singles. Online dating couldn't be easier!"; // from en
$install_lang["text_promo_second"] = "Are you looking for love, a new friend or a perfect companion? Our site is the place for people who are interested in a true relationship!"; // from en
$install_lang["text_social_promo"] = "SocialBiz is a social network that connects you with the people around you."; // from en
$install_lang["text_status"] = "Status"; // from en
$install_lang["today_on_site"] = "今日站点";
$install_lang["total"] = "总数";
$install_lang["unselect_all"] = "全部取消勾选";
$install_lang["update"] = "更新";
$install_lang["use_last_search"] = "使用最近搜索";
$install_lang["users_items_per_page_field"] = "每页用户";
$install_lang["users_settings_module"] = "用户设置";
$install_lang["view"] = "查看";
$install_lang["view_all"] = "查看全部";
$install_lang["wall_events_events_max_count_field"] = "Max number of wall events"; // from en
$install_lang["wall_events_items_per_page_field"] = "每页事件";
$install_lang["wall_events_live_period_field"] = "Wall events activity period (days, 0 = unlimited)"; // from en
$install_lang["wall_events_settings_module"] = "墙事件设置";
$install_lang["yes_str"] = "是的";

