<?php

$install_lang["block_active_users"] = "Latest active users";
$install_lang["block_auth_links"] = "Auth links";
$install_lang["block_featured_users"] = "Featured users";
$install_lang["block_lang_select"] = "Lang select";
$install_lang["block_new_users"] = "New users";
$install_lang["block_registration_login_form"] = "Registration / Login form";
$install_lang["param_active_users_count"] = "Count";
$install_lang["param_active_users_title"] = "Title";
$install_lang["param_active_users_user_type"] = "User type ID (0 = all)";
$install_lang["param_auth_links_right_align"] = "Right align";
$install_lang["param_featured_users_count"] = "Count";
$install_lang["param_featured_users_title"] = "Title";
$install_lang["param_featured_users_user_type"] = "User type ID (0 = all)";
$install_lang["param_lang_select_right_align"] = "Right align";
$install_lang["param_new_users_count"] = "Count";
$install_lang["param_new_users_title"] = "Title";
$install_lang["param_new_users_user_type"] = "User type ID (0 = all)";
$install_lang["view_active_users_big_thumbs"] = "Big thumbs";
$install_lang["view_active_users_carousel"] = "Carousel";
$install_lang["view_active_users_carousel_w_descr"] = "Carousel with description";
$install_lang["view_active_users_medium_thumbs"] = "Medium thumbs";
$install_lang["view_active_users_small_thumbs"] = "Small thumbs";
$install_lang["view_active_users_small_thumbs_w_descr"] = "Small thumbs with description";
$install_lang["view_auth_links_default"] = "Default";
$install_lang["view_featured_users_big_thumbs"] = "Big thumbs";
$install_lang["view_featured_users_carousel"] = "Carousel";
$install_lang["view_featured_users_carousel_w_descr"] = "Carousel with description";
$install_lang["view_featured_users_medium_thumbs"] = "Medium thumbs";
$install_lang["view_featured_users_small_thumbs"] = "Small thumbs";
$install_lang["view_featured_users_small_thumbs_w_descr"] = "Small thumbs with description";
$install_lang["view_lang_select_default"] = "Default";
$install_lang["view_new_users_big_thumbs"] = "Big thumbs";
$install_lang["view_new_users_carousel"] = "Carousel";
$install_lang["view_new_users_carousel_w_descr"] = "Carousel with description";
$install_lang["view_new_users_medium_thumbs"] = "Medium thumbs";
$install_lang["view_new_users_small_thumbs"] = "Small thumbs";
$install_lang["view_new_users_small_thumbs_w_descr"] = "Small thumbs with description";
$install_lang["view_registration_login_form_login_form"] = "Login form";
$install_lang["view_registration_login_form_registration_form"] = "Registration form";

