<?php

$install_lang["admin_header_configuration"] = "Настройки";
$install_lang["admin_header_preview"] = "Предпросмотр";
$install_lang["admin_header_widget_code"] = "Скопируйте и вставьте код на веб-сайт";
$install_lang["admin_header_widget_edit"] = "Редактирование виджета";
$install_lang["admin_header_widgets_install"] = "Установить";
$install_lang["admin_header_widgets_list"] = "Виджеты";
$install_lang["btn_get_code"] = "Получить код";
$install_lang["colors_background"] = "фон";
$install_lang["colors_block"] = "копирайт";
$install_lang["colors_border"] = "граница";
$install_lang["colors_header"] = "заголовок";
$install_lang["colors_link"] = "ссылка";
$install_lang["colors_text"] = "текст";
$install_lang["error_module_install"] = "Модуль не установлен";
$install_lang["error_widget_invalid"] = "Виджет не найден";
$install_lang["field_module"] = "Объект";
$install_lang["field_name"] = "Название";
$install_lang["field_widget_colors"] = "Цвета";
$install_lang["field_widget_footer"] = "Копирайт";
$install_lang["field_widget_size"] = "Размер";
$install_lang["field_widget_title"] = "Заголовок";
$install_lang["link_delete_widget"] = "Удалить виджет";
$install_lang["link_edit_widget"] = "Изменить виджет";
$install_lang["link_install_widget"] = "Установить";
$install_lang["no_widgets"] = "Нет виджетов";
$install_lang["no_widgets_install"] = "Нет виджетов. <a href=\"http://pilotgroup.zendesk.com/tickets/new/\">Подробнее</a>";
$install_lang["note_delete_widget"] = "Вы хотите удалить виджет?";
$install_lang["success_widget_delete"] = "Виджет успешно удален";
$install_lang["success_widget_install"] = "Виджет успешно установлен";
$install_lang["success_widget_update"] = "Виджет успешно изменен";
