DROP TABLE IF EXISTS `[prefix]statistics_payments`;
CREATE TABLE IF NOT EXISTS `[prefix]statistics_payments` (
  `object_id` int(3) NOT NULL,
  `amount_count` decimal(16,2) NOT NULL,
  `amount_day_1` decimal(16,2) NOT NULL,
  `amount_day_2` decimal(16,2) NOT NULL,
  `amount_day_3` decimal(16,2) NOT NULL,
  `amount_day_4` decimal(16,2) NOT NULL,
  `amount_day_5` decimal(16,2) NOT NULL,
  `amount_day_6` decimal(16,2) NOT NULL,
  `amount_day_7` decimal(16,2) NOT NULL,
  `amount_day_8` decimal(16,2) NOT NULL,
  `amount_day_9` decimal(16,2) NOT NULL,
  `amount_day_10` decimal(16,2) NOT NULL,
  `amount_day_11` decimal(16,2) NOT NULL,
  `amount_day_12` decimal(16,2) NOT NULL,
  `amount_day_13` decimal(16,2) NOT NULL,
  `amount_day_14` decimal(16,2) NOT NULL,
  `amount_total` decimal(16,2) NOT NULL,
  `transactions_count` decimal(16,2) NOT NULL,
  `transactions_day_1` decimal(16,2) NOT NULL,
  `transactions_day_2` decimal(16,2) NOT NULL,
  `transactions_day_3` decimal(16,2) NOT NULL,
  `transactions_day_4` decimal(16,2) NOT NULL,
  `transactions_day_5` decimal(16,2) NOT NULL,
  `transactions_day_6` decimal(16,2) NOT NULL,
  `transactions_day_7` decimal(16,2) NOT NULL,
  `transactions_day_8` decimal(16,2) NOT NULL,
  `transactions_day_9` decimal(16,2) NOT NULL,
  `transactions_day_10` decimal(16,2) NOT NULL,
  `transactions_day_11` decimal(16,2) NOT NULL,
  `transactions_day_12` decimal(16,2) NOT NULL,
  `transactions_day_13` decimal(16,2) NOT NULL,
  `transactions_day_14` decimal(16,2) NOT NULL,
  `transactions_total` decimal(16,2) NOT NULL,
  UNIQUE `object_id` (`object_id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8;

