<?php

$install_lang["admin_header_kisses_change"] = "Editing kisses";
$install_lang["admin_header_kisses_list"] = "Kisses list";
$install_lang["admin_header_kisses_settings"] = "Settings";
$install_lang["admin_system_settings_page"] = "Use default system settings";
$install_lang["btn_add"] = "Add new";
$install_lang["btn_close"] = "Close";
$install_lang["btn_confirm"] = "Confirm";
$install_lang["btn_link_delete"] = "Delete selected";
$install_lang["btn_select_all"] = "Select all";
$install_lang["btn_unselect_all"] = "Unselect all";
$install_lang["drag_files"] = "Drag and drop files here";
$install_lang["error_admin_items_per_page"] = "Invalid value of items per page in admin mode"; // from dev
$install_lang["error_empty_kiss_id"] = "Please select a kiss";
$install_lang["error_empty_kisses_name"] = "Please enter the name";
$install_lang["error_empty_record"] = "Please select a kiss";
$install_lang["error_invalid_file_type"] = "Invalid file type";
$install_lang["error_invalid_user_to"] = "Please try again";
$install_lang["error_items_per_page"] = "Invalid values of items per page in user mode"; // from dev
$install_lang["error_number_max_symbols"] = "Invalid values of  max symbols"; // from dev
$install_lang["error_send_kiss"] = "Something went wrong, please try again later";
$install_lang["field_date_created"] = "Date created";
$install_lang["field_name"] = "Kiss name";
$install_lang["header_new_kisses"] = "New kisses";
$install_lang["image"] = "Image";
$install_lang["images"] = "Images";
$install_lang["inbox"] = "Kisses sent to me";
$install_lang["kiss"] = "Send a kiss";
$install_lang["kisses"] = "Kisses";
$install_lang["kisses_annotation"] = "Select a kiss from the list below and write your message";
$install_lang["kisses_form_title"] = "Kisses list";
$install_lang["link_delete_selected"] = "Delete selected";
$install_lang["link_save_sorter"] = "Save sequence";
$install_lang["max"] = "Max";
$install_lang["message"] = "Message";
$install_lang["no_kisses"] = "No kisses yet";
$install_lang["no_select_kisses"] = "Please select kisses";
$install_lang["note_delete_kisses"] = "Are you sure you would like to delete selected kisses?";
$install_lang["number_max_symbols"] = "Maximum number of characters";
$install_lang["outbox"] = "Kisses sent from me";
$install_lang["settings_admin_items_per_page"] = "Items per page in admin mode";
$install_lang["settings_users_items_per_page"] = "Items per page in user mode";
$install_lang["sort_order"] = "Sort order";
$install_lang["success_delete_kisses"] = "Selected kisses have been successfully deleted";
$install_lang["success_send_kiss"] = "Kiss sent";
$install_lang["success_update_kisses"] = "Kiss successfully updated";
