<?php

$install_lang["admin_header_geomap_change"] = "Изменить ключ карты";
$install_lang["admin_header_geomap_edit"] = "Настройки карты";
$install_lang["admin_header_geomap_settings_change"] = "Редактировать настройки карты";
$install_lang["admin_header_geomap_settings_edit"] = "Настройки карты";
$install_lang["admin_header_list"] = "Геокарты";
$install_lang["driver_info"] = "Подробности";
$install_lang["driver_key_notrequired"] = "Ключ не требуется";
$install_lang["driver_name_bingmapsv7"] = "Карты Bing (API v7)";
$install_lang["driver_name_googlemaps"] = "Карты Google (API v2)";
$install_lang["driver_name_googlemapsv3"] = "Карты Google (API v3)";
$install_lang["driver_name_yandexmaps"] = "Карты Yandex (API v1)";
$install_lang["driver_name_yandexmapsv2"] = "Карты Yandex (API v2)";
$install_lang["driver_registration"] = "Получить ключ";
$install_lang["error_cant_save_settings"] = "Не получается сохранить изменения";
$install_lang["field_amenities"] = "Инфраструктура";
$install_lang["field_default_lat"] = "Широта по умолчанию";
$install_lang["field_default_lon"] = "Долгота по умолчанию";
$install_lang["field_default_zoom"] = "Масштаб по умолчанию";
$install_lang["field_driver"] = "Тип карты";
$install_lang["field_link"] = "Авторизация";
$install_lang["field_map_gid"] = "GID карты";
$install_lang["field_marker_icon"] = "Иконка";
$install_lang["field_marker_icon_delete"] = "Удалить";
$install_lang["field_regkey"] = "Ключ";
$install_lang["field_show_details"] = "Показать объект подробно";
$install_lang["field_status"] = "Используется";
$install_lang["field_title"] = "Название";
$install_lang["field_use_amenities"] = "Использовать инфраструктуру";
$install_lang["field_use_click_zoom"] = "Использовать масштабирование по клику";
$install_lang["field_use_clusterer"] = "Использовать кластеризатор геообъектов";
$install_lang["field_use_panorama"] = "Использовать панораму";
$install_lang["field_use_router"] = "Использовать маршруты";
$install_lang["field_use_search_auto"] = "Использовать автозаполнение в поиске";
$install_lang["field_use_search_radius"] = "Использовать радиус поиска";
$install_lang["field_use_searchbox"] = "Использовать поле поиска";
$install_lang["field_use_show_details"] = "Подробнее";
$install_lang["field_use_smart_zoom"] = "Использовать умный масштаб";
$install_lang["field_use_tools"] = "Использовать панель инструментов";
$install_lang["field_use_type_selector"] = "Использовать селектор типа";
$install_lang["field_view_type"] = "Вид по умолчанию";
$install_lang["header_amenity_select"] = "Выбор заведений";
$install_lang["link_activate_geomap"] = "Активировать";
$install_lang["link_active_geomap"] = "Активно";
$install_lang["link_edit_driver"] = "Редактировать";
$install_lang["link_reset_all"] = "Сбросить настройки";
$install_lang["link_select_amenities"] = "Выбрать заведения";
$install_lang["link_select_amenity"] = "Выбрать заведение";
$install_lang["link_settings_driver"] = "Редактировать настройки карты";
$install_lang["link_tableicon_edit_driver"] = "Ключ карты";
$install_lang["link_tableicon_settings_driver"] = "Настройка";
$install_lang["link_view_map"] = "Посмотреть на карте";
$install_lang["loading"] = "Загрузка...";
$install_lang["map_default"] = "Карта по умолчанию";
$install_lang["map_example"] = "Пример";
$install_lang["map_example_1_text"] = "<img src=\"/uploads/default/maps_example_1.jpeg\" align=\"left\" hspace=\"4\">\n<b>Лондон</b><br>\n<b>Тауэрский мост</b>, разводной мост в центре Лондона<br>\nнад рекой Темзой, недалеко от Лондонского Тауэра.";
$install_lang["map_example_2_text"] = "<img src=\"/uploads/default/maps_example_2.jpg\" align=\"left\" hspace=\"4\">\n<b>Франция</b><br>\n<b>Эйфелева башня</b>, самая узнаваемая архитектурная<br>\nдостопримечательность Парижа, всемирно известная как символ Франции.";
$install_lang["map_example_3_text"] = "<img src=\"/uploads/default/maps_example_3.jpg\" align=\"left\" hspace=\"4\">\n<b>Италия</b><br>\n<b>Пиза</b>, итальянский город и коммуна в регионе Тоскана.<br>\nНеофициальный символ города, Падающая башня...";
$install_lang["map_example_4_text"] = "<img src=\"/uploads/default/maps_example_4.jpeg\" align=\"left\" hspace=\"4\">\n<b>Замок Нойшванштайн</b>,<br>\nнем.: Schloss Neuschwanstein. Романтический замок баварского короля<br>\nЛюдвига II около городка Фюссен<br>\nв юго-западной Баварии.";
$install_lang["map_example_header"] = "Тур по Европе";
$install_lang["route_add"] = "Добавить маршрут";
$install_lang["route_delete"] = "Удалить маршрут";
$install_lang["set_general_settings_point_text"] = "<b>Перетащите флажок, чтобы установить пункт на карте по умолчанию</b>";
$install_lang["success_update_driver"] = "Ключ успешно сохранен";
$install_lang["success_update_driver_settings"] = "Настройки успешно обновлены";
$install_lang["text_availbale_select_amenities"] = "Можно выбрать";

