<?php

return array(
    'logo_block' => array(
        'gid'    => 'logo_block',
        'module' => 'themes',
        'model'  => 'Themes_model',
        'method' => '_dynamic_block_get_logo_block',
        'views'  => array(
            array(
                'gid' => 'default',
            ),
        ),
        'area' => array(
            array(
                'gid'        => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'sorter'     => '3',
                'cache_time' => '0',
                'x'          => '0',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
        ),
        'presets' => array(
            array(
                'gid_preset' => 'default',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '0',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '0',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '0',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'girls',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '30',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '4',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'girlfriends',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'jewish',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '70',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '8',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'lovers',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '70',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '8',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'neighbourhood',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'blackonwhite',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '0',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'deepblue',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '70',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '8',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'companions',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '70',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '8',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'community',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '70',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '8',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'christian',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '2',
                'x'          => '0',
                'y'          => '1',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'autumn_walk',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '3',
                'x'          => '0',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
            array(
                'gid_preset' => 'persimmon_red',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '50',
                'sorter'     => '3',
                'cache_time' => '0',
                'x'          => '0',
                'y'          => '2',
                'w'          => '6',
                'h'          => '1',
            ),
        ),
    ),
);
