<?php

return  array(
    'info_pages' => array(
        'gid'    => 'info_pages',
        'module' => 'content',
        'model'  => 'Content_model',
        'method' => '_dynamic_block_get_info_pages',
        'params' => array(
            'keyword' => array(
                'type'    => 'string',
                'default' => '',
                'gid'     => 'keyword',
            ),
            'transparent' => array(
                'type'    => 'checkbox',
                'default' => '1',
                'gid'     => 'transparent',
            ),
            'show_subsections' => array(
                'type'    => 'checkbox',
                'default' => '',
                'gid'     => 'show_subsections',
            ),
            'trim_subsections_text' => array(
                'type'    => 'checkbox',
                'default' => '1',
                'gid'     => 'trim_subsections_text',
            ),
        ),
        'views' => array(
            0 => array(
                'gid' => 'default',
            ),
        ),
        'area'    => array(),
        'presets' => array(
            0 => array(
                'gid_preset' => 'mediumturquoise',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:7:"keyword";s:8:"about_us";s:11:"transparent";s:1:"1";s:16:"show_subsections";s:1:"0";s:21:"trim_subsections_text";s:1:"0";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '14',
                'x'          => '0',
                'y'          => '10',
                'w'          => '6',
                'h'          => '1',
            ),
            1 => array(
                'gid_preset' => 'lavender',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:7:"keyword";s:8:"about_us";s:11:"transparent";s:1:"1";s:16:"show_subsections";s:1:"0";s:21:"trim_subsections_text";s:1:"0";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '14',
                'x'          => '0',
                'y'          => '10',
                'w'          => '6',
                'h'          => '1',
            ),
            2 => array(
                'gid_preset' => 'community',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:7:"keyword";s:8:"about_us";s:11:"transparent";s:1:"1";s:16:"show_subsections";s:1:"0";s:21:"trim_subsections_text";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '70',
                'cache_time' => '0',
                'sorter'     => '6',
                'x'          => '0',
                'y'          => '4',
                'w'          => '8',
                'h'          => '1',
            ),
            3 => array(
                'gid_preset' => 'christian',
                'gid_area'   => 'index-page',
                'params'     => 'a:4:{s:7:"keyword";s:8:"about_us";s:11:"transparent";s:1:"1";s:16:"show_subsections";s:1:"0";s:21:"trim_subsections_text";s:1:"1";}',
                'view_str'   => 'default',
                'width'      => '50',
                'cache_time' => '0',
                'sorter'     => '11',
                'x'          => '0',
                'y'          => '9',
                'w'          => '6',
                'h'          => '1',
            ),
        ),
    ),
    'content_promo' => array(
        'gid'    => 'content_promo',
        'module' => 'content',
        'model'  => 'Content_promo_model',
        'method' => '_dynamic_block_get_content_promo',
        'views'  => array(
            0 => array(
                'gid' => 'default',
            ),
        ),
        'area' => array(
            0 => array(
                'gid'        => 'girlfriends',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'sorter'     => '4',
                'cache_time' => '0',
                'x'          => '0',
                'y'          => '2',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
        'presets' => array(
            0 => array(
                'gid_preset' => 'girlfriends',
                'gid_area'   => 'index-page',
                'params'     => 'a:0:{}',
                'view_str'   => 'default',
                'width'      => '100',
                'cache_time' => '0',
                'sorter'     => '4',
                'x'          => '0',
                'y'          => '2',
                'w'          => '12',
                'h'          => '1',
            ),
        ),
    ),
);
