<?php

$install_lang["add_funds_to_my_account"] = "Legg til midler i min konto";
$install_lang["admin_header_numerics_change"] = "Endre sidenumerikk";
$install_lang["admin_header_settings_countries"] = "Land format";
$install_lang["admin_header_settings_date_formats"] = "Datoformat";
$install_lang["admin_header_settings_numerics"] = "Paginering";
$install_lang["admin_header_settings_overview"] = "Sidenumerikk overblikk";
$install_lang["applications"] = "Søknader";
$install_lang["apply_job_items_per_page_field"] = "Elementer per side";
$install_lang["apply_job_settings_module"] = "Innstillinger for liste over applikasjoner";
$install_lang["arrow_down"] = "&darr;";
$install_lang["arrow_up"] = "&darr;";
$install_lang["available_browsers_text1"] = "Du bruker en utdatert versjon av nettleseren.";
$install_lang["available_browsers_text2"] = "Vennligst oppgrader til en moderne nettleser for en bedre brukeropplevelse.";
$install_lang["banners_button_custom"] = "FÅ FUNKSJON";
$install_lang["banners_button_design"] = "BESTILL NÅ";
$install_lang["banners_button_modules"] = "FÅ PAKKE";
$install_lang["banners_button_packages"] = "FÅ PAKKE";
$install_lang["banners_description_custom"] = "Bestill tilpassede endringer fra ingeniørene som lagde din side!";
$install_lang["banners_description_design"] = "-Designintegrasjon<br>-Logodesign";
$install_lang["banners_description_modules"] = "Forbedre siden din med nye spesielle plugins og add-ons";
$install_lang["banners_description_packages"] = "Få alt du trenger for å starte en datingside";
$install_lang["banners_header_custom"] = "HAR DU EN FUNKSJONSFORESPØRSEL?";
$install_lang["banners_header_design"] = "<div class='fleft'>GJØR DIN SIDE</div> <div class='inverted fleft'>UNIK</div>";
$install_lang["banners_header_modules"] = "PLUGINS & ADDONS";
$install_lang["banners_header_packages"] = "PAKKER";
$install_lang["banners_items_per_page_field"] = "Elementer per side";
$install_lang["banners_settings_module"] = "Bannerinnstillinger";
$install_lang["btn_activate"] = "Aktiver";
$install_lang["btn_add"] = "Legg til";
$install_lang["btn_add_to"] = "Legg til i";
$install_lang["btn_apply"] = "Gjelder";
$install_lang["btn_approve"] = "Godkjenn";
$install_lang["btn_back"] = "Tilbake";
$install_lang["btn_cancel"] = "Avbryt";
$install_lang["btn_change"] = "Endre";
$install_lang["btn_choose_file"] = "Last opp fil fra datamaskinen";
$install_lang["btn_clear"] = "Resett";
$install_lang["btn_close"] = "Lukk";
$install_lang["btn_create"] = "Opprett";
$install_lang["btn_decline"] = "Avslå";
$install_lang["btn_delete"] = "Fjern";
$install_lang["btn_done"] = "Done"; // from en
$install_lang["btn_edit"] = "Rediger";
$install_lang["btn_login"] = "Logg inn";
$install_lang["btn_logoff"] = "Logg ut";
$install_lang["btn_logout"] = "Logg ut";
$install_lang["btn_ok"] = "OK";
$install_lang["btn_preview"] = "Forhåndsvis";
$install_lang["btn_refresh"] = "Oppdater";
$install_lang["btn_register"] = "Registrer";
$install_lang["btn_reply"] = "Svar";
$install_lang["btn_restore"] = "Gjenopprett";
$install_lang["btn_save"] = "Lagre";
$install_lang["btn_saving"] = "Lagrer...";
$install_lang["btn_search"] = "Søk";
$install_lang["btn_send"] = "Send";
$install_lang["btn_show"] = "Vis";
$install_lang["btn_support"] = "Support"; // from en
$install_lang["btn_tableicon_is_active"] = "Active"; // from en
$install_lang["btn_tableicon_is_not_active"] = "Inactive"; // from en
$install_lang["btn_tableicon_no"] = "No"; // from en
$install_lang["btn_tableicon_yes"] = "Yes"; // from en
$install_lang["btn_upload"] = "Last opp";
$install_lang["btn_view_more"] = "Se mer";
$install_lang["change_my_pass"] = "Endre passord";
$install_lang["contact_admin"] = "Kontakt admin";
$install_lang["content_removed"] = "Content has been removed"; // from en
$install_lang["copyright"] = "&copy;&nbsp;2016&nbsp;<a href=\"http://www.pilotgroup.net/\">Pilot Group Ltd</a>, Alle rettigheter reservert";
$install_lang["countries_output_city_format_field"] = "Utdataformat for by";
$install_lang["countries_output_country_format_field"] = "Utdataformat for land";
$install_lang["countries_output_region_format_field"] = "Utdataformat for region";
$install_lang["countries_settings_module"] = "Land innstillinger";
$install_lang["date_format_day"] = "Dag";
$install_lang["date_format_day_with_zero"] = "Tall med null";
$install_lang["date_format_day_without_zero"] = "Tall uten null";
$install_lang["date_format_hours"] = "Timer";
$install_lang["date_format_hours_12_with_zero"] = "12t med null";
$install_lang["date_format_hours_12_without_zero"] = "12t uten null";
$install_lang["date_format_hours_24_with_zero"] = "24t med null";
$install_lang["date_format_hours_24_without_zero"] = "24t uten null";
$install_lang["date_format_minutes"] = "Minutter";
$install_lang["date_format_minutes_with_zero"] = "Tall med null";
$install_lang["date_format_minutes_without_zero"] = "Tall uten null";
$install_lang["date_format_month"] = "Måned";
$install_lang["date_format_month_full"] = "Fult";
$install_lang["date_format_month_short"] = "Kort";
$install_lang["date_format_month_with_zero"] = "Tall med null";
$install_lang["date_format_month_without_zero"] = "Tall uten null";
$install_lang["date_format_seconds"] = "Sekunder";
$install_lang["date_format_seconds_with_zero"] = "Tall med null";
$install_lang["date_format_seconds_without_zero"] = "Tall uten null";
$install_lang["date_format_week_day"] = "Ukedag";
$install_lang["date_format_week_day_full"] = "Lang";
$install_lang["date_format_week_day_short"] = "Kort";
$install_lang["date_format_year"] = "r";
$install_lang["date_format_year_2"] = "To siffer";
$install_lang["date_format_year_4"] = "Fire siffer";
$install_lang["date_formats_date_literal_description"] = "hovedsaklig i brukermodus";
$install_lang["date_formats_date_literal_field"] = "Dato bokstavelig";
$install_lang["date_formats_date_numeric_description"] = "ingen steder";
$install_lang["date_formats_date_numeric_field"] = "Dato numerisk";
$install_lang["date_formats_date_time_literal_description"] = "hovedsaklig i adminmodus";
$install_lang["date_formats_date_time_literal_field"] = "Dato/tid bokstavelig";
$install_lang["date_formats_date_time_numeric_description"] = "adminmodus";
$install_lang["date_formats_date_time_numeric_field"] = "Dato/tid numerisk";
$install_lang["date_formats_settings_module"] = "Datoformat";
$install_lang["date_formats_time_literal_description"] = "ingen steder";
$install_lang["date_formats_time_literal_field"] = "Tid bokstavelig";
$install_lang["date_formats_time_numeric_description"] = "ingen steder";
$install_lang["date_formats_time_numeric_field"] = "Tid numerisk";
$install_lang["date_formats_used_in"] = "Brukt i";
$install_lang["donate"] = "Donations"; // from en
$install_lang["donate_amount"] = "Amount"; // from en
$install_lang["donate_approve"] = "Approve"; // from en
$install_lang["donate_approved"] = "Approved"; // from en
$install_lang["donate_comment"] = "Comment"; // from en
$install_lang["donate_decline"] = "Decline"; // from en
$install_lang["donate_declined"] = "Declined"; // from en
$install_lang["donate_declined_by_me"] = "Declined by me"; // from en
$install_lang["donate_declined_by_sender"] = "Declined by sender"; // from en
$install_lang["donate_declined_by_user"] = "Declined by user"; // from en
$install_lang["donate_no_data"] = "No transactions"; // from en
$install_lang["donate_status"] = "Status"; // from en
$install_lang["donate_waiting"] = "Waiting"; // from en
$install_lang["edit_my_profile"] = "Rediger profil";
$install_lang["error_date_format_empty"] = "Empty date format"; // from en
$install_lang["error_demo_mode"] = "Noen funksjoner er deaktivert i online demo for sikkerhetsårsaker.<br>Server prøveversjon er tilgjengelig for testing. <a href='http://www.datingpro.com/contact/'>Kontakt oss</a> for flere detaljer.";
$install_lang["error_numerics_empty"] = "Tom verdi: [field]";
$install_lang["error_output_city_format_empty"] = "Empty output city format"; // from en
$install_lang["error_output_country_format_empty"] = "Empty output country format"; // from en
$install_lang["error_output_region_format_empty"] = "Empty output region format"; // from en
$install_lang["error_product_key_incorrect"] = "Feil eller tom bestillingsnøkkel";
$install_lang["example"] = "Eksempel";
$install_lang["features_chats"] = "Text and video chats"; // from en
$install_lang["features_chats_txt"] = "See someone you like? Send a wink or a virtual gift, add them to your List of Favourites. Use Instant Messenger or a video chat to learn more about each other!"; // from en
$install_lang["features_likeme"] = "LikeMe"; // from en
$install_lang["features_likeme_txt"] = "LikeMe feature lets you like or skip site members. In case there's been a mutual 'like', you both can continue communication directly on the site."; // from en
$install_lang["features_nearest"] = "Nearest users"; // from en
$install_lang["features_nearest_txt"] = "Nearest users is a special search page with an interactive map. You can search by radius, and your own location will be the starting point. Exact location is not disclosed so it is perfectly safe."; // from en
$install_lang["fhf_back_link"] = "Return to homepage"; // from en
$install_lang["fhf_text"] = "The page you were looking for does not exist. You may have mistyped the address or the page may have moved."; // from en
$install_lang["fhf_title"] = "Not found"; // from en
$install_lang["field_login"] = "Innlogging";
$install_lang["field_order_key"] = "Bestillingsnøkkel";
$install_lang["field_password"] = "Passord";
$install_lang["field_placeholder"] = "Begynner å skrive...";
$install_lang["filter_header"] = "Filter";
$install_lang["from_last_week"] = "since last week"; // from en
$install_lang["geolocation_onoff"] = "Bestemme koordinatene til brukeren";
$install_lang["header_actions"] = "Handlinger";
$install_lang["header_admin_homepage"] = "Velkommen | Admin hjem";
$install_lang["header_donate_view_block"] = "My transactions";
$install_lang["header_error"] = "404 Side ikke funnet";
$install_lang["header_filters"] = "Filters";
$install_lang["header_homepage"] = "Min hjemmeside";
$install_lang["header_inline_lang_edit"] = "Oversett";
$install_lang["header_modinstaller_login"] = "Innlogging for moduladministrering";
$install_lang["header_my_statistics"] = "Mine statistikker";
$install_lang["header_settings_geolocation"] = "Innstillinger geolokasjon";
$install_lang["header_settings_numerics_list"] = "Numerikk";
$install_lang["header_start_page"] = "Startside";
$install_lang["lang_editor"] = "Språkredigering";
$install_lang["latest_added_ads_header"] = "Sist lagt til";
$install_lang["link_details"] = "Details";
$install_lang["link_less_options"] = "Færre valg";
$install_lang["link_more_options"] = "Flere valg";
$install_lang["mailbox_attach_limit_field"] = "Vedleggsbegrensning";
$install_lang["mailbox_items_per_page_field"] = "Elementer per side";
$install_lang["mailbox_settings_module"] = "Postkasseinnstillinger";
$install_lang["make_active"] = "Aktiver";
$install_lang["make_inactive"] = "Deaktiver";
$install_lang["max"] = "Maks";
$install_lang["max_photo_hint"] = "Maksimum";
$install_lang["media_items_per_page_field"] = "Elementer per side";
$install_lang["media_settings_module"] = "Mediainnstillinger";
$install_lang["min"] = "Min";
$install_lang["mobile_app_title"] = "Mobile applications"; // from en
$install_lang["mobile_app_txt"] = "Access our site from your mobile device and always keep in touch, even on the go."; // from en
$install_lang["mod_installer_admin_login_text"] = "For å komme til panelet for moduladministrering, vennligst logg inn. <br>Du finner innloggingsinformasjon og passord i filen <b>application/config/install.php</b>";
$install_lang["multiselect_all_text"] = "Alle valgmuligheter er valgt";
$install_lang["multiselect_change"] = "Rediger";
$install_lang["multiselect_of"] = "av";
$install_lang["multiselect_please_select"] = "Vennligst velg minst en valgmulighet";
$install_lang["multiselect_select_all"] = "Velg alle";
$install_lang["multiselect_selected"] = "valgte";
$install_lang["my_contacts"] = "Mine kontakter";
$install_lang["nav_first"] = "Først";
$install_lang["nav_last"] = "Sist";
$install_lang["nav_next"] = "Neste";
$install_lang["nav_prev"] = "Forrige";
$install_lang["nav_user_first"] = "‹ Først";
$install_lang["nav_user_last"] = "Sist ›";
$install_lang["nav_user_next"] = "›";
$install_lang["nav_user_prev"] = "‹";
$install_lang["new_messages"] = "Nye meldinger";
$install_lang["news_settings_module"] = "Nyhetsinnstillinger";
$install_lang["news_userside_items_per_page_field"] = "Nyheter per side";
$install_lang["no_information"] = "Ingen informasjon";
$install_lang["no_objects_select"] = "Vennligst velg minst en valgmulighet";
$install_lang["no_str"] = "Ingen";
$install_lang["not_found"] = "Ikke funnet";
$install_lang["note_types_translate"] = "Oversett tekst";
$install_lang["notify_stick"] = "Stick"; // from en
$install_lang["option_checkbox_no"] = "Nei";
$install_lang["option_checkbox_yes"] = "Ja";
$install_lang["or"] = "eller";
$install_lang["others_languages"] = "Other languages"; // from en
$install_lang["overflow_settings_module"] = "Overløp";
$install_lang["page_not_found"] = "Beklager, men vi kunne ikke finne siden du forespurte.";
$install_lang["payments_items_per_page_field"] = "Betalingsstatistikk innlegg per side";
$install_lang["payments_settings_module"] = "Betalingsinnstillinger";
$install_lang["return_home"] = "Gå til hjemmeside";
$install_lang["saved_searches"] = "Lagrede søk";
$install_lang["search_all_column"] = "Search all columns"; // from en
$install_lang["search_people"] = "Søk personer";
$install_lang["select_all"] = "Sjekk alle";
$install_lang["select_default"] = "Vennligst velg";
$install_lang["seo_tags_homepage_header"] = "Startside";
$install_lang["seo_tags_homepage_title"] = "Dating Pro : Startside";
$install_lang["seo_tags_index_title"] = "Dating Pro : Indeksside";
$install_lang["sett_apply_job_item"] = "Programmer";
$install_lang["sett_banners_item"] = "Bannere";
$install_lang["sett_countries_item"] = "Land innstillinger";
$install_lang["sett_date_formats_item"] = "Datoformat";
$install_lang["sett_im_item"] = "IM";
$install_lang["sett_mailbox_item"] = "Postkasse";
$install_lang["sett_media_item"] = "Media";
$install_lang["sett_news_item"] = "Nyheter";
$install_lang["sett_numerics_item"] = "Sidetall";
$install_lang["sett_overview_item"] = "Overblikk";
$install_lang["sett_payments_item"] = "Betalinger";
$install_lang["sett_start_item"] = "Standarder";
$install_lang["sett_wall_events_item"] = "Vegg";
$install_lang["showing"] = "Viser";
$install_lang["sort_by"] = "Sorter etter";
$install_lang["start_admin_items_per_page_field"] = "Antall elementer per side i adminmodus";
$install_lang["start_index_items_per_page_field"] = "Antall elementer per side i brukermodus";
$install_lang["start_settings_module"] = "Standarder";
$install_lang["stat_payments"] = "Earnings per week"; // from en
$install_lang["stat_payments_all"] = "Total earnings"; // from en
$install_lang["stat_payments_avg"] = "Average spend"; // from en
$install_lang["stat_profile_viewed"] = "Profile views"; // from en
$install_lang["stat_registered"] = "New registrations per week"; // from en
$install_lang["success_date_format_update"] = "Date format is successfully updated"; // from en
$install_lang["success_update_numerics_data"] = "Numeriske innstillinger er oppdatert";
$install_lang["system_version"] = "Systemversjon";
$install_lang["system_version_available"] = "<a href=\"http://www.datingpro.com/blog/meet-the-new-version-of-pg-dating-pro-software-2016-8-honey/\">Update your site now to version [version]</a>"; // from en
$install_lang["template"] = "Template";
$install_lang["text_error"] = "Kan ikke finne siden du forsøker å nå";
$install_lang["text_of"] = "av";
$install_lang["text_pages"] = "Side";
$install_lang["text_promo"] = "Find your match"; // from en
$install_lang["text_promo_description"] = "Create a simple profile, post your photos, and soon you'll be networking with our incredible singles. Online dating couldn't be easier!"; // from en
$install_lang["text_promo_second"] = "Are you looking for love, a new friend or a perfect companion? Our site is the place for people who are interested in a true relationship!"; // from en
$install_lang["text_social_promo"] = "SocialBiz is a social network that connects you with the people around you."; // from en
$install_lang["text_status"] = "Status";
$install_lang["today_on_site"] = "På siden i dag";
$install_lang["total"] = "Totalt";
$install_lang["unselect_all"] = "Avmarker alle";
$install_lang["update"] = "Oppdater";
$install_lang["use_last_search"] = "Bruk siste søk";
$install_lang["users_items_per_page_field"] = "Brukere per side";
$install_lang["users_settings_module"] = "Brukerenes innstillinger";
$install_lang["view"] = "Se";
$install_lang["view_all"] = "Se alle";
$install_lang["wall_events_events_max_count_field"] = "Maks antall vegg hendelser";
$install_lang["wall_events_items_per_page_field"] = "Hendelser per side";
$install_lang["wall_events_live_period_field"] = "Vegg hendelser aktivitet periode (dager, 0 = ubegrenset)";
$install_lang["wall_events_settings_module"] = "Vegg hendelser innstillinger";
$install_lang["yes_str"] = "Ja";

