<?php

$install_lang["add_funds_to_my_account"] = "Tilfør penge til min konto";
$install_lang["admin_header_numerics_change"] = "Ændre side nummering";
$install_lang["admin_header_settings_countries"] = "Countries format"; // from en
$install_lang["admin_header_settings_date_formats"] = "Date format"; // from en
$install_lang["admin_header_settings_numerics"] = "Pagination rules"; // from en
$install_lang["admin_header_settings_overview"] = "Numerics overview"; // from en
$install_lang["applications"] = "Applikationer";
$install_lang["apply_job_items_per_page_field"] = "Emner pr. side";
$install_lang["apply_job_settings_module"] = "Indstillinger for listen over programmer";
$install_lang["arrow_down"] = "&darr;";
$install_lang["arrow_up"] = "&uarr;";
$install_lang["available_browsers_text1"] = "Du bruger en forældet browser-version.";
$install_lang["available_browsers_text2"] = "Opgrader til den nyeste browserversion for en bedre oplevelse.";
$install_lang["banners_button_custom"] = "FÅ FEATURE";
$install_lang["banners_button_design"] = "BESTIL NU";
$install_lang["banners_button_modules"] = "FÅ PAKKEN";
$install_lang["banners_button_packages"] = "FÅ PAKKEN";
$install_lang["banners_description_custom"] = "Bestil brugerdefinerede ændringer fra de udviklere, der byggede dit site!";
$install_lang["banners_description_design"] = "-Design integrationer<br>-Logo design";
$install_lang["banners_description_modules"] = "Gør dit websted bedre med nye særlige plugins og addons";
$install_lang["banners_description_packages"] = "Få alt hvad du behøver for at starte en datingside";
$install_lang["banners_header_custom"] = "HAR DU ET FEATURE ØNSKE?";
$install_lang["banners_header_design"] = "GØR DIN SIDE UNIK";
$install_lang["banners_header_modules"] = "PLUGINS & ADDONS";
$install_lang["banners_header_packages"] = "PAKKER";
$install_lang["banners_items_per_page_field"] = "Emner pr. side";
$install_lang["banners_settings_module"] = "Banner indstillinger";
$install_lang["btn_activate"] = "Aktiver";
$install_lang["btn_add"] = "Tilføj";
$install_lang["btn_add_to"] = "Tilføj til";
$install_lang["btn_apply"] = "Anvend";
$install_lang["btn_approve"] = "Godkend";
$install_lang["btn_back"] = "Tilbage";
$install_lang["btn_cancel"] = "Annulér";
$install_lang["btn_change"] = "Ændre";
$install_lang["btn_choose_file"] = "Opload fil fra computer";
$install_lang["btn_clear"] = "Nulstil";
$install_lang["btn_close"] = "Luk";
$install_lang["btn_create"] = "Opret";
$install_lang["btn_decline"] = "Nedgang";
$install_lang["btn_delete"] = "Fjern";
$install_lang["btn_done"] = "Done"; // from en
$install_lang["btn_edit"] = "Rediger";
$install_lang["btn_login"] = "Log ind";
$install_lang["btn_logoff"] = "Log af";
$install_lang["btn_logout"] = "Log ud";
$install_lang["btn_ok"] = "OK";
$install_lang["btn_preview"] = "Smugkig";
$install_lang["btn_refresh"] = "Opdatér";
$install_lang["btn_register"] = "Registrer";
$install_lang["btn_reply"] = "Besvar";
$install_lang["btn_restore"] = "Genopret";
$install_lang["btn_save"] = "Gem";
$install_lang["btn_saving"] = "Gemmer...";
$install_lang["btn_search"] = "Søg";
$install_lang["btn_send"] = "Send";
$install_lang["btn_show"] = "Vis";
$install_lang["btn_support"] = "Kontakt os";
$install_lang["btn_tableicon_is_active"] = "Active"; // from en
$install_lang["btn_tableicon_is_not_active"] = "Inactive"; // from en
$install_lang["btn_tableicon_no"] = "No"; // from en
$install_lang["btn_tableicon_yes"] = "Yes"; // from en
$install_lang["btn_upload"] = "Opload";
$install_lang["btn_view_more"] = "Se mere";
$install_lang["change_my_pass"] = "Ændre password";
$install_lang["contact_admin"] = "Kontakt admin";
$install_lang["content_removed"] = "Content has been removed"; // from en
$install_lang["copyright"] = "&copy;&nbsp;2016&nbsp;<a href=\"http://www.pilotgroup.net/\">Pilot Group Ltd</a>, All Rights reserved";
$install_lang["countries_output_city_format_field"] = "By output format"; // from en
$install_lang["countries_output_country_format_field"] = "Land output format"; // from en
$install_lang["countries_output_region_format_field"] = "Region output format"; // from en
$install_lang["countries_settings_module"] = "Lande indstillinger";
$install_lang["date_format_day"] = "Dag";
$install_lang["date_format_day_with_zero"] = "Nummer med nul";
$install_lang["date_format_day_without_zero"] = "Nummer uden nul";
$install_lang["date_format_hours"] = "Timer";
$install_lang["date_format_hours_12_with_zero"] = "12h with zero"; // from en
$install_lang["date_format_hours_12_without_zero"] = "12h without zero"; // from en
$install_lang["date_format_hours_24_with_zero"] = "24h with zero"; // from en
$install_lang["date_format_hours_24_without_zero"] = "24h without zero"; // from en
$install_lang["date_format_minutes"] = "Minutter";
$install_lang["date_format_minutes_with_zero"] = "Number with zero"; // from en
$install_lang["date_format_minutes_without_zero"] = "Number without zero"; // from en
$install_lang["date_format_month"] = "Måned";
$install_lang["date_format_month_full"] = "Fuldt";
$install_lang["date_format_month_short"] = "Kort";
$install_lang["date_format_month_with_zero"] = "Number with zero"; // from en
$install_lang["date_format_month_without_zero"] = "Number without zero"; // from en
$install_lang["date_format_seconds"] = "Sekunder";
$install_lang["date_format_seconds_with_zero"] = "Number with zero"; // from en
$install_lang["date_format_seconds_without_zero"] = "Number without zero"; // from en
$install_lang["date_format_week_day"] = "Ugedagen";
$install_lang["date_format_week_day_full"] = "Lang";
$install_lang["date_format_week_day_short"] = "Kort";
$install_lang["date_format_year"] = "År";
$install_lang["date_format_year_2"] = "To decimaler";
$install_lang["date_format_year_4"] = "Fire decimaler";
$install_lang["date_formats_date_literal_description"] = "primært i brugertilstand";
$install_lang["date_formats_date_literal_field"] = "Eksakt dato";
$install_lang["date_formats_date_numeric_description"] = "ingensteder";
$install_lang["date_formats_date_numeric_field"] = "Dato numerisk";
$install_lang["date_formats_date_time_literal_description"] = "primært i admin tilstand";
$install_lang["date_formats_date_time_literal_field"] = "Eksakt dato og tid";
$install_lang["date_formats_date_time_numeric_description"] = "admin mode";
$install_lang["date_formats_date_time_numeric_field"] = "Dato/tid numerisk";
$install_lang["date_formats_settings_module"] = "Dato format";
$install_lang["date_formats_time_literal_description"] = "ingen steder";
$install_lang["date_formats_time_literal_field"] = "Tid literal";
$install_lang["date_formats_time_numeric_description"] = "ingen steder";
$install_lang["date_formats_time_numeric_field"] = "Tid numerisk";
$install_lang["date_formats_used_in"] = "Brugt i";
$install_lang["donate"] = "Donationer";
$install_lang["donate_amount"] = "Sum";
$install_lang["donate_approve"] = "Godkend";
$install_lang["donate_approved"] = "Godkendt";
$install_lang["donate_comment"] = "Kommentar";
$install_lang["donate_decline"] = "Afvis";
$install_lang["donate_declined"] = "Afvist";
$install_lang["donate_declined_by_me"] = "Afvist af mig";
$install_lang["donate_declined_by_sender"] = "Afvist af afsender";
$install_lang["donate_declined_by_user"] = "Afvist af bruger";
$install_lang["donate_no_data"] = "Ingen oversættelser";
$install_lang["donate_status"] = "Status";
$install_lang["donate_waiting"] = "Venter";
$install_lang["edit_my_profile"] = "Rediger profil";
$install_lang["error_date_format_empty"] = "Tomt dato format";
$install_lang["error_demo_mode"] = "Nogle funktioner er deaktiveret i online demo af sikkerhedsmæssige årsager. <br> Server prøveversion er tilgængelig til test. <a href=\"http://www.datingpro.com/contact/\"> Kontakt os </a> for flere detaljer.";
$install_lang["error_numerics_empty"] = "Tøm værdien: [field]";
$install_lang["error_output_city_format_empty"] = "Tomt output By-format";
$install_lang["error_output_country_format_empty"] = "Tomt output land-format";
$install_lang["error_output_region_format_empty"] = "Tomt output region-format";
$install_lang["error_product_key_incorrect"] = "Forkert eller tom ordre nøgle";
$install_lang["example"] = "Eksempel";
$install_lang["features_chats"] = "Tekst og video chats";
$install_lang["features_chats_txt"] = "Find nogen du kan lide? Send et kys eller en virtuel gave, føj dem til din liste over favoritter. Brug Instant Messenger eller en videochat til at lære mere om hinanden!";
$install_lang["features_likeme"] = "Like mig";
$install_lang["features_likeme_txt"] = "Med LikeMe funktionen kan du \"like\" eller springe forbi medlemmer. I tilfælde hvor der har været en gensidig 'like', kan begge kan fortsætte kommunikationen direkte på sitet.";
$install_lang["features_nearest"] = "Nærmeste brugere";
$install_lang["features_nearest_txt"] = "Nærmeste brugere er en speciel søgeside med et interaktivt kort. Du kan søge efter radius, og din egen placering vil være udgangspunktet. Præcis placering afsløres ikke, så sikkerheden er iorden.";
$install_lang["fhf_back_link"] = "Returnér til hjemmesiden";
$install_lang["fhf_text"] = "Den side, du søgte findes ikke. Du har måske skrevet forkert adresse eller siden kan være flyttet.";
$install_lang["fhf_title"] = "Ikke fundet";
$install_lang["field_login"] = "Log ind";
$install_lang["field_order_key"] = "Ordre nøgle";
$install_lang["field_password"] = "Password";
$install_lang["field_placeholder"] = "Start indtastning...";
$install_lang["filter_header"] = "Filter";
$install_lang["from_last_week"] = "since last week"; // from en
$install_lang["geolocation_onoff"] = "Etabler brugernes kordinater";
$install_lang["header_actions"] = "Handlinger";
$install_lang["header_admin_homepage"] = "Velkommen | Admin home";
$install_lang["header_donate_view_block"] = "Mine oversættelser";
$install_lang["header_error"] = "404 Siden blev ikke fundet";
$install_lang["header_filters"] = "Filters";
$install_lang["header_homepage"] = "Min hjemmeside";
$install_lang["header_inline_lang_edit"] = "Oversæt";
$install_lang["header_modinstaller_login"] = "Log ind i moduler management";
$install_lang["header_my_statistics"] = "Mine statistiker";
$install_lang["header_settings_geolocation"] = "Geolocation indstillinger";
$install_lang["header_settings_numerics_list"] = "Numerisk";
$install_lang["header_start_page"] = "Hjemmeside";
$install_lang["lang_editor"] = "Sprog editor";
$install_lang["latest_added_ads_header"] = "Sidst tilføjede";
$install_lang["link_details"] = "Details";
$install_lang["link_less_options"] = "Færre muligheder";
$install_lang["link_more_options"] = "Flere muligheder";
$install_lang["mailbox_attach_limit_field"] = "Vedhæft grænse";
$install_lang["mailbox_items_per_page_field"] = "Emner pr. side";
$install_lang["mailbox_settings_module"] = "Mailbox indstillinger";
$install_lang["make_active"] = "Aktiver";
$install_lang["make_inactive"] = "Deaktiver";
$install_lang["max"] = "Max";
$install_lang["max_photo_hint"] = "Maximum";
$install_lang["media_items_per_page_field"] = "Emner pr. side";
$install_lang["media_settings_module"] = "Media indstillinger";
$install_lang["min"] = "Min";
$install_lang["mobile_app_title"] = "Mobile applications"; // from en
$install_lang["mobile_app_txt"] = "Få adgang til vores hjemmeside fra din mobile enhed og vær i kontakt, selv på farten.";
$install_lang["mod_installer_admin_login_text"] = "For at komme til moduler management panel, skal du logge ind. <Eller> Du finder login og password info i filen <b> application/ config / install.php </ b>";
$install_lang["multiselect_all_text"] = "Alle muligheder er valgt";
$install_lang["multiselect_change"] = "Redigér";
$install_lang["multiselect_of"] = "fra";
$install_lang["multiselect_please_select"] = "Vælg venligst mindst een mulighed";
$install_lang["multiselect_select_all"] = "Vælg alle";
$install_lang["multiselect_selected"] = "valgte";
$install_lang["my_contacts"] = "Mine kontakter";
$install_lang["nav_first"] = "Første";
$install_lang["nav_last"] = "Sidste";
$install_lang["nav_next"] = "Næste";
$install_lang["nav_prev"] = "Forrige";
$install_lang["nav_user_first"] = "‹ Første";
$install_lang["nav_user_last"] = "Sidste ›";
$install_lang["nav_user_next"] = "›";
$install_lang["nav_user_prev"] = "‹";
$install_lang["new_messages"] = "Nye beskeder";
$install_lang["news_settings_module"] = "Nyheds indstillinger";
$install_lang["news_userside_items_per_page_field"] = "Nyheder pr. side";
$install_lang["no_information"] = "Ingen informationer";
$install_lang["no_objects_select"] = "Vælg venligst mindst een mulighed";
$install_lang["no_str"] = "Nej";
$install_lang["not_found"] = "Siden blev ikke fundet";
$install_lang["note_types_translate"] = "Oversæt tekst";
$install_lang["notify_stick"] = "Stick"; // from en
$install_lang["option_checkbox_no"] = "Nej";
$install_lang["option_checkbox_yes"] = "Ja";
$install_lang["or"] = "eller";
$install_lang["others_languages"] = "Other languages"; // from en
$install_lang["overflow_settings_module"] = "Flyder over";
$install_lang["page_not_found"] = "Den side, du søgte findes ikke. Du har måske skrevet forkert adresse eller siden kan være flyttet.";
$install_lang["payments_items_per_page_field"] = "Betaling status per side";
$install_lang["payments_settings_module"] = "Betalings indstillinger";
$install_lang["return_home"] = "Gå til hjemmeside";
$install_lang["saved_searches"] = "Gemte søgninger";
$install_lang["search_all_column"] = "Search all columns"; // from en
$install_lang["search_people"] = "Søg personer";
$install_lang["select_all"] = "Vælg alle";
$install_lang["select_default"] = "Vælg venligst";
$install_lang["seo_tags_homepage_header"] = "Hjemmeside";
$install_lang["seo_tags_homepage_title"] = "Dating Pro : Home page";
$install_lang["seo_tags_index_title"] = "Dating Pro : Index page";
$install_lang["sett_apply_job_item"] = "Applicationer";
$install_lang["sett_banners_item"] = "Banners";
$install_lang["sett_countries_item"] = "Lande";
$install_lang["sett_date_formats_item"] = "Dato format";
$install_lang["sett_im_item"] = "IM";
$install_lang["sett_mailbox_item"] = "Mailbox";
$install_lang["sett_media_item"] = "Media";
$install_lang["sett_news_item"] = "Nyheder";
$install_lang["sett_numerics_item"] = "Pagination";
$install_lang["sett_overview_item"] = "Oversigt";
$install_lang["sett_payments_item"] = "Betalinger";
$install_lang["sett_start_item"] = "Standarder";
$install_lang["sett_wall_events_item"] = "Væg";
$install_lang["showing"] = "Viser";
$install_lang["sort_by"] = "Sort´er med";
$install_lang["start_admin_items_per_page_field"] = "Antal emner pr side i admin mode";
$install_lang["start_index_items_per_page_field"] = "Antal emner pr side i bruger mode";
$install_lang["start_settings_module"] = "Standarder";
$install_lang["stat_payments"] = "Earnings per week"; // from en
$install_lang["stat_payments_all"] = "Total earnings"; // from en
$install_lang["stat_payments_avg"] = "Average spend"; // from en
$install_lang["stat_profile_viewed"] = "Profile views"; // from en
$install_lang["stat_registered"] = "New registrations per week"; // from en
$install_lang["success_date_format_update"] = "Dato format er opdateret";
$install_lang["success_update_numerics_data"] = "Numerisk indstillinger er opdateret";
$install_lang["system_version"] = "System version"; // from en
$install_lang["system_version_available"] = "<a href=\"http://www.datingpro.com/blog/meet-the-new-version-of-pg-dating-pro-software-2016-8-honey/\">Update your site now to version [version]</a>"; // from en
$install_lang["template"] = "Template";
$install_lang["text_error"] = "Siden du søgte kan ikke findes";
$install_lang["text_of"] = "af";
$install_lang["text_pages"] = "Side";
$install_lang["text_promo"] = "Find dit match";
$install_lang["text_promo_description"] = "Opret en simpel profil, opload dine fotos, og snart vil du være i netværk med vores utrolige singler. Online dating kunne ikke være nemmere!";
$install_lang["text_promo_second"] = "På udkig efter kærligheden, en ny ven eller det perfekte match? Så har du fundet det helt rigtige sted!";
$install_lang["text_social_promo"] = "Dating Pro er et socialt netværk, der forbinder dig med mennesker fra nær og fjern";
$install_lang["text_status"] = "Status";
$install_lang["today_on_site"] = "I dag på siden";
$install_lang["total"] = "Total";
$install_lang["unselect_all"] = "Fravælg alle";
$install_lang["update"] = "Opdatér";
$install_lang["use_last_search"] = "Brug sidste søgning";
$install_lang["users_items_per_page_field"] = "Brugere pr. side";
$install_lang["users_settings_module"] = "Brugernes indstillinger";
$install_lang["view"] = "Se";
$install_lang["view_all"] = "Se alle";
$install_lang["wall_events_events_max_count_field"] = "Max antal væg arrangementer";
$install_lang["wall_events_items_per_page_field"] = "Arrangementer pr. side";
$install_lang["wall_events_live_period_field"] = "Væg begivenheder aktivitet periode (dage, 0 = ubegrænset)";
$install_lang["wall_events_settings_module"] = "Væg begivenheder indstillinger";
$install_lang["yes_str"] = "Ja";

