<?php

$install_lang["add_funds_to_my_account"] = "เพ่ิมเงินในบัญชี";
$install_lang["admin_header_numerics_change"] = "เปลี่ยนแปลงเกี่ยวกับตัวเลขเว็บไซ์";
$install_lang["admin_header_settings_countries"] = "Countries format"; // from en
$install_lang["admin_header_settings_date_formats"] = "Date format"; // from en
$install_lang["admin_header_settings_numerics"] = "Pagination rules"; // from en
$install_lang["admin_header_settings_overview"] = "Numerics overview"; // from en
$install_lang["applications"] = "แอพพลิเคชั่น";
$install_lang["apply_job_items_per_page_field"] = "รายการต่อหน้า";
$install_lang["apply_job_settings_module"] = "การตั้งค่าสำหรับรายการแอพพลิเคชั่น";
$install_lang["arrow_down"] = "&darr;";
$install_lang["arrow_up"] = "&uarr;";
$install_lang["available_browsers_text1"] = "ท่านกำลังใช้เวอร์ชั่นเบราเซอร์รุ่นเก่า";
$install_lang["available_browsers_text2"] = "กรุณาทำการอัพเกรดเว็บเบราเซอร์รุ่นปัจจุบันเพื่อประสบการณ์ที่ดีกว่า";
$install_lang["banners_button_custom"] = "รับคุณสมบัติพิเศษ";
$install_lang["banners_button_design"] = "สั่งเลยตอนนี้";
$install_lang["banners_button_modules"] = "รับแพคเกจ";
$install_lang["banners_button_packages"] = "รับแพคเกจ";
$install_lang["banners_description_custom"] = "สั่งเปลี่ยนแปลงแบบที่กำหนดเองจากวิศวกรรมที่ออกแบบเว็บไซต์ของท่าน";
$install_lang["banners_description_design"] = "-การรวมดีไซน์<br>-ดีไซน์โลโก้";
$install_lang["banners_description_modules"] = "เพ่ิมเว็บไซต์ของท่านด้วยปลั๊กอินและแอดออนอันใหม่";
$install_lang["banners_description_packages"] = "ได้รับทุกอย่างที่ต้องการสำหรับเริ่มใช้เว็บไซต์หาคู่";
$install_lang["banners_header_custom"] = "มีคำขอพิเศษ?";
$install_lang["banners_header_design"] = "<div class='fleft'>MAKE YOUR SITE</div> <div class='inverted fleft'>UNIQUE</div>"; // from en
$install_lang["banners_header_modules"] = "ปลั๊กอิน & แอดออนส์";
$install_lang["banners_header_packages"] = "แพคเกจ";
$install_lang["banners_items_per_page_field"] = "รายการต่อหน้า";
$install_lang["banners_settings_module"] = "การตั้งค่าแบนเนอร์";
$install_lang["btn_activate"] = "เปิดใช้งาน";
$install_lang["btn_add"] = "เพ่ิม";
$install_lang["btn_add_to"] = "เพิ่มไปยัง";
$install_lang["btn_apply"] = "ใส่เข้าไป";
$install_lang["btn_approve"] = "อนุมัติ";
$install_lang["btn_back"] = "ย้อนกลับ";
$install_lang["btn_cancel"] = "ยกเลิก";
$install_lang["btn_change"] = "เปลี่ยนแปลง";
$install_lang["btn_choose_file"] = "อัพโหลดไฟล์จากคอมพิวเตอร์";
$install_lang["btn_clear"] = "รีเซต";
$install_lang["btn_close"] = "ปิด";
$install_lang["btn_create"] = "สร้าง";
$install_lang["btn_decline"] = "ปฏิเสธ";
$install_lang["btn_delete"] = "ลบ";
$install_lang["btn_done"] = "Done"; // from en
$install_lang["btn_edit"] = "แก้ไข";
$install_lang["btn_login"] = "ลงชื่อเข้าใช้";
$install_lang["btn_logoff"] = "ออกจากระบบ";
$install_lang["btn_logout"] = "ลงชื่อออก";
$install_lang["btn_ok"] = "โอเค";
$install_lang["btn_preview"] = "พรีวิว";
$install_lang["btn_refresh"] = "รีเฟรช";
$install_lang["btn_register"] = "ลงทะเบียน";
$install_lang["btn_reply"] = "ตอบกลับ";
$install_lang["btn_restore"] = "ฟื้นฟู";
$install_lang["btn_save"] = "บันทึก";
$install_lang["btn_saving"] = "กำลังบันทึก...";
$install_lang["btn_search"] = "ค้นหา";
$install_lang["btn_send"] = "ส่ง";
$install_lang["btn_show"] = "แสดง";
$install_lang["btn_support"] = "สนับสนุน";
$install_lang["btn_tableicon_is_active"] = "Active"; // from en
$install_lang["btn_tableicon_is_not_active"] = "Inactive"; // from en
$install_lang["btn_tableicon_no"] = "No"; // from en
$install_lang["btn_tableicon_yes"] = "Yes"; // from en
$install_lang["btn_upload"] = "อัพโหลด";
$install_lang["btn_view_more"] = "ดูเพ่ิมเติม";
$install_lang["change_my_pass"] = "เปลี่ยนรหัสผ่าน";
$install_lang["contact_admin"] = "ติดต่อผู้ดูแลระบบ";
$install_lang["content_removed"] = "Content has been removed"; // from en
$install_lang["copyright"] = "&copy;&nbsp;2016&nbsp;<a href=\"http://www.pilotgroup.net/\">Pilot Group Ltd</a>, สงวนลิขสิทธิ์";
$install_lang["countries_output_city_format_field"] = "รูปแบบข้อมูลเมือง";
$install_lang["countries_output_country_format_field"] = "รูปแบบข้อมูลประเทศ";
$install_lang["countries_output_region_format_field"] = "รูปแบบข้อมูลภูมิภาค";
$install_lang["countries_settings_module"] = "การตั้งค่าประเทศ";
$install_lang["date_format_day"] = "วัน";
$install_lang["date_format_day_with_zero"] = "ตัวเลขโดยมีเลขศูนย์";
$install_lang["date_format_day_without_zero"] = "ตัวเลขโดยไม่มีเลขศูนย์";
$install_lang["date_format_hours"] = "เวลา";
$install_lang["date_format_hours_12_with_zero"] = "12 ชั่วโมงโดยมีเลขศูนย์";
$install_lang["date_format_hours_12_without_zero"] = "12 ชั่วโมงโดยไม่มีเลขศูนย์";
$install_lang["date_format_hours_24_with_zero"] = "24 ชั่วโมงโดยมีเลขศูนย์";
$install_lang["date_format_hours_24_without_zero"] = "24ชั่วโมงโดยไม่มีเลขศูนย์";
$install_lang["date_format_minutes"] = "นาที";
$install_lang["date_format_minutes_with_zero"] = "ตัวเลขโดยมีเลขศูนย์";
$install_lang["date_format_minutes_without_zero"] = "ตัวเลขโดยไม่มีเลขศูนย์";
$install_lang["date_format_month"] = "เดือน";
$install_lang["date_format_month_full"] = "เต็ม";
$install_lang["date_format_month_short"] = "สั้น";
$install_lang["date_format_month_with_zero"] = "ตัวเลขโดยมีเลขศูนย์";
$install_lang["date_format_month_without_zero"] = "ตัวเลขโดยไม่มีเลขศูนย์";
$install_lang["date_format_seconds"] = "วินาที";
$install_lang["date_format_seconds_with_zero"] = "ตัวเลขโดยมีเลขศูนย์";
$install_lang["date_format_seconds_without_zero"] = "ตัวเลขโดยไม่มีเลขศูนย์";
$install_lang["date_format_week_day"] = "วันต่างๆในสัปดาห์";
$install_lang["date_format_week_day_full"] = "ยาว";
$install_lang["date_format_week_day_short"] = "สั้น";
$install_lang["date_format_year"] = "ปี";
$install_lang["date_format_year_2"] = "ตัวเลขสองหลัก";
$install_lang["date_format_year_4"] = "ตัวเลขสี่หลัก";
$install_lang["date_formats_date_literal_description"] = "หลักพื้นฐานในโหมดผุ้ใช้งาน";
$install_lang["date_formats_date_literal_field"] = "วันที่ตัวหนังสือ";
$install_lang["date_formats_date_numeric_description"] = "ไม่มีที่ไหน";
$install_lang["date_formats_date_numeric_field"] = "วันที่เป็นตัวเลข";
$install_lang["date_formats_date_time_literal_description"] = "หลักพื้นฐานในโหมดของผุ้ดูแลระบบ";
$install_lang["date_formats_date_time_literal_field"] = "วันเวลาแบบตัวหนังสือ";
$install_lang["date_formats_date_time_numeric_description"] = "โหมดผู้ดูแลระบบ";
$install_lang["date_formats_date_time_numeric_field"] = "วันเวลาแบบตัวเลข";
$install_lang["date_formats_settings_module"] = "รูปแบบวันที่";
$install_lang["date_formats_time_literal_description"] = "ไม่มีที่ไหน";
$install_lang["date_formats_time_literal_field"] = "เวลาแบบตัวหนังสือ";
$install_lang["date_formats_time_numeric_description"] = "ไม่มีที่ไหน";
$install_lang["date_formats_time_numeric_field"] = "เวลาเป็นตัวเลข";
$install_lang["date_formats_used_in"] = "ใช้ใน";
$install_lang["donate"] = "Donations"; // from en
$install_lang["donate_amount"] = "Amount"; // from en
$install_lang["donate_approve"] = "Approve"; // from en
$install_lang["donate_approved"] = "Approved"; // from en
$install_lang["donate_comment"] = "Comment"; // from en
$install_lang["donate_decline"] = "Decline"; // from en
$install_lang["donate_declined"] = "Declined"; // from en
$install_lang["donate_declined_by_me"] = "Declined by me"; // from en
$install_lang["donate_declined_by_sender"] = "Declined by sender"; // from en
$install_lang["donate_declined_by_user"] = "Declined by user"; // from en
$install_lang["donate_no_data"] = "No transactions"; // from en
$install_lang["donate_status"] = "Status"; // from en
$install_lang["donate_waiting"] = "Waiting"; // from en
$install_lang["edit_my_profile"] = "แก้ไข โปรไฟล์";
$install_lang["error_date_format_empty"] = "Empty date format"; // from en
$install_lang["error_demo_mode"] = "คุณลักษณะบางประการถูกปิดใช้งานในตัวอย่างออนไลน์ด้วยเหตุผลด้านความปลอดภัย<br>เวอร์ชั่นการทดลองใช้เซิร์ฟเวอร์พร้อมสำหรับการทดลองใช้ <a href='http://www.datingpro.com/contact/'>ติดต่อเรา</a> สำหรับรายละเอียดเพ่ิมเติม";
$install_lang["error_numerics_empty"] = "ค่าว่างเปล่า: [field]";
$install_lang["error_output_city_format_empty"] = "Empty output city format"; // from en
$install_lang["error_output_country_format_empty"] = "Empty output country format"; // from en
$install_lang["error_output_region_format_empty"] = "Empty output region format"; // from en
$install_lang["error_product_key_incorrect"] = "คีย์คำสั่งผิดหรือว่างเปล่า";
$install_lang["example"] = "ตัวอย่าง";
$install_lang["features_chats"] = "Text and video chats"; // from en
$install_lang["features_chats_txt"] = "See someone you like? Send a wink or a virtual gift, add them to your List of Favourites. Use Instant Messenger or a video chat to learn more about each other!"; // from en
$install_lang["features_likeme"] = "LikeMe"; // from en
$install_lang["features_likeme_txt"] = "LikeMe feature lets you like or skip site members. In case there's been a mutual 'like', you both can continue communication directly on the site."; // from en
$install_lang["features_nearest"] = "Nearest users"; // from en
$install_lang["features_nearest_txt"] = "Nearest users is a special search page with an interactive map. You can search by radius, and your own location will be the starting point. Exact location is not disclosed so it is perfectly safe."; // from en
$install_lang["fhf_back_link"] = "Return to homepage"; // from en
$install_lang["fhf_text"] = "The page you were looking for does not exist. You may have mistyped the address or the page may have moved."; // from en
$install_lang["fhf_title"] = "Not found"; // from en
$install_lang["field_login"] = "ลงชื่อเข้าใช้";
$install_lang["field_order_key"] = "คีย์คำสั่ง";
$install_lang["field_password"] = "รหัสผ่าน";
$install_lang["field_placeholder"] = "Start typing..."; // from en
$install_lang["filter_header"] = "กรอง";
$install_lang["from_last_week"] = "since last week"; // from en
$install_lang["geolocation_onoff"] = "Establish the coordinates of users"; // from en
$install_lang["header_actions"] = "ทำงาน";
$install_lang["header_admin_homepage"] = "ยินดีต้อนรับ | หน้าหลักผู้ดูแลระบบ";
$install_lang["header_donate_view_block"] = "My transactions"; // from en
$install_lang["header_error"] = "404 ไม่พบหน้าเพจ";
$install_lang["header_filters"] = "Filters"; // from en
$install_lang["header_homepage"] = "หน้าหลักของฉัน";
$install_lang["header_inline_lang_edit"] = "แปล";
$install_lang["header_modinstaller_login"] = "ลงชื่อเข้าสู่การจัดการโมดูล";
$install_lang["header_my_statistics"] = "สถิติของฉัน";
$install_lang["header_settings_geolocation"] = "Geolocation settings"; // from en
$install_lang["header_settings_numerics_list"] = "เป็นตัวเลข";
$install_lang["header_start_page"] = "หน้าหลัก";
$install_lang["lang_editor"] = "ตัวแก้ไขภาษา";
$install_lang["latest_added_ads_header"] = "ที่เพ่ิมล่าสุด";
$install_lang["link_details"] = "Details"; // from en
$install_lang["link_less_options"] = "ตัวเลือกน้อยกว่านี้";
$install_lang["link_more_options"] = "ตัวเลือกมากกว่านี้";
$install_lang["mailbox_attach_limit_field"] = "ขีดจำกัดของสิ่งที่แนบมา";
$install_lang["mailbox_items_per_page_field"] = "รายการต่อหน้า";
$install_lang["mailbox_settings_module"] = "การตั้งค่ากล่องจดหมาย";
$install_lang["make_active"] = "เปิดใช้งาน";
$install_lang["make_inactive"] = "ปิดการใช้งาน";
$install_lang["max"] = "สูงสุด";
$install_lang["max_photo_hint"] = "สูงสุด";
$install_lang["media_items_per_page_field"] = "รายการต่อหน้า";
$install_lang["media_settings_module"] = "การตั้งค่ามีเดีย";
$install_lang["min"] = "นาที";
$install_lang["mobile_app_title"] = "Mobile applications"; // from en
$install_lang["mobile_app_txt"] = "Access our site from your mobile device and always keep in touch, even on the go."; // from en
$install_lang["mod_installer_admin_login_text"] = "การเข้าถึงแผงการจัดการโมดูล กรุณาลงชื่อเข้าใช้.<br>ท่านจะพบกับข้อมูลการลงชื่อเข้าใช้และรหัสผ่านภายในไฟล์ <b>application/config/install.php</b>";
$install_lang["multiselect_all_text"] = "ตัวเลือกทั้งหมดถูกเลือก";
$install_lang["multiselect_change"] = "แก้ไข";
$install_lang["multiselect_of"] = "ของ";
$install_lang["multiselect_please_select"] = "กรุณาเลือกอย่างน้อยหนึ่งตัวเลือก";
$install_lang["multiselect_select_all"] = "เลือกทั้งหมด";
$install_lang["multiselect_selected"] = "ที่เลือก";
$install_lang["my_contacts"] = "รายชื่อผุ้ติดต่อของฉัน";
$install_lang["nav_first"] = "แรก";
$install_lang["nav_last"] = "สุดท้าย";
$install_lang["nav_next"] = "ต่อไป";
$install_lang["nav_prev"] = "ก่อนหน้านี้";
$install_lang["nav_user_first"] = "‹ แรก";
$install_lang["nav_user_last"] = "สุดท้าย ›";
$install_lang["nav_user_next"] = "›";
$install_lang["nav_user_prev"] = "‹";
$install_lang["new_messages"] = "ข้อความใหม่";
$install_lang["news_settings_module"] = "การตั้งค่าข่าว";
$install_lang["news_userside_items_per_page_field"] = "ข่าวต่อหน้า";
$install_lang["no_information"] = "ไม่มีข้อมูล";
$install_lang["no_objects_select"] = "Please select at least one item"; // from en
$install_lang["no_str"] = "ไม่มี";
$install_lang["not_found"] = "Not Found"; // from en
$install_lang["note_types_translate"] = "แปลข้อความ";
$install_lang["notify_stick"] = "Stick"; // from en
$install_lang["option_checkbox_no"] = "ไม่";
$install_lang["option_checkbox_yes"] = "ใช่";
$install_lang["or"] = "หรือ";
$install_lang["others_languages"] = "Other languages"; // from en
$install_lang["overflow_settings_module"] = "ล้น";
$install_lang["page_not_found"] = "The page you were looking for does not exist. You may have mistyped the address or the page may have moved."; // from en
$install_lang["payments_items_per_page_field"] = "สถิติรายการการชำระเงินต่อหน้า";
$install_lang["payments_settings_module"] = "การตั้งค่าการชำระเงิน";
$install_lang["return_home"] = "Go to homepage"; // from en
$install_lang["saved_searches"] = "บันทึกการค้นหาแล้ว";
$install_lang["search_all_column"] = "Search all columns"; // from en
$install_lang["search_people"] = "ค้นหาผู้คน";
$install_lang["select_all"] = "ทำเครื่องหมายทั้งหมด";
$install_lang["select_default"] = "กรุณาเลือก";
$install_lang["seo_tags_homepage_header"] = "หน้าหลัก";
$install_lang["seo_tags_homepage_title"] = "Dating Pro : หน้าหลัก";
$install_lang["seo_tags_index_title"] = "Dating Pro : หน้าดัชนี";
$install_lang["sett_apply_job_item"] = "แอพพลิเคชั่น";
$install_lang["sett_banners_item"] = "แบนเนอร์";
$install_lang["sett_countries_item"] = "ประเทศต่างๆ";
$install_lang["sett_date_formats_item"] = "รูปแบบวันที่";
$install_lang["sett_im_item"] = "IM";
$install_lang["sett_mailbox_item"] = "กล่องจดหมาย";
$install_lang["sett_media_item"] = "มีเดีย";
$install_lang["sett_news_item"] = "ข่าว";
$install_lang["sett_numerics_item"] = "หมายเลขหน้า";
$install_lang["sett_overview_item"] = "โดยรวม";
$install_lang["sett_payments_item"] = "การชำระเงิน";
$install_lang["sett_start_item"] = "ค่าเริ่มต้น";
$install_lang["sett_wall_events_item"] = "หน้าวอลล์";
$install_lang["showing"] = "กำลังแสดง";
$install_lang["sort_by"] = "เรียงลำดับโดย";
$install_lang["start_admin_items_per_page_field"] = "จำนวนรายการต่อหน้าในโหมดของผู้ดูแลระบบ";
$install_lang["start_index_items_per_page_field"] = "จำนวนรายการต่อหน้าในโหมดของผู้ใช้งาน";
$install_lang["start_settings_module"] = "ค่าเริ่มต้น";
$install_lang["stat_payments"] = "Earnings per week"; // from en
$install_lang["stat_payments_all"] = "Total earnings"; // from en
$install_lang["stat_payments_avg"] = "Average spend"; // from en
$install_lang["stat_profile_viewed"] = "Profile views"; // from en
$install_lang["stat_registered"] = "New registrations per week"; // from en
$install_lang["success_date_format_update"] = "Date format is successfully updated"; // from en
$install_lang["success_update_numerics_data"] = "อัพเดตการตั้งค่าแบบตัวเรียบร้อยแล้ว";
$install_lang["system_version"] = "เวอร์ชั่นระบบ";
$install_lang["system_version_available"] = "<a href=\"http://www.datingpro.com/blog/meet-the-new-version-of-pg-dating-pro-software-2016-8-honey/\">Update your site now to version [version]</a>"; // from en
$install_lang["template"] = "Template"; // from en
$install_lang["text_error"] = "ไม่พบหน้าที่ท่านต้องการ";
$install_lang["text_of"] = "ของ";
$install_lang["text_pages"] = "หน้า";
$install_lang["text_promo"] = "Find your match"; // from en
$install_lang["text_promo_description"] = "Create a simple profile, post your photos, and soon you'll be networking with our incredible singles. Online dating couldn't be easier!"; // from en
$install_lang["text_promo_second"] = "Are you looking for love, a new friend or a perfect companion? Our site is the place for people who are interested in a true relationship!"; // from en
$install_lang["text_social_promo"] = "SocialBiz is a social network that connects you with the people around you."; // from en
$install_lang["text_status"] = "Status"; // from en
$install_lang["today_on_site"] = "วันนี้บนเว็บไซต์";
$install_lang["total"] = "ทั้งหมด";
$install_lang["unselect_all"] = "ยกเลิกการทำเครื่องหมายทั้งหมด";
$install_lang["update"] = "อัพเดต";
$install_lang["use_last_search"] = "ใช้การค้นหาครั้งล่าสุด";
$install_lang["users_items_per_page_field"] = "ผู้ใช้งสานต่อหน้า";
$install_lang["users_settings_module"] = "การตั้งค่าผู้ใช้งาน";
$install_lang["view"] = "ดู";
$install_lang["view_all"] = "ดูท้้งหมด";
$install_lang["wall_events_events_max_count_field"] = "Max number of wall events"; // from en
$install_lang["wall_events_items_per_page_field"] = "เรื่องต่อหน้า";
$install_lang["wall_events_live_period_field"] = "Wall events activity period (days, 0 = unlimited)"; // from en
$install_lang["wall_events_settings_module"] = "การตั้งค่าอีเว้นท์หน้าวอลล์";
$install_lang["yes_str"] = "ใช่";

